// @generated by protoc-gen-es v2.10.2 with parameter "target=ts,import_extension=ts"
// @generated from file geometry/v1/zone.proto (package geometry.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb.ts";
import type { Point } from "./point_pb.ts";
import { file_geometry_v1_point } from "./point_pb.ts";
import { file_validation_v1_predefined_string_rules } from "../../validation/v1/predefined_string_rules_pb.ts";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file geometry/v1/zone.proto.
 */
export const file_geometry_v1_zone: GenFile = /*@__PURE__*/
  fileDesc("ChZnZW9tZXRyeS92MS96b25lLnByb3RvEgtnZW9tZXRyeS52MSKHAQoOWm9uZURlZmluaXRpb24SFQoCaWQYASABKAlCCbpIBnIEqOwwARIXCgRuYW1lGAIgASgJQgm6SAZyBIDxBAESDAoEaWNvbhgDIAEoCRITCgtkZXNjcmlwdGlvbhgEIAEoCRIiCgZwb2ludHMYBSADKAsyEi5nZW9tZXRyeS52MS5Qb2ludCI9Cg9ab25lRGVmaW5pdGlvbnMSKgoFaXRlbXMYASADKAsyGy5nZW9tZXRyeS52MS5ab25lRGVmaW5pdGlvbkKvAQoPY29tLmdlb21ldHJ5LnYxQglab25lUHJvdG9QAVo7Z2l0aHViLmNvbS9jb2JvdGFyL3Byb3RvY29sL21lc3NhZ2VzL2dlb21ldHJ5L3YxO2dlb21ldHJ5djGiAgNHWFiqAhRNZXNzYWdlcy5HZW9tZXRyeS5WMcoCC0dlb21ldHJ5XFYx4gIXR2VvbWV0cnlcVjFcR1BCTWV0YWRhdGHqAgxHZW9tZXRyeTo6VjFiBnByb3RvMw", [file_buf_validate_validate, file_geometry_v1_point, file_validation_v1_predefined_string_rules]);

/**
 * @generated from message geometry.v1.ZoneDefinition
 */
export type ZoneDefinition = Message<"geometry.v1.ZoneDefinition"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string icon = 3;
   */
  icon: string;

  /**
   * @generated from field: string description = 4;
   */
  description: string;

  /**
   * @generated from field: repeated geometry.v1.Point points = 5;
   */
  points: Point[];
};

/**
 * Describes the message geometry.v1.ZoneDefinition.
 * Use `create(ZoneDefinitionSchema)` to create a new message.
 */
export const ZoneDefinitionSchema: GenMessage<ZoneDefinition> = /*@__PURE__*/
  messageDesc(file_geometry_v1_zone, 0);

/**
 * @generated from message geometry.v1.ZoneDefinitions
 */
export type ZoneDefinitions = Message<"geometry.v1.ZoneDefinitions"> & {
  /**
   * @generated from field: repeated geometry.v1.ZoneDefinition items = 1;
   */
  items: ZoneDefinition[];
};

/**
 * Describes the message geometry.v1.ZoneDefinitions.
 * Use `create(ZoneDefinitionsSchema)` to create a new message.
 */
export const ZoneDefinitionsSchema: GenMessage<ZoneDefinitions> = /*@__PURE__*/
  messageDesc(file_geometry_v1_zone, 1);

