// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ar/v1/feedback_info.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Messages.AR.V1 {

  /// <summary>Holder for reflection information generated from ar/v1/feedback_info.proto</summary>
  public static partial class FeedbackInfoReflection {

    #region Descriptor
    /// <summary>File descriptor for ar/v1/feedback_info.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FeedbackInfoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chlhci92MS9mZWVkYmFja19pbmZvLnByb3RvEgVhci52MRoSYXIvdjEvZXZl",
            "bnRzLnByb3RvGhRhci92MS9mZWVkYmFjay5wcm90bxobYnVmL3ZhbGlkYXRl",
            "L3ZhbGlkYXRlLnByb3RvGit2YWxpZGF0aW9uL3YxL3ByZWRlZmluZWRfc3Ry",
            "aW5nX3J1bGVzLnByb3RvIrcEChNGZWVkYmFja0luZm9NZXNzYWdlEh0KBG5h",
            "bWUYAiABKAlCCbpIBnIEgPEEAVIEbmFtZRISCgRpY29uGAMgASgJUgRpY29u",
            "EiAKC2Rlc2NyaXB0aW9uGAQgASgJUgtkZXNjcmlwdGlvbhI0CgR0eXBlGAUg",
            "ASgOMhMuYXIudjEuRmVlZGJhY2tUeXBlQgu6SAiCAQIQAcgBAVIEdHlwZRI0",
            "CgVncm91cBgGIAEoDjIULmFyLnYxLkZlZWRiYWNrR3JvdXBCCLpIBYIBAhAB",
            "UgVncm91cBIjCg1yZXF1aXJlX2FnZW50GAcgASgIUgxyZXF1aXJlQWdlbnQS",
            "IwoNcmVxdWlyZV9mcmFtZRgIIAEoCFIMcmVxdWlyZUZyYW1lEkIKEmNvbnN1",
            "bWVyc19yZXF1aXJlZBgJIAMoCzITLmFyLnYxLkV4Y2hhbmdlVHlwZVIRY29u",
            "c3VtZXJzUmVxdWlyZWQSQgoSY29uc3VtZXJzX29wdGlvbmFsGAogAygLMhMu",
            "YXIudjEuRXhjaGFuZ2VUeXBlUhFjb25zdW1lcnNPcHRpb25hbBJGChFyZXF1",
            "aXJlZF9oYW5kbGVycxgLIAMoCzIZLmFyLnYxLkhhbmRsZXJSZXF1aXJlbWVu",
            "dFIQcmVxdWlyZWRIYW5kbGVycxIpCgVlbWl0cxgMIAMoCzITLmFyLnYxLkV4",
            "Y2hhbmdlVHlwZVIFZW1pdHMSGgoIZGlzYWJsZWQYDSABKAhSCGRpc2FibGVk",
            "IkgKFEZlZWRiYWNrSW5mb01lc3NhZ2VzEjAKBWluZm9zGAEgAygLMhouYXIu",
            "djEuRmVlZGJhY2tJbmZvTWVzc2FnZVIFaW5mb3MqngEKDUZlZWRiYWNrR3Jv",
            "dXASHgoaRkVFREJBQ0tfR1JPVVBfVU5TUEVDSUZJRUQQABIaChZGRUVEQkFD",
            "S19HUk9VUF9HRU5FUkFMEAESGAoURkVFREJBQ0tfR1JPVVBfUk9CT1QQAhIX",
            "ChNGRUVEQkFDS19HUk9VUF9UQVNLEAMSHgoaRkVFREJBQ0tfR1JPVVBfRU5W",
            "SVJPTk1FTlQQBEKNAQoJY29tLmFyLnYxQhFGZWVkYmFja0luZm9Qcm90b1AB",
            "Wi9naXRodWIuY29tL2NvYm90YXIvcHJvdG9jb2wvbWVzc2FnZXMvYXIvdjE7",
            "YXJ2MaICA0FYWKoCDk1lc3NhZ2VzLkFSLlYxygIFQXJcVjHiAhFBclxWMVxH",
            "UEJNZXRhZGF0YeoCBkFyOjpWMWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Messages.AR.V1.EventsReflection.Descriptor, global::Messages.AR.V1.FeedbackReflection.Descriptor, global::Buf.Validate.ValidateReflection.Descriptor, global::Validation.V1.PredefinedStringRulesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Messages.AR.V1.FeedbackGroup), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Messages.AR.V1.FeedbackInfoMessage), global::Messages.AR.V1.FeedbackInfoMessage.Parser, new[]{ "Name", "Icon", "Description", "Type", "Group", "RequireAgent", "RequireFrame", "ConsumersRequired", "ConsumersOptional", "RequiredHandlers", "Emits", "Disabled" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Messages.AR.V1.FeedbackInfoMessages), global::Messages.AR.V1.FeedbackInfoMessages.Parser, new[]{ "Infos" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum FeedbackGroup {
    [pbr::OriginalName("FEEDBACK_GROUP_UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("FEEDBACK_GROUP_GENERAL")] General = 1,
    [pbr::OriginalName("FEEDBACK_GROUP_ROBOT")] Robot = 2,
    [pbr::OriginalName("FEEDBACK_GROUP_TASK")] Task = 3,
    [pbr::OriginalName("FEEDBACK_GROUP_ENVIRONMENT")] Environment = 4,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class FeedbackInfoMessage : pb::IMessage<FeedbackInfoMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<FeedbackInfoMessage> _parser = new pb::MessageParser<FeedbackInfoMessage>(() => new FeedbackInfoMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<FeedbackInfoMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Messages.AR.V1.FeedbackInfoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FeedbackInfoMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FeedbackInfoMessage(FeedbackInfoMessage other) : this() {
      name_ = other.name_;
      icon_ = other.icon_;
      description_ = other.description_;
      type_ = other.type_;
      group_ = other.group_;
      requireAgent_ = other.requireAgent_;
      requireFrame_ = other.requireFrame_;
      consumersRequired_ = other.consumersRequired_.Clone();
      consumersOptional_ = other.consumersOptional_.Clone();
      requiredHandlers_ = other.requiredHandlers_.Clone();
      emits_ = other.emits_.Clone();
      disabled_ = other.disabled_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FeedbackInfoMessage Clone() {
      return new FeedbackInfoMessage(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "icon" field.</summary>
    public const int IconFieldNumber = 3;
    private string icon_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Icon {
      get { return icon_; }
      set {
        icon_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "description" field.</summary>
    public const int DescriptionFieldNumber = 4;
    private string description_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Description {
      get { return description_; }
      set {
        description_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 5;
    private global::Messages.AR.V1.FeedbackType type_ = global::Messages.AR.V1.FeedbackType.Unspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Messages.AR.V1.FeedbackType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "group" field.</summary>
    public const int GroupFieldNumber = 6;
    private global::Messages.AR.V1.FeedbackGroup group_ = global::Messages.AR.V1.FeedbackGroup.Unspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Messages.AR.V1.FeedbackGroup Group {
      get { return group_; }
      set {
        group_ = value;
      }
    }

    /// <summary>Field number for the "require_agent" field.</summary>
    public const int RequireAgentFieldNumber = 7;
    private bool requireAgent_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool RequireAgent {
      get { return requireAgent_; }
      set {
        requireAgent_ = value;
      }
    }

    /// <summary>Field number for the "require_frame" field.</summary>
    public const int RequireFrameFieldNumber = 8;
    private bool requireFrame_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool RequireFrame {
      get { return requireFrame_; }
      set {
        requireFrame_ = value;
      }
    }

    /// <summary>Field number for the "consumers_required" field.</summary>
    public const int ConsumersRequiredFieldNumber = 9;
    private static readonly pb::FieldCodec<global::Messages.AR.V1.ExchangeType> _repeated_consumersRequired_codec
        = pb::FieldCodec.ForMessage(74, global::Messages.AR.V1.ExchangeType.Parser);
    private readonly pbc::RepeatedField<global::Messages.AR.V1.ExchangeType> consumersRequired_ = new pbc::RepeatedField<global::Messages.AR.V1.ExchangeType>();
    /// <summary>
    /// Inputs the action expects to receive
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Messages.AR.V1.ExchangeType> ConsumersRequired {
      get { return consumersRequired_; }
    }

    /// <summary>Field number for the "consumers_optional" field.</summary>
    public const int ConsumersOptionalFieldNumber = 10;
    private static readonly pb::FieldCodec<global::Messages.AR.V1.ExchangeType> _repeated_consumersOptional_codec
        = pb::FieldCodec.ForMessage(82, global::Messages.AR.V1.ExchangeType.Parser);
    private readonly pbc::RepeatedField<global::Messages.AR.V1.ExchangeType> consumersOptional_ = new pbc::RepeatedField<global::Messages.AR.V1.ExchangeType>();
    /// <summary>
    /// Inputs that will enhance the action, but not needed to function
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Messages.AR.V1.ExchangeType> ConsumersOptional {
      get { return consumersOptional_; }
    }

    /// <summary>Field number for the "required_handlers" field.</summary>
    public const int RequiredHandlersFieldNumber = 11;
    private static readonly pb::FieldCodec<global::Messages.AR.V1.HandlerRequirement> _repeated_requiredHandlers_codec
        = pb::FieldCodec.ForMessage(90, global::Messages.AR.V1.HandlerRequirement.Parser);
    private readonly pbc::RepeatedField<global::Messages.AR.V1.HandlerRequirement> requiredHandlers_ = new pbc::RepeatedField<global::Messages.AR.V1.HandlerRequirement>();
    /// <summary>
    /// Events that MUST have at least one handler somewhere else in the system. (i.e., if the action emits these, it expects the environment to react)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Messages.AR.V1.HandlerRequirement> RequiredHandlers {
      get { return requiredHandlers_; }
    }

    /// <summary>Field number for the "emits" field.</summary>
    public const int EmitsFieldNumber = 12;
    private static readonly pb::FieldCodec<global::Messages.AR.V1.ExchangeType> _repeated_emits_codec
        = pb::FieldCodec.ForMessage(98, global::Messages.AR.V1.ExchangeType.Parser);
    private readonly pbc::RepeatedField<global::Messages.AR.V1.ExchangeType> emits_ = new pbc::RepeatedField<global::Messages.AR.V1.ExchangeType>();
    /// <summary>
    /// / Outputs the feedback publishes
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Messages.AR.V1.ExchangeType> Emits {
      get { return emits_; }
    }

    /// <summary>Field number for the "disabled" field.</summary>
    public const int DisabledFieldNumber = 13;
    private bool disabled_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Disabled {
      get { return disabled_; }
      set {
        disabled_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as FeedbackInfoMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(FeedbackInfoMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Icon != other.Icon) return false;
      if (Description != other.Description) return false;
      if (Type != other.Type) return false;
      if (Group != other.Group) return false;
      if (RequireAgent != other.RequireAgent) return false;
      if (RequireFrame != other.RequireFrame) return false;
      if(!consumersRequired_.Equals(other.consumersRequired_)) return false;
      if(!consumersOptional_.Equals(other.consumersOptional_)) return false;
      if(!requiredHandlers_.Equals(other.requiredHandlers_)) return false;
      if(!emits_.Equals(other.emits_)) return false;
      if (Disabled != other.Disabled) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Icon.Length != 0) hash ^= Icon.GetHashCode();
      if (Description.Length != 0) hash ^= Description.GetHashCode();
      if (Type != global::Messages.AR.V1.FeedbackType.Unspecified) hash ^= Type.GetHashCode();
      if (Group != global::Messages.AR.V1.FeedbackGroup.Unspecified) hash ^= Group.GetHashCode();
      if (RequireAgent != false) hash ^= RequireAgent.GetHashCode();
      if (RequireFrame != false) hash ^= RequireFrame.GetHashCode();
      hash ^= consumersRequired_.GetHashCode();
      hash ^= consumersOptional_.GetHashCode();
      hash ^= requiredHandlers_.GetHashCode();
      hash ^= emits_.GetHashCode();
      if (Disabled != false) hash ^= Disabled.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (Icon.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Icon);
      }
      if (Description.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Description);
      }
      if (Type != global::Messages.AR.V1.FeedbackType.Unspecified) {
        output.WriteRawTag(40);
        output.WriteEnum((int) Type);
      }
      if (Group != global::Messages.AR.V1.FeedbackGroup.Unspecified) {
        output.WriteRawTag(48);
        output.WriteEnum((int) Group);
      }
      if (RequireAgent != false) {
        output.WriteRawTag(56);
        output.WriteBool(RequireAgent);
      }
      if (RequireFrame != false) {
        output.WriteRawTag(64);
        output.WriteBool(RequireFrame);
      }
      consumersRequired_.WriteTo(output, _repeated_consumersRequired_codec);
      consumersOptional_.WriteTo(output, _repeated_consumersOptional_codec);
      requiredHandlers_.WriteTo(output, _repeated_requiredHandlers_codec);
      emits_.WriteTo(output, _repeated_emits_codec);
      if (Disabled != false) {
        output.WriteRawTag(104);
        output.WriteBool(Disabled);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (Icon.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Icon);
      }
      if (Description.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Description);
      }
      if (Type != global::Messages.AR.V1.FeedbackType.Unspecified) {
        output.WriteRawTag(40);
        output.WriteEnum((int) Type);
      }
      if (Group != global::Messages.AR.V1.FeedbackGroup.Unspecified) {
        output.WriteRawTag(48);
        output.WriteEnum((int) Group);
      }
      if (RequireAgent != false) {
        output.WriteRawTag(56);
        output.WriteBool(RequireAgent);
      }
      if (RequireFrame != false) {
        output.WriteRawTag(64);
        output.WriteBool(RequireFrame);
      }
      consumersRequired_.WriteTo(ref output, _repeated_consumersRequired_codec);
      consumersOptional_.WriteTo(ref output, _repeated_consumersOptional_codec);
      requiredHandlers_.WriteTo(ref output, _repeated_requiredHandlers_codec);
      emits_.WriteTo(ref output, _repeated_emits_codec);
      if (Disabled != false) {
        output.WriteRawTag(104);
        output.WriteBool(Disabled);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Icon.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Icon);
      }
      if (Description.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Description);
      }
      if (Type != global::Messages.AR.V1.FeedbackType.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (Group != global::Messages.AR.V1.FeedbackGroup.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Group);
      }
      if (RequireAgent != false) {
        size += 1 + 1;
      }
      if (RequireFrame != false) {
        size += 1 + 1;
      }
      size += consumersRequired_.CalculateSize(_repeated_consumersRequired_codec);
      size += consumersOptional_.CalculateSize(_repeated_consumersOptional_codec);
      size += requiredHandlers_.CalculateSize(_repeated_requiredHandlers_codec);
      size += emits_.CalculateSize(_repeated_emits_codec);
      if (Disabled != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(FeedbackInfoMessage other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Icon.Length != 0) {
        Icon = other.Icon;
      }
      if (other.Description.Length != 0) {
        Description = other.Description;
      }
      if (other.Type != global::Messages.AR.V1.FeedbackType.Unspecified) {
        Type = other.Type;
      }
      if (other.Group != global::Messages.AR.V1.FeedbackGroup.Unspecified) {
        Group = other.Group;
      }
      if (other.RequireAgent != false) {
        RequireAgent = other.RequireAgent;
      }
      if (other.RequireFrame != false) {
        RequireFrame = other.RequireFrame;
      }
      consumersRequired_.Add(other.consumersRequired_);
      consumersOptional_.Add(other.consumersOptional_);
      requiredHandlers_.Add(other.requiredHandlers_);
      emits_.Add(other.emits_);
      if (other.Disabled != false) {
        Disabled = other.Disabled;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            Icon = input.ReadString();
            break;
          }
          case 34: {
            Description = input.ReadString();
            break;
          }
          case 40: {
            Type = (global::Messages.AR.V1.FeedbackType) input.ReadEnum();
            break;
          }
          case 48: {
            Group = (global::Messages.AR.V1.FeedbackGroup) input.ReadEnum();
            break;
          }
          case 56: {
            RequireAgent = input.ReadBool();
            break;
          }
          case 64: {
            RequireFrame = input.ReadBool();
            break;
          }
          case 74: {
            consumersRequired_.AddEntriesFrom(input, _repeated_consumersRequired_codec);
            break;
          }
          case 82: {
            consumersOptional_.AddEntriesFrom(input, _repeated_consumersOptional_codec);
            break;
          }
          case 90: {
            requiredHandlers_.AddEntriesFrom(input, _repeated_requiredHandlers_codec);
            break;
          }
          case 98: {
            emits_.AddEntriesFrom(input, _repeated_emits_codec);
            break;
          }
          case 104: {
            Disabled = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            Icon = input.ReadString();
            break;
          }
          case 34: {
            Description = input.ReadString();
            break;
          }
          case 40: {
            Type = (global::Messages.AR.V1.FeedbackType) input.ReadEnum();
            break;
          }
          case 48: {
            Group = (global::Messages.AR.V1.FeedbackGroup) input.ReadEnum();
            break;
          }
          case 56: {
            RequireAgent = input.ReadBool();
            break;
          }
          case 64: {
            RequireFrame = input.ReadBool();
            break;
          }
          case 74: {
            consumersRequired_.AddEntriesFrom(ref input, _repeated_consumersRequired_codec);
            break;
          }
          case 82: {
            consumersOptional_.AddEntriesFrom(ref input, _repeated_consumersOptional_codec);
            break;
          }
          case 90: {
            requiredHandlers_.AddEntriesFrom(ref input, _repeated_requiredHandlers_codec);
            break;
          }
          case 98: {
            emits_.AddEntriesFrom(ref input, _repeated_emits_codec);
            break;
          }
          case 104: {
            Disabled = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class FeedbackInfoMessages : pb::IMessage<FeedbackInfoMessages>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<FeedbackInfoMessages> _parser = new pb::MessageParser<FeedbackInfoMessages>(() => new FeedbackInfoMessages());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<FeedbackInfoMessages> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Messages.AR.V1.FeedbackInfoReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FeedbackInfoMessages() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FeedbackInfoMessages(FeedbackInfoMessages other) : this() {
      infos_ = other.infos_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FeedbackInfoMessages Clone() {
      return new FeedbackInfoMessages(this);
    }

    /// <summary>Field number for the "infos" field.</summary>
    public const int InfosFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Messages.AR.V1.FeedbackInfoMessage> _repeated_infos_codec
        = pb::FieldCodec.ForMessage(10, global::Messages.AR.V1.FeedbackInfoMessage.Parser);
    private readonly pbc::RepeatedField<global::Messages.AR.V1.FeedbackInfoMessage> infos_ = new pbc::RepeatedField<global::Messages.AR.V1.FeedbackInfoMessage>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Messages.AR.V1.FeedbackInfoMessage> Infos {
      get { return infos_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as FeedbackInfoMessages);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(FeedbackInfoMessages other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!infos_.Equals(other.infos_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= infos_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      infos_.WriteTo(output, _repeated_infos_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      infos_.WriteTo(ref output, _repeated_infos_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += infos_.CalculateSize(_repeated_infos_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(FeedbackInfoMessages other) {
      if (other == null) {
        return;
      }
      infos_.Add(other.infos_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            infos_.AddEntriesFrom(input, _repeated_infos_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            infos_.AddEntriesFrom(ref input, _repeated_infos_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
