// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: assembly/v1/process_requests.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Messages.Assembly.V1 {

  /// <summary>Holder for reflection information generated from assembly/v1/process_requests.proto</summary>
  public static partial class ProcessRequestsReflection {

    #region Descriptor
    /// <summary>File descriptor for assembly/v1/process_requests.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProcessRequestsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiJhc3NlbWJseS92MS9wcm9jZXNzX3JlcXVlc3RzLnByb3RvEgthc3NlbWJs",
            "eS52MRobYXNzZW1ibHkvdjEvZXhlY3V0aW9uLnByb3RvGhlhc3NlbWJseS92",
            "MS92YXJpYW50LnByb3RvItcBChJQcm9jZXNzTG9hZFJlcXVlc3QSKgoRcHJv",
            "Y2Vzc19yZWNpcGVfaWQYASABKAlSD3Byb2Nlc3NSZWNpcGVJZBIkCg50YXJn",
            "ZXRfbGluZV9pZBgCIAEoCVIMdGFyZ2V0TGluZUlkElYKFXZhcmlhbnRfY29u",
            "ZmlndXJhdGlvbhgDIAEoCzIhLmFzc2VtYmx5LnYxLlZhcmlhbnRDb25maWd1",
            "cmF0aW9uUhR2YXJpYW50Q29uZmlndXJhdGlvbhIXCgdkcnlfcnVuGAQgASgI",
            "UgZkcnlSdW4ihwUKD1Byb2Nlc3NSdW5Jc3N1ZRI5CgdmYWlsdXJlGAEgASgO",
            "Mh8uYXNzZW1ibHkudjEuUHJvY2Vzc0xvYWRGYWlsdXJlUgdmYWlsdXJlEhgK",
            "B21lc3NhZ2UYAiABKAlSB21lc3NhZ2USQAoIc2V2ZXJpdHkYAyABKA4yJC5h",
            "c3NlbWJseS52MS5Qcm9jZXNzUnVuSXNzdWVTZXZlcml0eVIIc2V2ZXJpdHkS",
            "KgoRcHJvY2Vzc19yZWNpcGVfaWQYBCABKAlSD3Byb2Nlc3NSZWNpcGVJZBI0",
            "ChZzZXF1ZW5jZV9kZWZpbml0aW9uX2lkGAUgASgJUhRzZXF1ZW5jZURlZmlu",
            "aXRpb25JZBIsChJ0YXNrX2RlZmluaXRpb25faWQYBiABKAlSEHRhc2tEZWZp",
            "bml0aW9uSWQSLAoScmVxdWlyZWRfdG9vbF9yb2xlGAcgASgJUhByZXF1aXJl",
            "ZFRvb2xSb2xlEioKEXJlcXVpcmVkX3NraWxsX2lkGAggASgJUg9yZXF1aXJl",
            "ZFNraWxsSWQSMgoVZml4dHVyZV9kZWZpbml0aW9uX2lkGAkgASgJUhNmaXh0",
            "dXJlRGVmaW5pdGlvbklkEh0KCnN0YXRpb25faWQYCiABKAlSCXN0YXRpb25J",
            "ZBIZCghhY3Rvcl9pZBgLIAEoCVIHYWN0b3JJZBIfCgtyZXNvdXJjZV9pZBgM",
            "IAEoCVIKcmVzb3VyY2VJZBIgCgtyZW1lZGlhdGlvbhgNIAEoCVILcmVtZWRp",
            "YXRpb24SQgoKaW1wb3J0YW5jZRgOIAEoDjIiLmFzc2VtYmx5LnYxLlJlcXVp",
            "cmVtZW50SW1wb3J0YW5jZVIKaW1wb3J0YW5jZSKGAwoPVGFza0ZlYXNpYmls",
            "aXR5EiwKEnRhc2tfZGVmaW5pdGlvbl9pZBgBIAEoCVIQdGFza0RlZmluaXRp",
            "b25JZBIaCghmZWFzaWJsZRgCIAEoCFIIZmVhc2libGUSLgoTY2FuZGlkYXRl",
            "X2FjdG9yX2lkcxgDIAMoCVIRY2FuZGlkYXRlQWN0b3JJZHMSPQobY2FuZGlk",
            "YXRlX3Rvb2xfaW5zdGFuY2VfaWRzGAQgAygJUhhjYW5kaWRhdGVUb29sSW5z",
            "dGFuY2VJZHMSQwoeY2FuZGlkYXRlX2ZpeHR1cmVfaW5zdGFuY2VfaWRzGAUg",
            "AygJUhtjYW5kaWRhdGVGaXh0dXJlSW5zdGFuY2VJZHMSPwocY2FuZGlkYXRl",
            "X2Fzc2V0X2luc3RhbmNlX2lkcxgGIAMoCVIZY2FuZGlkYXRlQXNzZXRJbnN0",
            "YW5jZUlkcxI0CgZpc3N1ZXMYByADKAsyHC5hc3NlbWJseS52MS5Qcm9jZXNz",
            "UnVuSXNzdWVSBmlzc3VlcyKcAwoYUHJvY2Vzc1J1blByZWNoZWNrUmVzdWx0",
            "Eg4KAm9rGAEgASgIUgJvaxI0CgZpc3N1ZXMYAiADKAsyHC5hc3NlbWJseS52",
            "MS5Qcm9jZXNzUnVuSXNzdWVSBmlzc3VlcxIwChRibG9ja2luZ19pc3N1ZV9j",
            "b3VudBgDIAEoBVISYmxvY2tpbmdJc3N1ZUNvdW50Ei4KE3dhcm5pbmdfaXNz",
            "dWVfY291bnQYBCABKAVSEXdhcm5pbmdJc3N1ZUNvdW50EioKEXByb2Nlc3Nf",
            "cmVjaXBlX2lkGAUgASgJUg9wcm9jZXNzUmVjaXBlSWQSJAoOdGFyZ2V0X2xp",
            "bmVfaWQYBiABKAlSDHRhcmdldExpbmVJZBJHChB0YXNrX2ZlYXNpYmlsaXR5",
            "GAcgAygLMhwuYXNzZW1ibHkudjEuVGFza0ZlYXNpYmlsaXR5Ug90YXNrRmVh",
            "c2liaWxpdHkSPQoGc3RhdHVzGAggASgOMiUuYXNzZW1ibHkudjEuUHJvY2Vz",
            "c1J1blByZWNoZWNrU3RhdHVzUgZzdGF0dXMiyAEKEVByb2Nlc3NMb2FkUmVz",
            "dWx0EjYKBnN0YXR1cxgBIAEoDjIeLmFzc2VtYmx5LnYxLlByb2Nlc3NMb2Fk",
            "U3RhdHVzUgZzdGF0dXMSQQoIcHJlY2hlY2sYAiABKAsyJS5hc3NlbWJseS52",
            "MS5Qcm9jZXNzUnVuUHJlY2hlY2tSZXN1bHRSCHByZWNoZWNrEjgKC3Byb2Nl",
            "c3NfcnVuGAMgASgLMhcuYXNzZW1ibHkudjEuUHJvY2Vzc1J1blIKcHJvY2Vz",
            "c1J1biqpBwoSUHJvY2Vzc0xvYWRGYWlsdXJlEiQKIFBST0NFU1NfTE9BRF9G",
            "QUlMVVJFX1VOU1BFQ0lGSUVEEAASJwojUFJPQ0VTU19MT0FEX0ZBSUxVUkVf",
            "TElORV9OT1RfRk9VTkQQARIxCi1QUk9DRVNTX0xPQURfRkFJTFVSRV9QUk9D",
            "RVNTX1JFQ0lQRV9OT1RfRk9VTkQQAhIuCipQUk9DRVNTX0xPQURfRkFJTFVS",
            "RV9QUk9EVUNUX05PVF9TVVBQT1JURUQQAxIvCitQUk9DRVNTX0xPQURfRkFJ",
            "TFVSRV9SRVNPVVJDRV9TVEFURV9VTktOT1dOEAQSLgoqUFJPQ0VTU19MT0FE",
            "X0ZBSUxVUkVfTk9fQ09NUEFUSUJMRV9GSVhUVVJFEAoSKgomUFJPQ0VTU19M",
            "T0FEX0ZBSUxVUkVfTUlTU0lOR19UT09MX1JPTEUQFBIsCihQUk9DRVNTX0xP",
            "QURfRkFJTFVSRV9UT09MX05PVF9DQUxJQlJBVEVEEBUSNQoxUFJPQ0VTU19M",
            "T0FEX0ZBSUxVUkVfVE9PTF9DQVBBQklMSVRZX0lOU1VGRklDSUVOVBAWEioK",
            "JlBST0NFU1NfTE9BRF9GQUlMVVJFX1JPQk9UX1VOQVZBSUxBQkxFEB4SLwor",
            "UFJPQ0VTU19MT0FEX0ZBSUxVUkVfUk9CT1RfVE9PTElOR19NSVNNQVRDSBAf",
            "Ei4KKlBST0NFU1NfTE9BRF9GQUlMVVJFX05PX1FVQUxJRklFRF9PUEVSQVRP",
            "UhAoEi8KK1BST0NFU1NfTE9BRF9GQUlMVVJFX1JFUVVJUkVEX1NLSUxMX0VY",
            "UElSRUQQKRIqCiZQUk9DRVNTX0xPQURfRkFJTFVSRV9OT19GRUFTSUJMRV9B",
            "Q1RPUhAqEjcKM1BST0NFU1NfTE9BRF9GQUlMVVJFX0NPTExBQk9SQVRJT05f",
            "TU9ERV9VTlNVUFBPUlRFRBAyEi0KKVBST0NFU1NfTE9BRF9GQUlMVVJFX1NB",
            "RkVUWV9NT0RFX01JU01BVENIEDMSMQotUFJPQ0VTU19MT0FEX0ZBSUxVUkVf",
            "VklTSU9OX0FTU0VUX1VOQVZBSUxBQkxFEDwSMgouUFJPQ0VTU19MT0FEX0ZB",
            "SUxVUkVfVkFMSURBVElPTl9TT1VSQ0VfTUlTU0lORxA9EjYKMlBST0NFU1Nf",
            "TE9BRF9GQUlMVVJFX05PX0ZFQVNJQkxFX1ZBTElEQVRJT05fTUVUSE9EED4q",
            "lgEKF1Byb2Nlc3NSdW5Jc3N1ZVNldmVyaXR5EioKJlBST0NFU1NfUlVOX0lT",
            "U1VFX1NFVkVSSVRZX1VOU1BFQ0lGSUVEEAASJwojUFJPQ0VTU19SVU5fSVNT",
            "VUVfU0VWRVJJVFlfQkxPQ0tJTkcQARImCiJQUk9DRVNTX1JVTl9JU1NVRV9T",
            "RVZFUklUWV9XQVJOSU5HEAIqigEKFVJlcXVpcmVtZW50SW1wb3J0YW5jZRIm",
            "CiJSRVFVSVJFTUVOVF9JTVBPUlRBTkNFX1VOU1BFQ0lGSUVEEAASIwofUkVR",
            "VUlSRU1FTlRfSU1QT1JUQU5DRV9SRVFVSVJFRBABEiQKIFJFUVVJUkVNRU5U",
            "X0lNUE9SVEFOQ0VfUFJFRkVSUkVEEAIqxgEKGFByb2Nlc3NSdW5QcmVjaGVj",
            "a1N0YXR1cxIrCidQUk9DRVNTX1JVTl9QUkVDSEVDS19TVEFUVVNfVU5TUEVD",
            "SUZJRUQQABIiCh5QUk9DRVNTX1JVTl9QUkVDSEVDS19TVEFUVVNfT0sQARIw",
            "CixQUk9DRVNTX1JVTl9QUkVDSEVDS19TVEFUVVNfT0tfV0lUSF9XQVJOSU5H",
            "UxACEicKI1BST0NFU1NfUlVOX1BSRUNIRUNLX1NUQVRVU19CTE9DS0VEEAMq",
            "oAEKEVByb2Nlc3NMb2FkU3RhdHVzEiMKH1BST0NFU1NfTE9BRF9TVEFUVVNf",
            "VU5TUEVDSUZJRUQQABInCiNQUk9DRVNTX0xPQURfU1RBVFVTX1BSRUNIRUNL",
            "X0ZBSUxFRBABEh0KGVBST0NFU1NfTE9BRF9TVEFUVVNfUkVBRFkQAhIeChpQ",
            "Uk9DRVNTX0xPQURfU1RBVFVTX0xPQURFRBADQroBCg9jb20uYXNzZW1ibHku",
            "djFCFFByb2Nlc3NSZXF1ZXN0c1Byb3RvUAFaO2dpdGh1Yi5jb20vY29ib3Rh",
            "ci9wcm90b2NvbC9tZXNzYWdlcy9hc3NlbWJseS92MTthc3NlbWJseXYxogID",
            "QVhYqgIUTWVzc2FnZXMuQXNzZW1ibHkuVjHKAgtBc3NlbWJseVxWMeICF0Fz",
            "c2VtYmx5XFYxXEdQQk1ldGFkYXRh6gIMQXNzZW1ibHk6OlYxYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Messages.Assembly.V1.ExecutionReflection.Descriptor, global::Messages.Assembly.V1.VariantReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Messages.Assembly.V1.ProcessLoadFailure), typeof(global::Messages.Assembly.V1.ProcessRunIssueSeverity), typeof(global::Messages.Assembly.V1.RequirementImportance), typeof(global::Messages.Assembly.V1.ProcessRunPrecheckStatus), typeof(global::Messages.Assembly.V1.ProcessLoadStatus), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Messages.Assembly.V1.ProcessLoadRequest), global::Messages.Assembly.V1.ProcessLoadRequest.Parser, new[]{ "ProcessRecipeId", "TargetLineId", "VariantConfiguration", "DryRun" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Messages.Assembly.V1.ProcessRunIssue), global::Messages.Assembly.V1.ProcessRunIssue.Parser, new[]{ "Failure", "Message", "Severity", "ProcessRecipeId", "SequenceDefinitionId", "TaskDefinitionId", "RequiredToolRole", "RequiredSkillId", "FixtureDefinitionId", "StationId", "ActorId", "ResourceId", "Remediation", "Importance" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Messages.Assembly.V1.TaskFeasibility), global::Messages.Assembly.V1.TaskFeasibility.Parser, new[]{ "TaskDefinitionId", "Feasible", "CandidateActorIds", "CandidateToolInstanceIds", "CandidateFixtureInstanceIds", "CandidateAssetInstanceIds", "Issues" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Messages.Assembly.V1.ProcessRunPrecheckResult), global::Messages.Assembly.V1.ProcessRunPrecheckResult.Parser, new[]{ "Ok", "Issues", "BlockingIssueCount", "WarningIssueCount", "ProcessRecipeId", "TargetLineId", "TaskFeasibility", "Status" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Messages.Assembly.V1.ProcessLoadResult), global::Messages.Assembly.V1.ProcessLoadResult.Parser, new[]{ "Status", "Precheck", "ProcessRun" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum ProcessLoadFailure {
    [pbr::OriginalName("PROCESS_LOAD_FAILURE_UNSPECIFIED")] Unspecified = 0,
    /// <summary>
    /// General failures
    /// </summary>
    [pbr::OriginalName("PROCESS_LOAD_FAILURE_LINE_NOT_FOUND")] LineNotFound = 1,
    [pbr::OriginalName("PROCESS_LOAD_FAILURE_PROCESS_RECIPE_NOT_FOUND")] ProcessRecipeNotFound = 2,
    [pbr::OriginalName("PROCESS_LOAD_FAILURE_PRODUCT_NOT_SUPPORTED")] ProductNotSupported = 3,
    [pbr::OriginalName("PROCESS_LOAD_FAILURE_RESOURCE_STATE_UNKNOWN")] ResourceStateUnknown = 4,
    /// <summary>
    /// Fixture related failures
    /// </summary>
    [pbr::OriginalName("PROCESS_LOAD_FAILURE_NO_COMPATIBLE_FIXTURE")] NoCompatibleFixture = 10,
    /// <summary>
    /// Tool related failures
    /// </summary>
    [pbr::OriginalName("PROCESS_LOAD_FAILURE_MISSING_TOOL_ROLE")] MissingToolRole = 20,
    [pbr::OriginalName("PROCESS_LOAD_FAILURE_TOOL_NOT_CALIBRATED")] ToolNotCalibrated = 21,
    [pbr::OriginalName("PROCESS_LOAD_FAILURE_TOOL_CAPABILITY_INSUFFICIENT")] ToolCapabilityInsufficient = 22,
    /// <summary>
    /// Robot related failures
    /// </summary>
    [pbr::OriginalName("PROCESS_LOAD_FAILURE_ROBOT_UNAVAILABLE")] RobotUnavailable = 30,
    [pbr::OriginalName("PROCESS_LOAD_FAILURE_ROBOT_TOOLING_MISMATCH")] RobotToolingMismatch = 31,
    /// <summary>
    /// Agent/operator related failueres
    /// </summary>
    [pbr::OriginalName("PROCESS_LOAD_FAILURE_NO_QUALIFIED_OPERATOR")] NoQualifiedOperator = 40,
    [pbr::OriginalName("PROCESS_LOAD_FAILURE_REQUIRED_SKILL_EXPIRED")] RequiredSkillExpired = 41,
    [pbr::OriginalName("PROCESS_LOAD_FAILURE_NO_FEASIBLE_ACTOR")] NoFeasibleActor = 42,
    /// <summary>
    /// Safety / collaboration related failures
    /// </summary>
    [pbr::OriginalName("PROCESS_LOAD_FAILURE_COLLABORATION_MODE_UNSUPPORTED")] CollaborationModeUnsupported = 50,
    [pbr::OriginalName("PROCESS_LOAD_FAILURE_SAFETY_MODE_MISMATCH")] SafetyModeMismatch = 51,
    /// <summary>
    /// Validation related failures
    /// </summary>
    [pbr::OriginalName("PROCESS_LOAD_FAILURE_VISION_ASSET_UNAVAILABLE")] VisionAssetUnavailable = 60,
    [pbr::OriginalName("PROCESS_LOAD_FAILURE_VALIDATION_SOURCE_MISSING")] ValidationSourceMissing = 61,
    [pbr::OriginalName("PROCESS_LOAD_FAILURE_NO_FEASIBLE_VALIDATION_METHOD")] NoFeasibleValidationMethod = 62,
  }

  public enum ProcessRunIssueSeverity {
    [pbr::OriginalName("PROCESS_RUN_ISSUE_SEVERITY_UNSPECIFIED")] Unspecified = 0,
    /// <summary>
    /// Run cannot start. Some reasons: no compatible fixture, required tool missing, robot required but unavailable, safety mode incompatible, no feasible actor for only-human/only-robot task
    /// </summary>
    [pbr::OriginalName("PROCESS_RUN_ISSUE_SEVERITY_BLOCKING")] Blocking = 1,
    /// <summary>
    /// Run may start, but quality/performance may suffer. Examples: preferred robot unavailable (but human can do task), calibration expires soon, only one qualified actor available, vision unavailable but manual confirmation allowed.
    /// </summary>
    [pbr::OriginalName("PROCESS_RUN_ISSUE_SEVERITY_WARNING")] Warning = 2,
  }

  public enum RequirementImportance {
    [pbr::OriginalName("REQUIREMENT_IMPORTANCE_UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("REQUIREMENT_IMPORTANCE_REQUIRED")] Required = 1,
    [pbr::OriginalName("REQUIREMENT_IMPORTANCE_PREFERRED")] Preferred = 2,
  }

  public enum ProcessRunPrecheckStatus {
    [pbr::OriginalName("PROCESS_RUN_PRECHECK_STATUS_UNSPECIFIED")] Unspecified = 0,
    /// <summary>
    /// Neither warning nor blocking issues
    /// </summary>
    [pbr::OriginalName("PROCESS_RUN_PRECHECK_STATUS_OK")] Ok = 1,
    /// <summary>
    /// One or more warning issues, but no blocking
    /// </summary>
    [pbr::OriginalName("PROCESS_RUN_PRECHECK_STATUS_OK_WITH_WARNINGS")] OkWithWarnings = 2,
    /// <summary>
    /// One or more blocking issues
    /// </summary>
    [pbr::OriginalName("PROCESS_RUN_PRECHECK_STATUS_BLOCKED")] Blocked = 3,
  }

  public enum ProcessLoadStatus {
    [pbr::OriginalName("PROCESS_LOAD_STATUS_UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("PROCESS_LOAD_STATUS_PRECHECK_FAILED")] PrecheckFailed = 1,
    /// <summary>
    /// feasible, but not instantiated (dry run)
    /// </summary>
    [pbr::OriginalName("PROCESS_LOAD_STATUS_READY")] Ready = 2,
    /// <summary>
    /// feasible and instantiated
    /// </summary>
    [pbr::OriginalName("PROCESS_LOAD_STATUS_LOADED")] Loaded = 3,
  }

  #endregion

  #region Messages
  /// <summary>
  /// ProcessLoadRequest is used to go from ProcessRecipe -> ProcessRun
  /// During this process, resources feasibility should be checked, i.e.
  ///    "Can this recipe be instantiated now, on this station/cell/line, with the currently available resources?"
  ///
  /// Thus the following must be evaluated:
  /// - available robots (if any task requires or strongly prefers a robot, can that be satisfied?)
  /// - available workers (if tasks requires only-human or need certain skills, can that be satisfied? Either check immediately or defer until operator is assigned. Perhaps assigned based on skills and availability? Check that: assigned worker exist, worker enabled, required skills present and valid)
  /// - available tool instances (all ToolRequirements from all tasks, available ToolInstances is station/cell, tool status, calibration validity, required properties, minimum capability profile)
  /// - valid calibration
  /// - fixture availability/feasibility (recipe supported fixtures, available fixture instances, fixture status, product/recipe compatibility)
  /// - safety mode / collaboration mode (check: recipe task collaboration modes, station/cell safety mode, whether simultaneous HRC is allowed, whether human-only or robot-only is possible right now)
  /// - active faults / disabled resources
  /// - asset / inspection feasibility (if validation required: vision, torque feedback, external QC, sensors --> then verify those assets exist and are available.)
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ProcessLoadRequest : pb::IMessage<ProcessLoadRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ProcessLoadRequest> _parser = new pb::MessageParser<ProcessLoadRequest>(() => new ProcessLoadRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ProcessLoadRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Messages.Assembly.V1.ProcessRequestsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProcessLoadRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProcessLoadRequest(ProcessLoadRequest other) : this() {
      processRecipeId_ = other.processRecipeId_;
      targetLineId_ = other.targetLineId_;
      variantConfiguration_ = other.variantConfiguration_ != null ? other.variantConfiguration_.Clone() : null;
      dryRun_ = other.dryRun_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProcessLoadRequest Clone() {
      return new ProcessLoadRequest(this);
    }

    /// <summary>Field number for the "process_recipe_id" field.</summary>
    public const int ProcessRecipeIdFieldNumber = 1;
    private string processRecipeId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ProcessRecipeId {
      get { return processRecipeId_; }
      set {
        processRecipeId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "target_line_id" field.</summary>
    public const int TargetLineIdFieldNumber = 2;
    private string targetLineId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TargetLineId {
      get { return targetLineId_; }
      set {
        targetLineId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "variant_configuration" field.</summary>
    public const int VariantConfigurationFieldNumber = 3;
    private global::Messages.Assembly.V1.VariantConfiguration variantConfiguration_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Messages.Assembly.V1.VariantConfiguration VariantConfiguration {
      get { return variantConfiguration_; }
      set {
        variantConfiguration_ = value;
      }
    }

    /// <summary>Field number for the "dry_run" field.</summary>
    public const int DryRunFieldNumber = 4;
    private bool dryRun_;
    /// <summary>
    /// true = precheck only, false = precheck + instantiate
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool DryRun {
      get { return dryRun_; }
      set {
        dryRun_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ProcessLoadRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ProcessLoadRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ProcessRecipeId != other.ProcessRecipeId) return false;
      if (TargetLineId != other.TargetLineId) return false;
      if (!object.Equals(VariantConfiguration, other.VariantConfiguration)) return false;
      if (DryRun != other.DryRun) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ProcessRecipeId.Length != 0) hash ^= ProcessRecipeId.GetHashCode();
      if (TargetLineId.Length != 0) hash ^= TargetLineId.GetHashCode();
      if (variantConfiguration_ != null) hash ^= VariantConfiguration.GetHashCode();
      if (DryRun != false) hash ^= DryRun.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ProcessRecipeId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ProcessRecipeId);
      }
      if (TargetLineId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(TargetLineId);
      }
      if (variantConfiguration_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(VariantConfiguration);
      }
      if (DryRun != false) {
        output.WriteRawTag(32);
        output.WriteBool(DryRun);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ProcessRecipeId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ProcessRecipeId);
      }
      if (TargetLineId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(TargetLineId);
      }
      if (variantConfiguration_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(VariantConfiguration);
      }
      if (DryRun != false) {
        output.WriteRawTag(32);
        output.WriteBool(DryRun);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ProcessRecipeId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ProcessRecipeId);
      }
      if (TargetLineId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TargetLineId);
      }
      if (variantConfiguration_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(VariantConfiguration);
      }
      if (DryRun != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ProcessLoadRequest other) {
      if (other == null) {
        return;
      }
      if (other.ProcessRecipeId.Length != 0) {
        ProcessRecipeId = other.ProcessRecipeId;
      }
      if (other.TargetLineId.Length != 0) {
        TargetLineId = other.TargetLineId;
      }
      if (other.variantConfiguration_ != null) {
        if (variantConfiguration_ == null) {
          VariantConfiguration = new global::Messages.Assembly.V1.VariantConfiguration();
        }
        VariantConfiguration.MergeFrom(other.VariantConfiguration);
      }
      if (other.DryRun != false) {
        DryRun = other.DryRun;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ProcessRecipeId = input.ReadString();
            break;
          }
          case 18: {
            TargetLineId = input.ReadString();
            break;
          }
          case 26: {
            if (variantConfiguration_ == null) {
              VariantConfiguration = new global::Messages.Assembly.V1.VariantConfiguration();
            }
            input.ReadMessage(VariantConfiguration);
            break;
          }
          case 32: {
            DryRun = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ProcessRecipeId = input.ReadString();
            break;
          }
          case 18: {
            TargetLineId = input.ReadString();
            break;
          }
          case 26: {
            if (variantConfiguration_ == null) {
              VariantConfiguration = new global::Messages.Assembly.V1.VariantConfiguration();
            }
            input.ReadMessage(VariantConfiguration);
            break;
          }
          case 32: {
            DryRun = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ProcessRunIssue : pb::IMessage<ProcessRunIssue>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ProcessRunIssue> _parser = new pb::MessageParser<ProcessRunIssue>(() => new ProcessRunIssue());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ProcessRunIssue> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Messages.Assembly.V1.ProcessRequestsReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProcessRunIssue() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProcessRunIssue(ProcessRunIssue other) : this() {
      failure_ = other.failure_;
      message_ = other.message_;
      severity_ = other.severity_;
      processRecipeId_ = other.processRecipeId_;
      sequenceDefinitionId_ = other.sequenceDefinitionId_;
      taskDefinitionId_ = other.taskDefinitionId_;
      requiredToolRole_ = other.requiredToolRole_;
      requiredSkillId_ = other.requiredSkillId_;
      fixtureDefinitionId_ = other.fixtureDefinitionId_;
      stationId_ = other.stationId_;
      actorId_ = other.actorId_;
      resourceId_ = other.resourceId_;
      remediation_ = other.remediation_;
      importance_ = other.importance_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProcessRunIssue Clone() {
      return new ProcessRunIssue(this);
    }

    /// <summary>Field number for the "failure" field.</summary>
    public const int FailureFieldNumber = 1;
    private global::Messages.Assembly.V1.ProcessLoadFailure failure_ = global::Messages.Assembly.V1.ProcessLoadFailure.Unspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Messages.Assembly.V1.ProcessLoadFailure Failure {
      get { return failure_; }
      set {
        failure_ = value;
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 2;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "severity" field.</summary>
    public const int SeverityFieldNumber = 3;
    private global::Messages.Assembly.V1.ProcessRunIssueSeverity severity_ = global::Messages.Assembly.V1.ProcessRunIssueSeverity.Unspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Messages.Assembly.V1.ProcessRunIssueSeverity Severity {
      get { return severity_; }
      set {
        severity_ = value;
      }
    }

    /// <summary>Field number for the "process_recipe_id" field.</summary>
    public const int ProcessRecipeIdFieldNumber = 4;
    private string processRecipeId_ = "";
    /// <summary>
    /// Scope
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ProcessRecipeId {
      get { return processRecipeId_; }
      set {
        processRecipeId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "sequence_definition_id" field.</summary>
    public const int SequenceDefinitionIdFieldNumber = 5;
    private string sequenceDefinitionId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SequenceDefinitionId {
      get { return sequenceDefinitionId_; }
      set {
        sequenceDefinitionId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "task_definition_id" field.</summary>
    public const int TaskDefinitionIdFieldNumber = 6;
    private string taskDefinitionId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TaskDefinitionId {
      get { return taskDefinitionId_; }
      set {
        taskDefinitionId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "required_tool_role" field.</summary>
    public const int RequiredToolRoleFieldNumber = 7;
    private string requiredToolRole_ = "";
    /// <summary>
    /// Related requirement/resource
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string RequiredToolRole {
      get { return requiredToolRole_; }
      set {
        requiredToolRole_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "required_skill_id" field.</summary>
    public const int RequiredSkillIdFieldNumber = 8;
    private string requiredSkillId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string RequiredSkillId {
      get { return requiredSkillId_; }
      set {
        requiredSkillId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "fixture_definition_id" field.</summary>
    public const int FixtureDefinitionIdFieldNumber = 9;
    private string fixtureDefinitionId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FixtureDefinitionId {
      get { return fixtureDefinitionId_; }
      set {
        fixtureDefinitionId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "station_id" field.</summary>
    public const int StationIdFieldNumber = 10;
    private string stationId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string StationId {
      get { return stationId_; }
      set {
        stationId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "actor_id" field.</summary>
    public const int ActorIdFieldNumber = 11;
    private string actorId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ActorId {
      get { return actorId_; }
      set {
        actorId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "resource_id" field.</summary>
    public const int ResourceIdFieldNumber = 12;
    private string resourceId_ = "";
    /// <summary>
    /// tool/robot/fixture/asset instance if known
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ResourceId {
      get { return resourceId_; }
      set {
        resourceId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "remediation" field.</summary>
    public const int RemediationFieldNumber = 13;
    private string remediation_ = "";
    /// <summary>
    /// Optional remediation hint
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Remediation {
      get { return remediation_; }
      set {
        remediation_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "importance" field.</summary>
    public const int ImportanceFieldNumber = 14;
    private global::Messages.Assembly.V1.RequirementImportance importance_ = global::Messages.Assembly.V1.RequirementImportance.Unspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Messages.Assembly.V1.RequirementImportance Importance {
      get { return importance_; }
      set {
        importance_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ProcessRunIssue);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ProcessRunIssue other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Failure != other.Failure) return false;
      if (Message != other.Message) return false;
      if (Severity != other.Severity) return false;
      if (ProcessRecipeId != other.ProcessRecipeId) return false;
      if (SequenceDefinitionId != other.SequenceDefinitionId) return false;
      if (TaskDefinitionId != other.TaskDefinitionId) return false;
      if (RequiredToolRole != other.RequiredToolRole) return false;
      if (RequiredSkillId != other.RequiredSkillId) return false;
      if (FixtureDefinitionId != other.FixtureDefinitionId) return false;
      if (StationId != other.StationId) return false;
      if (ActorId != other.ActorId) return false;
      if (ResourceId != other.ResourceId) return false;
      if (Remediation != other.Remediation) return false;
      if (Importance != other.Importance) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Failure != global::Messages.Assembly.V1.ProcessLoadFailure.Unspecified) hash ^= Failure.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (Severity != global::Messages.Assembly.V1.ProcessRunIssueSeverity.Unspecified) hash ^= Severity.GetHashCode();
      if (ProcessRecipeId.Length != 0) hash ^= ProcessRecipeId.GetHashCode();
      if (SequenceDefinitionId.Length != 0) hash ^= SequenceDefinitionId.GetHashCode();
      if (TaskDefinitionId.Length != 0) hash ^= TaskDefinitionId.GetHashCode();
      if (RequiredToolRole.Length != 0) hash ^= RequiredToolRole.GetHashCode();
      if (RequiredSkillId.Length != 0) hash ^= RequiredSkillId.GetHashCode();
      if (FixtureDefinitionId.Length != 0) hash ^= FixtureDefinitionId.GetHashCode();
      if (StationId.Length != 0) hash ^= StationId.GetHashCode();
      if (ActorId.Length != 0) hash ^= ActorId.GetHashCode();
      if (ResourceId.Length != 0) hash ^= ResourceId.GetHashCode();
      if (Remediation.Length != 0) hash ^= Remediation.GetHashCode();
      if (Importance != global::Messages.Assembly.V1.RequirementImportance.Unspecified) hash ^= Importance.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Failure != global::Messages.Assembly.V1.ProcessLoadFailure.Unspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Failure);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Message);
      }
      if (Severity != global::Messages.Assembly.V1.ProcessRunIssueSeverity.Unspecified) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Severity);
      }
      if (ProcessRecipeId.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(ProcessRecipeId);
      }
      if (SequenceDefinitionId.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(SequenceDefinitionId);
      }
      if (TaskDefinitionId.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(TaskDefinitionId);
      }
      if (RequiredToolRole.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(RequiredToolRole);
      }
      if (RequiredSkillId.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(RequiredSkillId);
      }
      if (FixtureDefinitionId.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(FixtureDefinitionId);
      }
      if (StationId.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(StationId);
      }
      if (ActorId.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(ActorId);
      }
      if (ResourceId.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(ResourceId);
      }
      if (Remediation.Length != 0) {
        output.WriteRawTag(106);
        output.WriteString(Remediation);
      }
      if (Importance != global::Messages.Assembly.V1.RequirementImportance.Unspecified) {
        output.WriteRawTag(112);
        output.WriteEnum((int) Importance);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Failure != global::Messages.Assembly.V1.ProcessLoadFailure.Unspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Failure);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Message);
      }
      if (Severity != global::Messages.Assembly.V1.ProcessRunIssueSeverity.Unspecified) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Severity);
      }
      if (ProcessRecipeId.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(ProcessRecipeId);
      }
      if (SequenceDefinitionId.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(SequenceDefinitionId);
      }
      if (TaskDefinitionId.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(TaskDefinitionId);
      }
      if (RequiredToolRole.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(RequiredToolRole);
      }
      if (RequiredSkillId.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(RequiredSkillId);
      }
      if (FixtureDefinitionId.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(FixtureDefinitionId);
      }
      if (StationId.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(StationId);
      }
      if (ActorId.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(ActorId);
      }
      if (ResourceId.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(ResourceId);
      }
      if (Remediation.Length != 0) {
        output.WriteRawTag(106);
        output.WriteString(Remediation);
      }
      if (Importance != global::Messages.Assembly.V1.RequirementImportance.Unspecified) {
        output.WriteRawTag(112);
        output.WriteEnum((int) Importance);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Failure != global::Messages.Assembly.V1.ProcessLoadFailure.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Failure);
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (Severity != global::Messages.Assembly.V1.ProcessRunIssueSeverity.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Severity);
      }
      if (ProcessRecipeId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ProcessRecipeId);
      }
      if (SequenceDefinitionId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SequenceDefinitionId);
      }
      if (TaskDefinitionId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TaskDefinitionId);
      }
      if (RequiredToolRole.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RequiredToolRole);
      }
      if (RequiredSkillId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RequiredSkillId);
      }
      if (FixtureDefinitionId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FixtureDefinitionId);
      }
      if (StationId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StationId);
      }
      if (ActorId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ActorId);
      }
      if (ResourceId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ResourceId);
      }
      if (Remediation.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Remediation);
      }
      if (Importance != global::Messages.Assembly.V1.RequirementImportance.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Importance);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ProcessRunIssue other) {
      if (other == null) {
        return;
      }
      if (other.Failure != global::Messages.Assembly.V1.ProcessLoadFailure.Unspecified) {
        Failure = other.Failure;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      if (other.Severity != global::Messages.Assembly.V1.ProcessRunIssueSeverity.Unspecified) {
        Severity = other.Severity;
      }
      if (other.ProcessRecipeId.Length != 0) {
        ProcessRecipeId = other.ProcessRecipeId;
      }
      if (other.SequenceDefinitionId.Length != 0) {
        SequenceDefinitionId = other.SequenceDefinitionId;
      }
      if (other.TaskDefinitionId.Length != 0) {
        TaskDefinitionId = other.TaskDefinitionId;
      }
      if (other.RequiredToolRole.Length != 0) {
        RequiredToolRole = other.RequiredToolRole;
      }
      if (other.RequiredSkillId.Length != 0) {
        RequiredSkillId = other.RequiredSkillId;
      }
      if (other.FixtureDefinitionId.Length != 0) {
        FixtureDefinitionId = other.FixtureDefinitionId;
      }
      if (other.StationId.Length != 0) {
        StationId = other.StationId;
      }
      if (other.ActorId.Length != 0) {
        ActorId = other.ActorId;
      }
      if (other.ResourceId.Length != 0) {
        ResourceId = other.ResourceId;
      }
      if (other.Remediation.Length != 0) {
        Remediation = other.Remediation;
      }
      if (other.Importance != global::Messages.Assembly.V1.RequirementImportance.Unspecified) {
        Importance = other.Importance;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Failure = (global::Messages.Assembly.V1.ProcessLoadFailure) input.ReadEnum();
            break;
          }
          case 18: {
            Message = input.ReadString();
            break;
          }
          case 24: {
            Severity = (global::Messages.Assembly.V1.ProcessRunIssueSeverity) input.ReadEnum();
            break;
          }
          case 34: {
            ProcessRecipeId = input.ReadString();
            break;
          }
          case 42: {
            SequenceDefinitionId = input.ReadString();
            break;
          }
          case 50: {
            TaskDefinitionId = input.ReadString();
            break;
          }
          case 58: {
            RequiredToolRole = input.ReadString();
            break;
          }
          case 66: {
            RequiredSkillId = input.ReadString();
            break;
          }
          case 74: {
            FixtureDefinitionId = input.ReadString();
            break;
          }
          case 82: {
            StationId = input.ReadString();
            break;
          }
          case 90: {
            ActorId = input.ReadString();
            break;
          }
          case 98: {
            ResourceId = input.ReadString();
            break;
          }
          case 106: {
            Remediation = input.ReadString();
            break;
          }
          case 112: {
            Importance = (global::Messages.Assembly.V1.RequirementImportance) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Failure = (global::Messages.Assembly.V1.ProcessLoadFailure) input.ReadEnum();
            break;
          }
          case 18: {
            Message = input.ReadString();
            break;
          }
          case 24: {
            Severity = (global::Messages.Assembly.V1.ProcessRunIssueSeverity) input.ReadEnum();
            break;
          }
          case 34: {
            ProcessRecipeId = input.ReadString();
            break;
          }
          case 42: {
            SequenceDefinitionId = input.ReadString();
            break;
          }
          case 50: {
            TaskDefinitionId = input.ReadString();
            break;
          }
          case 58: {
            RequiredToolRole = input.ReadString();
            break;
          }
          case 66: {
            RequiredSkillId = input.ReadString();
            break;
          }
          case 74: {
            FixtureDefinitionId = input.ReadString();
            break;
          }
          case 82: {
            StationId = input.ReadString();
            break;
          }
          case 90: {
            ActorId = input.ReadString();
            break;
          }
          case 98: {
            ResourceId = input.ReadString();
            break;
          }
          case 106: {
            Remediation = input.ReadString();
            break;
          }
          case 112: {
            Importance = (global::Messages.Assembly.V1.RequirementImportance) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class TaskFeasibility : pb::IMessage<TaskFeasibility>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TaskFeasibility> _parser = new pb::MessageParser<TaskFeasibility>(() => new TaskFeasibility());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TaskFeasibility> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Messages.Assembly.V1.ProcessRequestsReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TaskFeasibility() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TaskFeasibility(TaskFeasibility other) : this() {
      taskDefinitionId_ = other.taskDefinitionId_;
      feasible_ = other.feasible_;
      candidateActorIds_ = other.candidateActorIds_.Clone();
      candidateToolInstanceIds_ = other.candidateToolInstanceIds_.Clone();
      candidateFixtureInstanceIds_ = other.candidateFixtureInstanceIds_.Clone();
      candidateAssetInstanceIds_ = other.candidateAssetInstanceIds_.Clone();
      issues_ = other.issues_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TaskFeasibility Clone() {
      return new TaskFeasibility(this);
    }

    /// <summary>Field number for the "task_definition_id" field.</summary>
    public const int TaskDefinitionIdFieldNumber = 1;
    private string taskDefinitionId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TaskDefinitionId {
      get { return taskDefinitionId_; }
      set {
        taskDefinitionId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "feasible" field.</summary>
    public const int FeasibleFieldNumber = 2;
    private bool feasible_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Feasible {
      get { return feasible_; }
      set {
        feasible_ = value;
      }
    }

    /// <summary>Field number for the "candidate_actor_ids" field.</summary>
    public const int CandidateActorIdsFieldNumber = 3;
    private static readonly pb::FieldCodec<string> _repeated_candidateActorIds_codec
        = pb::FieldCodec.ForString(26);
    private readonly pbc::RepeatedField<string> candidateActorIds_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> CandidateActorIds {
      get { return candidateActorIds_; }
    }

    /// <summary>Field number for the "candidate_tool_instance_ids" field.</summary>
    public const int CandidateToolInstanceIdsFieldNumber = 4;
    private static readonly pb::FieldCodec<string> _repeated_candidateToolInstanceIds_codec
        = pb::FieldCodec.ForString(34);
    private readonly pbc::RepeatedField<string> candidateToolInstanceIds_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> CandidateToolInstanceIds {
      get { return candidateToolInstanceIds_; }
    }

    /// <summary>Field number for the "candidate_fixture_instance_ids" field.</summary>
    public const int CandidateFixtureInstanceIdsFieldNumber = 5;
    private static readonly pb::FieldCodec<string> _repeated_candidateFixtureInstanceIds_codec
        = pb::FieldCodec.ForString(42);
    private readonly pbc::RepeatedField<string> candidateFixtureInstanceIds_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> CandidateFixtureInstanceIds {
      get { return candidateFixtureInstanceIds_; }
    }

    /// <summary>Field number for the "candidate_asset_instance_ids" field.</summary>
    public const int CandidateAssetInstanceIdsFieldNumber = 6;
    private static readonly pb::FieldCodec<string> _repeated_candidateAssetInstanceIds_codec
        = pb::FieldCodec.ForString(50);
    private readonly pbc::RepeatedField<string> candidateAssetInstanceIds_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> CandidateAssetInstanceIds {
      get { return candidateAssetInstanceIds_; }
    }

    /// <summary>Field number for the "issues" field.</summary>
    public const int IssuesFieldNumber = 7;
    private static readonly pb::FieldCodec<global::Messages.Assembly.V1.ProcessRunIssue> _repeated_issues_codec
        = pb::FieldCodec.ForMessage(58, global::Messages.Assembly.V1.ProcessRunIssue.Parser);
    private readonly pbc::RepeatedField<global::Messages.Assembly.V1.ProcessRunIssue> issues_ = new pbc::RepeatedField<global::Messages.Assembly.V1.ProcessRunIssue>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Messages.Assembly.V1.ProcessRunIssue> Issues {
      get { return issues_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TaskFeasibility);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TaskFeasibility other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TaskDefinitionId != other.TaskDefinitionId) return false;
      if (Feasible != other.Feasible) return false;
      if(!candidateActorIds_.Equals(other.candidateActorIds_)) return false;
      if(!candidateToolInstanceIds_.Equals(other.candidateToolInstanceIds_)) return false;
      if(!candidateFixtureInstanceIds_.Equals(other.candidateFixtureInstanceIds_)) return false;
      if(!candidateAssetInstanceIds_.Equals(other.candidateAssetInstanceIds_)) return false;
      if(!issues_.Equals(other.issues_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (TaskDefinitionId.Length != 0) hash ^= TaskDefinitionId.GetHashCode();
      if (Feasible != false) hash ^= Feasible.GetHashCode();
      hash ^= candidateActorIds_.GetHashCode();
      hash ^= candidateToolInstanceIds_.GetHashCode();
      hash ^= candidateFixtureInstanceIds_.GetHashCode();
      hash ^= candidateAssetInstanceIds_.GetHashCode();
      hash ^= issues_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (TaskDefinitionId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(TaskDefinitionId);
      }
      if (Feasible != false) {
        output.WriteRawTag(16);
        output.WriteBool(Feasible);
      }
      candidateActorIds_.WriteTo(output, _repeated_candidateActorIds_codec);
      candidateToolInstanceIds_.WriteTo(output, _repeated_candidateToolInstanceIds_codec);
      candidateFixtureInstanceIds_.WriteTo(output, _repeated_candidateFixtureInstanceIds_codec);
      candidateAssetInstanceIds_.WriteTo(output, _repeated_candidateAssetInstanceIds_codec);
      issues_.WriteTo(output, _repeated_issues_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (TaskDefinitionId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(TaskDefinitionId);
      }
      if (Feasible != false) {
        output.WriteRawTag(16);
        output.WriteBool(Feasible);
      }
      candidateActorIds_.WriteTo(ref output, _repeated_candidateActorIds_codec);
      candidateToolInstanceIds_.WriteTo(ref output, _repeated_candidateToolInstanceIds_codec);
      candidateFixtureInstanceIds_.WriteTo(ref output, _repeated_candidateFixtureInstanceIds_codec);
      candidateAssetInstanceIds_.WriteTo(ref output, _repeated_candidateAssetInstanceIds_codec);
      issues_.WriteTo(ref output, _repeated_issues_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (TaskDefinitionId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TaskDefinitionId);
      }
      if (Feasible != false) {
        size += 1 + 1;
      }
      size += candidateActorIds_.CalculateSize(_repeated_candidateActorIds_codec);
      size += candidateToolInstanceIds_.CalculateSize(_repeated_candidateToolInstanceIds_codec);
      size += candidateFixtureInstanceIds_.CalculateSize(_repeated_candidateFixtureInstanceIds_codec);
      size += candidateAssetInstanceIds_.CalculateSize(_repeated_candidateAssetInstanceIds_codec);
      size += issues_.CalculateSize(_repeated_issues_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TaskFeasibility other) {
      if (other == null) {
        return;
      }
      if (other.TaskDefinitionId.Length != 0) {
        TaskDefinitionId = other.TaskDefinitionId;
      }
      if (other.Feasible != false) {
        Feasible = other.Feasible;
      }
      candidateActorIds_.Add(other.candidateActorIds_);
      candidateToolInstanceIds_.Add(other.candidateToolInstanceIds_);
      candidateFixtureInstanceIds_.Add(other.candidateFixtureInstanceIds_);
      candidateAssetInstanceIds_.Add(other.candidateAssetInstanceIds_);
      issues_.Add(other.issues_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            TaskDefinitionId = input.ReadString();
            break;
          }
          case 16: {
            Feasible = input.ReadBool();
            break;
          }
          case 26: {
            candidateActorIds_.AddEntriesFrom(input, _repeated_candidateActorIds_codec);
            break;
          }
          case 34: {
            candidateToolInstanceIds_.AddEntriesFrom(input, _repeated_candidateToolInstanceIds_codec);
            break;
          }
          case 42: {
            candidateFixtureInstanceIds_.AddEntriesFrom(input, _repeated_candidateFixtureInstanceIds_codec);
            break;
          }
          case 50: {
            candidateAssetInstanceIds_.AddEntriesFrom(input, _repeated_candidateAssetInstanceIds_codec);
            break;
          }
          case 58: {
            issues_.AddEntriesFrom(input, _repeated_issues_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            TaskDefinitionId = input.ReadString();
            break;
          }
          case 16: {
            Feasible = input.ReadBool();
            break;
          }
          case 26: {
            candidateActorIds_.AddEntriesFrom(ref input, _repeated_candidateActorIds_codec);
            break;
          }
          case 34: {
            candidateToolInstanceIds_.AddEntriesFrom(ref input, _repeated_candidateToolInstanceIds_codec);
            break;
          }
          case 42: {
            candidateFixtureInstanceIds_.AddEntriesFrom(ref input, _repeated_candidateFixtureInstanceIds_codec);
            break;
          }
          case 50: {
            candidateAssetInstanceIds_.AddEntriesFrom(ref input, _repeated_candidateAssetInstanceIds_codec);
            break;
          }
          case 58: {
            issues_.AddEntriesFrom(ref input, _repeated_issues_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ProcessRunPrecheckResult : pb::IMessage<ProcessRunPrecheckResult>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ProcessRunPrecheckResult> _parser = new pb::MessageParser<ProcessRunPrecheckResult>(() => new ProcessRunPrecheckResult());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ProcessRunPrecheckResult> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Messages.Assembly.V1.ProcessRequestsReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProcessRunPrecheckResult() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProcessRunPrecheckResult(ProcessRunPrecheckResult other) : this() {
      ok_ = other.ok_;
      issues_ = other.issues_.Clone();
      blockingIssueCount_ = other.blockingIssueCount_;
      warningIssueCount_ = other.warningIssueCount_;
      processRecipeId_ = other.processRecipeId_;
      targetLineId_ = other.targetLineId_;
      taskFeasibility_ = other.taskFeasibility_.Clone();
      status_ = other.status_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProcessRunPrecheckResult Clone() {
      return new ProcessRunPrecheckResult(this);
    }

    /// <summary>Field number for the "ok" field.</summary>
    public const int OkFieldNumber = 1;
    private bool ok_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Ok {
      get { return ok_; }
      set {
        ok_ = value;
      }
    }

    /// <summary>Field number for the "issues" field.</summary>
    public const int IssuesFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Messages.Assembly.V1.ProcessRunIssue> _repeated_issues_codec
        = pb::FieldCodec.ForMessage(18, global::Messages.Assembly.V1.ProcessRunIssue.Parser);
    private readonly pbc::RepeatedField<global::Messages.Assembly.V1.ProcessRunIssue> issues_ = new pbc::RepeatedField<global::Messages.Assembly.V1.ProcessRunIssue>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Messages.Assembly.V1.ProcessRunIssue> Issues {
      get { return issues_; }
    }

    /// <summary>Field number for the "blocking_issue_count" field.</summary>
    public const int BlockingIssueCountFieldNumber = 3;
    private int blockingIssueCount_;
    /// <summary>
    /// Optional summary counts for UI / fast filtering
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int BlockingIssueCount {
      get { return blockingIssueCount_; }
      set {
        blockingIssueCount_ = value;
      }
    }

    /// <summary>Field number for the "warning_issue_count" field.</summary>
    public const int WarningIssueCountFieldNumber = 4;
    private int warningIssueCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int WarningIssueCount {
      get { return warningIssueCount_; }
      set {
        warningIssueCount_ = value;
      }
    }

    /// <summary>Field number for the "process_recipe_id" field.</summary>
    public const int ProcessRecipeIdFieldNumber = 5;
    private string processRecipeId_ = "";
    /// <summary>
    /// What was checked
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ProcessRecipeId {
      get { return processRecipeId_; }
      set {
        processRecipeId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "target_line_id" field.</summary>
    public const int TargetLineIdFieldNumber = 6;
    private string targetLineId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TargetLineId {
      get { return targetLineId_; }
      set {
        targetLineId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "task_feasibility" field.</summary>
    public const int TaskFeasibilityFieldNumber = 7;
    private static readonly pb::FieldCodec<global::Messages.Assembly.V1.TaskFeasibility> _repeated_taskFeasibility_codec
        = pb::FieldCodec.ForMessage(58, global::Messages.Assembly.V1.TaskFeasibility.Parser);
    private readonly pbc::RepeatedField<global::Messages.Assembly.V1.TaskFeasibility> taskFeasibility_ = new pbc::RepeatedField<global::Messages.Assembly.V1.TaskFeasibility>();
    /// <summary>
    /// Optional: useful if precheck computes feasible assignments/resources
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Messages.Assembly.V1.TaskFeasibility> TaskFeasibility {
      get { return taskFeasibility_; }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 8;
    private global::Messages.Assembly.V1.ProcessRunPrecheckStatus status_ = global::Messages.Assembly.V1.ProcessRunPrecheckStatus.Unspecified;
    /// <summary>
    /// Optional overall status
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Messages.Assembly.V1.ProcessRunPrecheckStatus Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ProcessRunPrecheckResult);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ProcessRunPrecheckResult other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Ok != other.Ok) return false;
      if(!issues_.Equals(other.issues_)) return false;
      if (BlockingIssueCount != other.BlockingIssueCount) return false;
      if (WarningIssueCount != other.WarningIssueCount) return false;
      if (ProcessRecipeId != other.ProcessRecipeId) return false;
      if (TargetLineId != other.TargetLineId) return false;
      if(!taskFeasibility_.Equals(other.taskFeasibility_)) return false;
      if (Status != other.Status) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Ok != false) hash ^= Ok.GetHashCode();
      hash ^= issues_.GetHashCode();
      if (BlockingIssueCount != 0) hash ^= BlockingIssueCount.GetHashCode();
      if (WarningIssueCount != 0) hash ^= WarningIssueCount.GetHashCode();
      if (ProcessRecipeId.Length != 0) hash ^= ProcessRecipeId.GetHashCode();
      if (TargetLineId.Length != 0) hash ^= TargetLineId.GetHashCode();
      hash ^= taskFeasibility_.GetHashCode();
      if (Status != global::Messages.Assembly.V1.ProcessRunPrecheckStatus.Unspecified) hash ^= Status.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Ok != false) {
        output.WriteRawTag(8);
        output.WriteBool(Ok);
      }
      issues_.WriteTo(output, _repeated_issues_codec);
      if (BlockingIssueCount != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(BlockingIssueCount);
      }
      if (WarningIssueCount != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(WarningIssueCount);
      }
      if (ProcessRecipeId.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(ProcessRecipeId);
      }
      if (TargetLineId.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(TargetLineId);
      }
      taskFeasibility_.WriteTo(output, _repeated_taskFeasibility_codec);
      if (Status != global::Messages.Assembly.V1.ProcessRunPrecheckStatus.Unspecified) {
        output.WriteRawTag(64);
        output.WriteEnum((int) Status);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Ok != false) {
        output.WriteRawTag(8);
        output.WriteBool(Ok);
      }
      issues_.WriteTo(ref output, _repeated_issues_codec);
      if (BlockingIssueCount != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(BlockingIssueCount);
      }
      if (WarningIssueCount != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(WarningIssueCount);
      }
      if (ProcessRecipeId.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(ProcessRecipeId);
      }
      if (TargetLineId.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(TargetLineId);
      }
      taskFeasibility_.WriteTo(ref output, _repeated_taskFeasibility_codec);
      if (Status != global::Messages.Assembly.V1.ProcessRunPrecheckStatus.Unspecified) {
        output.WriteRawTag(64);
        output.WriteEnum((int) Status);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Ok != false) {
        size += 1 + 1;
      }
      size += issues_.CalculateSize(_repeated_issues_codec);
      if (BlockingIssueCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BlockingIssueCount);
      }
      if (WarningIssueCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(WarningIssueCount);
      }
      if (ProcessRecipeId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ProcessRecipeId);
      }
      if (TargetLineId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TargetLineId);
      }
      size += taskFeasibility_.CalculateSize(_repeated_taskFeasibility_codec);
      if (Status != global::Messages.Assembly.V1.ProcessRunPrecheckStatus.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ProcessRunPrecheckResult other) {
      if (other == null) {
        return;
      }
      if (other.Ok != false) {
        Ok = other.Ok;
      }
      issues_.Add(other.issues_);
      if (other.BlockingIssueCount != 0) {
        BlockingIssueCount = other.BlockingIssueCount;
      }
      if (other.WarningIssueCount != 0) {
        WarningIssueCount = other.WarningIssueCount;
      }
      if (other.ProcessRecipeId.Length != 0) {
        ProcessRecipeId = other.ProcessRecipeId;
      }
      if (other.TargetLineId.Length != 0) {
        TargetLineId = other.TargetLineId;
      }
      taskFeasibility_.Add(other.taskFeasibility_);
      if (other.Status != global::Messages.Assembly.V1.ProcessRunPrecheckStatus.Unspecified) {
        Status = other.Status;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Ok = input.ReadBool();
            break;
          }
          case 18: {
            issues_.AddEntriesFrom(input, _repeated_issues_codec);
            break;
          }
          case 24: {
            BlockingIssueCount = input.ReadInt32();
            break;
          }
          case 32: {
            WarningIssueCount = input.ReadInt32();
            break;
          }
          case 42: {
            ProcessRecipeId = input.ReadString();
            break;
          }
          case 50: {
            TargetLineId = input.ReadString();
            break;
          }
          case 58: {
            taskFeasibility_.AddEntriesFrom(input, _repeated_taskFeasibility_codec);
            break;
          }
          case 64: {
            Status = (global::Messages.Assembly.V1.ProcessRunPrecheckStatus) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Ok = input.ReadBool();
            break;
          }
          case 18: {
            issues_.AddEntriesFrom(ref input, _repeated_issues_codec);
            break;
          }
          case 24: {
            BlockingIssueCount = input.ReadInt32();
            break;
          }
          case 32: {
            WarningIssueCount = input.ReadInt32();
            break;
          }
          case 42: {
            ProcessRecipeId = input.ReadString();
            break;
          }
          case 50: {
            TargetLineId = input.ReadString();
            break;
          }
          case 58: {
            taskFeasibility_.AddEntriesFrom(ref input, _repeated_taskFeasibility_codec);
            break;
          }
          case 64: {
            Status = (global::Messages.Assembly.V1.ProcessRunPrecheckStatus) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ProcessLoadResult : pb::IMessage<ProcessLoadResult>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ProcessLoadResult> _parser = new pb::MessageParser<ProcessLoadResult>(() => new ProcessLoadResult());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ProcessLoadResult> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Messages.Assembly.V1.ProcessRequestsReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProcessLoadResult() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProcessLoadResult(ProcessLoadResult other) : this() {
      status_ = other.status_;
      precheck_ = other.precheck_ != null ? other.precheck_.Clone() : null;
      processRun_ = other.processRun_ != null ? other.processRun_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProcessLoadResult Clone() {
      return new ProcessLoadResult(this);
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 1;
    private global::Messages.Assembly.V1.ProcessLoadStatus status_ = global::Messages.Assembly.V1.ProcessLoadStatus.Unspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Messages.Assembly.V1.ProcessLoadStatus Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "precheck" field.</summary>
    public const int PrecheckFieldNumber = 2;
    private global::Messages.Assembly.V1.ProcessRunPrecheckResult precheck_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Messages.Assembly.V1.ProcessRunPrecheckResult Precheck {
      get { return precheck_; }
      set {
        precheck_ = value;
      }
    }

    /// <summary>Field number for the "process_run" field.</summary>
    public const int ProcessRunFieldNumber = 3;
    private global::Messages.Assembly.V1.ProcessRun processRun_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Messages.Assembly.V1.ProcessRun ProcessRun {
      get { return processRun_; }
      set {
        processRun_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ProcessLoadResult);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ProcessLoadResult other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Status != other.Status) return false;
      if (!object.Equals(Precheck, other.Precheck)) return false;
      if (!object.Equals(ProcessRun, other.ProcessRun)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Status != global::Messages.Assembly.V1.ProcessLoadStatus.Unspecified) hash ^= Status.GetHashCode();
      if (precheck_ != null) hash ^= Precheck.GetHashCode();
      if (processRun_ != null) hash ^= ProcessRun.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Status != global::Messages.Assembly.V1.ProcessLoadStatus.Unspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Status);
      }
      if (precheck_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Precheck);
      }
      if (processRun_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(ProcessRun);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Status != global::Messages.Assembly.V1.ProcessLoadStatus.Unspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Status);
      }
      if (precheck_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Precheck);
      }
      if (processRun_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(ProcessRun);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Status != global::Messages.Assembly.V1.ProcessLoadStatus.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      if (precheck_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Precheck);
      }
      if (processRun_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ProcessRun);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ProcessLoadResult other) {
      if (other == null) {
        return;
      }
      if (other.Status != global::Messages.Assembly.V1.ProcessLoadStatus.Unspecified) {
        Status = other.Status;
      }
      if (other.precheck_ != null) {
        if (precheck_ == null) {
          Precheck = new global::Messages.Assembly.V1.ProcessRunPrecheckResult();
        }
        Precheck.MergeFrom(other.Precheck);
      }
      if (other.processRun_ != null) {
        if (processRun_ == null) {
          ProcessRun = new global::Messages.Assembly.V1.ProcessRun();
        }
        ProcessRun.MergeFrom(other.ProcessRun);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Status = (global::Messages.Assembly.V1.ProcessLoadStatus) input.ReadEnum();
            break;
          }
          case 18: {
            if (precheck_ == null) {
              Precheck = new global::Messages.Assembly.V1.ProcessRunPrecheckResult();
            }
            input.ReadMessage(Precheck);
            break;
          }
          case 26: {
            if (processRun_ == null) {
              ProcessRun = new global::Messages.Assembly.V1.ProcessRun();
            }
            input.ReadMessage(ProcessRun);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Status = (global::Messages.Assembly.V1.ProcessLoadStatus) input.ReadEnum();
            break;
          }
          case 18: {
            if (precheck_ == null) {
              Precheck = new global::Messages.Assembly.V1.ProcessRunPrecheckResult();
            }
            input.ReadMessage(Precheck);
            break;
          }
          case 26: {
            if (processRun_ == null) {
              ProcessRun = new global::Messages.Assembly.V1.ProcessRun();
            }
            input.ReadMessage(ProcessRun);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
