// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: resources/v1/robot_instance.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Messages.Resources.V1 {

  /// <summary>Holder for reflection information generated from resources/v1/robot_instance.proto</summary>
  public static partial class RobotInstanceReflection {

    #region Descriptor
    /// <summary>File descriptor for resources/v1/robot_instance.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RobotInstanceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiFyZXNvdXJjZXMvdjEvcm9ib3RfaW5zdGFuY2UucHJvdG8SDHJlc291cmNl",
            "cy52MRobYnVmL3ZhbGlkYXRlL3ZhbGlkYXRlLnByb3RvGiFjb21tb24vdjEv",
            "Y3VzdG9tX3Byb3BlcnRpZXMucHJvdG8aFWNvbW1vbi92MS9lbnVtcy5wcm90",
            "bxoWZ2VvbWV0cnkvdjEvcG9zZS5wcm90bxordmFsaWRhdGlvbi92MS9wcmVk",
            "ZWZpbmVkX3N0cmluZ19ydWxlcy5wcm90byKHBQoNUm9ib3RJbnN0YW5jZRIO",
            "CgJpZBgBIAEoCVICaWQSHQoEbmFtZRgCIAEoCUIJukgGcgSA8QQBUgRuYW1l",
            "EhIKBGljb24YAyABKAlSBGljb24SIAoLZGVzY3JpcHRpb24YBCABKAlSC2Rl",
            "c2NyaXB0aW9uEjwKE3JvYm90X2RlZmluaXRpb25faWQYBSABKAlCDLpICXIE",
            "oPEEAcgBAVIRcm9ib3REZWZpbml0aW9uSWQSIwoNc2VyaWFsX251bWJlchgG",
            "IAEoCVIMc2VyaWFsTnVtYmVyEisKCnN0YXRpb25faWQYByABKAlCDLpICXIE",
            "2PEEAcgBAVIJc3RhdGlvbklkEkIKGG1vdW50ZWRfdG9vbF9pbnN0YW5jZV9p",
            "ZBgIIAEoCUIJukgGcgTg8QQBUhVtb3VudGVkVG9vbEluc3RhbmNlSWQSPQob",
            "YXZhaWxhYmxlX3Rvb2xfaW5zdGFuY2VfaWRzGAkgAygJUhhhdmFpbGFibGVU",
            "b29sSW5zdGFuY2VJZHMSMAoUc3VwcG9ydHNfdG9vbF9jaGFuZ2UYCiABKAhS",
            "EnN1cHBvcnRzVG9vbENoYW5nZRIhCgxpc19zaW11bGF0ZWQYCyABKAhSC2lz",
            "U2ltdWxhdGVkEjsKBnN0YXR1cxgMIAEoDjIZLmNvbW1vbi52MS5SZXNvdXJj",
            "ZVN0YXR1c0IIukgFggECEAFSBnN0YXR1cxI3CgliYXNlX3Bvc2UYDSABKAsy",
            "Gi5nZW9tZXRyeS52MS5Mb2NhbGl6ZWRQb3NlUghiYXNlUG9zZRIzCgZjdXN0",
            "b20YDiABKAsyGy5jb21tb24udjEuQ3VzdG9tUHJvcGVydGllc1IGY3VzdG9t",
            "IkMKDlJvYm90SW5zdGFuY2VzEjEKBWl0ZW1zGAEgAygLMhsucmVzb3VyY2Vz",
            "LnYxLlJvYm90SW5zdGFuY2VSBWl0ZW1zQr8BChBjb20ucmVzb3VyY2VzLnYx",
            "QhJSb2JvdEluc3RhbmNlUHJvdG9QAVo9Z2l0aHViLmNvbS9jb2JvdGFyL3By",
            "b3RvY29sL21lc3NhZ2VzL3Jlc291cmNlcy92MTtyZXNvdXJjZXN2MaICA1JY",
            "WKoCFU1lc3NhZ2VzLlJlc291cmNlcy5WMcoCDFJlc291cmNlc1xWMeICGFJl",
            "c291cmNlc1xWMVxHUEJNZXRhZGF0YeoCDVJlc291cmNlczo6VjFiBnByb3Rv",
            "Mw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Buf.Validate.ValidateReflection.Descriptor, global::Messages.Common.V1.CustomPropertiesReflection.Descriptor, global::Messages.Common.V1.EnumsReflection.Descriptor, global::Messages.Common.V1.PoseReflection.Descriptor, global::Validation.V1.PredefinedStringRulesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Messages.Resources.V1.RobotInstance), global::Messages.Resources.V1.RobotInstance.Parser, new[]{ "Id", "Name", "Icon", "Description", "RobotDefinitionId", "SerialNumber", "StationId", "MountedToolInstanceId", "AvailableToolInstanceIds", "SupportsToolChange", "IsSimulated", "Status", "BasePose", "Custom" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Messages.Resources.V1.RobotInstances), global::Messages.Resources.V1.RobotInstances.Parser, new[]{ "Items" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class RobotInstance : pb::IMessage<RobotInstance>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RobotInstance> _parser = new pb::MessageParser<RobotInstance>(() => new RobotInstance());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RobotInstance> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Messages.Resources.V1.RobotInstanceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RobotInstance() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RobotInstance(RobotInstance other) : this() {
      id_ = other.id_;
      name_ = other.name_;
      icon_ = other.icon_;
      description_ = other.description_;
      robotDefinitionId_ = other.robotDefinitionId_;
      serialNumber_ = other.serialNumber_;
      stationId_ = other.stationId_;
      mountedToolInstanceId_ = other.mountedToolInstanceId_;
      availableToolInstanceIds_ = other.availableToolInstanceIds_.Clone();
      supportsToolChange_ = other.supportsToolChange_;
      isSimulated_ = other.isSimulated_;
      status_ = other.status_;
      basePose_ = other.basePose_ != null ? other.basePose_.Clone() : null;
      custom_ = other.custom_ != null ? other.custom_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RobotInstance Clone() {
      return new RobotInstance(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "icon" field.</summary>
    public const int IconFieldNumber = 3;
    private string icon_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Icon {
      get { return icon_; }
      set {
        icon_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "description" field.</summary>
    public const int DescriptionFieldNumber = 4;
    private string description_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Description {
      get { return description_; }
      set {
        description_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "robot_definition_id" field.</summary>
    public const int RobotDefinitionIdFieldNumber = 5;
    private string robotDefinitionId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string RobotDefinitionId {
      get { return robotDefinitionId_; }
      set {
        robotDefinitionId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "serial_number" field.</summary>
    public const int SerialNumberFieldNumber = 6;
    private string serialNumber_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SerialNumber {
      get { return serialNumber_; }
      set {
        serialNumber_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "station_id" field.</summary>
    public const int StationIdFieldNumber = 7;
    private string stationId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string StationId {
      get { return stationId_; }
      set {
        stationId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "mounted_tool_instance_id" field.</summary>
    public const int MountedToolInstanceIdFieldNumber = 8;
    private string mountedToolInstanceId_ = "";
    /// <summary>
    /// The tool instance currently mounted on the robot, if any.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MountedToolInstanceId {
      get { return mountedToolInstanceId_; }
      set {
        mountedToolInstanceId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "available_tool_instance_ids" field.</summary>
    public const int AvailableToolInstanceIdsFieldNumber = 9;
    private static readonly pb::FieldCodec<string> _repeated_availableToolInstanceIds_codec
        = pb::FieldCodec.ForString(74);
    private readonly pbc::RepeatedField<string> availableToolInstanceIds_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// Tool instances available to this robot in the cell/tool dock/tool magazine.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> AvailableToolInstanceIds {
      get { return availableToolInstanceIds_; }
    }

    /// <summary>Field number for the "supports_tool_change" field.</summary>
    public const int SupportsToolChangeFieldNumber = 10;
    private bool supportsToolChange_;
    /// <summary>
    /// Whether this robot instance can dynamically change between available tools.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool SupportsToolChange {
      get { return supportsToolChange_; }
      set {
        supportsToolChange_ = value;
      }
    }

    /// <summary>Field number for the "is_simulated" field.</summary>
    public const int IsSimulatedFieldNumber = 11;
    private bool isSimulated_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsSimulated {
      get { return isSimulated_; }
      set {
        isSimulated_ = value;
      }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 12;
    private global::Messages.Common.V1.ResourceStatus status_ = global::Messages.Common.V1.ResourceStatus.Unspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Messages.Common.V1.ResourceStatus Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "base_pose" field.</summary>
    public const int BasePoseFieldNumber = 13;
    private global::Messages.Common.V1.LocalizedPose basePose_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Messages.Common.V1.LocalizedPose BasePose {
      get { return basePose_; }
      set {
        basePose_ = value;
      }
    }

    /// <summary>Field number for the "custom" field.</summary>
    public const int CustomFieldNumber = 14;
    private global::Messages.Common.V1.CustomProperties custom_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Messages.Common.V1.CustomProperties Custom {
      get { return custom_; }
      set {
        custom_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RobotInstance);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RobotInstance other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Name != other.Name) return false;
      if (Icon != other.Icon) return false;
      if (Description != other.Description) return false;
      if (RobotDefinitionId != other.RobotDefinitionId) return false;
      if (SerialNumber != other.SerialNumber) return false;
      if (StationId != other.StationId) return false;
      if (MountedToolInstanceId != other.MountedToolInstanceId) return false;
      if(!availableToolInstanceIds_.Equals(other.availableToolInstanceIds_)) return false;
      if (SupportsToolChange != other.SupportsToolChange) return false;
      if (IsSimulated != other.IsSimulated) return false;
      if (Status != other.Status) return false;
      if (!object.Equals(BasePose, other.BasePose)) return false;
      if (!object.Equals(Custom, other.Custom)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Icon.Length != 0) hash ^= Icon.GetHashCode();
      if (Description.Length != 0) hash ^= Description.GetHashCode();
      if (RobotDefinitionId.Length != 0) hash ^= RobotDefinitionId.GetHashCode();
      if (SerialNumber.Length != 0) hash ^= SerialNumber.GetHashCode();
      if (StationId.Length != 0) hash ^= StationId.GetHashCode();
      if (MountedToolInstanceId.Length != 0) hash ^= MountedToolInstanceId.GetHashCode();
      hash ^= availableToolInstanceIds_.GetHashCode();
      if (SupportsToolChange != false) hash ^= SupportsToolChange.GetHashCode();
      if (IsSimulated != false) hash ^= IsSimulated.GetHashCode();
      if (Status != global::Messages.Common.V1.ResourceStatus.Unspecified) hash ^= Status.GetHashCode();
      if (basePose_ != null) hash ^= BasePose.GetHashCode();
      if (custom_ != null) hash ^= Custom.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (Icon.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Icon);
      }
      if (Description.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Description);
      }
      if (RobotDefinitionId.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(RobotDefinitionId);
      }
      if (SerialNumber.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(SerialNumber);
      }
      if (StationId.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(StationId);
      }
      if (MountedToolInstanceId.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(MountedToolInstanceId);
      }
      availableToolInstanceIds_.WriteTo(output, _repeated_availableToolInstanceIds_codec);
      if (SupportsToolChange != false) {
        output.WriteRawTag(80);
        output.WriteBool(SupportsToolChange);
      }
      if (IsSimulated != false) {
        output.WriteRawTag(88);
        output.WriteBool(IsSimulated);
      }
      if (Status != global::Messages.Common.V1.ResourceStatus.Unspecified) {
        output.WriteRawTag(96);
        output.WriteEnum((int) Status);
      }
      if (basePose_ != null) {
        output.WriteRawTag(106);
        output.WriteMessage(BasePose);
      }
      if (custom_ != null) {
        output.WriteRawTag(114);
        output.WriteMessage(Custom);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (Icon.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Icon);
      }
      if (Description.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Description);
      }
      if (RobotDefinitionId.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(RobotDefinitionId);
      }
      if (SerialNumber.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(SerialNumber);
      }
      if (StationId.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(StationId);
      }
      if (MountedToolInstanceId.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(MountedToolInstanceId);
      }
      availableToolInstanceIds_.WriteTo(ref output, _repeated_availableToolInstanceIds_codec);
      if (SupportsToolChange != false) {
        output.WriteRawTag(80);
        output.WriteBool(SupportsToolChange);
      }
      if (IsSimulated != false) {
        output.WriteRawTag(88);
        output.WriteBool(IsSimulated);
      }
      if (Status != global::Messages.Common.V1.ResourceStatus.Unspecified) {
        output.WriteRawTag(96);
        output.WriteEnum((int) Status);
      }
      if (basePose_ != null) {
        output.WriteRawTag(106);
        output.WriteMessage(BasePose);
      }
      if (custom_ != null) {
        output.WriteRawTag(114);
        output.WriteMessage(Custom);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Icon.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Icon);
      }
      if (Description.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Description);
      }
      if (RobotDefinitionId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RobotDefinitionId);
      }
      if (SerialNumber.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SerialNumber);
      }
      if (StationId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StationId);
      }
      if (MountedToolInstanceId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MountedToolInstanceId);
      }
      size += availableToolInstanceIds_.CalculateSize(_repeated_availableToolInstanceIds_codec);
      if (SupportsToolChange != false) {
        size += 1 + 1;
      }
      if (IsSimulated != false) {
        size += 1 + 1;
      }
      if (Status != global::Messages.Common.V1.ResourceStatus.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      if (basePose_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BasePose);
      }
      if (custom_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Custom);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RobotInstance other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Icon.Length != 0) {
        Icon = other.Icon;
      }
      if (other.Description.Length != 0) {
        Description = other.Description;
      }
      if (other.RobotDefinitionId.Length != 0) {
        RobotDefinitionId = other.RobotDefinitionId;
      }
      if (other.SerialNumber.Length != 0) {
        SerialNumber = other.SerialNumber;
      }
      if (other.StationId.Length != 0) {
        StationId = other.StationId;
      }
      if (other.MountedToolInstanceId.Length != 0) {
        MountedToolInstanceId = other.MountedToolInstanceId;
      }
      availableToolInstanceIds_.Add(other.availableToolInstanceIds_);
      if (other.SupportsToolChange != false) {
        SupportsToolChange = other.SupportsToolChange;
      }
      if (other.IsSimulated != false) {
        IsSimulated = other.IsSimulated;
      }
      if (other.Status != global::Messages.Common.V1.ResourceStatus.Unspecified) {
        Status = other.Status;
      }
      if (other.basePose_ != null) {
        if (basePose_ == null) {
          BasePose = new global::Messages.Common.V1.LocalizedPose();
        }
        BasePose.MergeFrom(other.BasePose);
      }
      if (other.custom_ != null) {
        if (custom_ == null) {
          Custom = new global::Messages.Common.V1.CustomProperties();
        }
        Custom.MergeFrom(other.Custom);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            Icon = input.ReadString();
            break;
          }
          case 34: {
            Description = input.ReadString();
            break;
          }
          case 42: {
            RobotDefinitionId = input.ReadString();
            break;
          }
          case 50: {
            SerialNumber = input.ReadString();
            break;
          }
          case 58: {
            StationId = input.ReadString();
            break;
          }
          case 66: {
            MountedToolInstanceId = input.ReadString();
            break;
          }
          case 74: {
            availableToolInstanceIds_.AddEntriesFrom(input, _repeated_availableToolInstanceIds_codec);
            break;
          }
          case 80: {
            SupportsToolChange = input.ReadBool();
            break;
          }
          case 88: {
            IsSimulated = input.ReadBool();
            break;
          }
          case 96: {
            Status = (global::Messages.Common.V1.ResourceStatus) input.ReadEnum();
            break;
          }
          case 106: {
            if (basePose_ == null) {
              BasePose = new global::Messages.Common.V1.LocalizedPose();
            }
            input.ReadMessage(BasePose);
            break;
          }
          case 114: {
            if (custom_ == null) {
              Custom = new global::Messages.Common.V1.CustomProperties();
            }
            input.ReadMessage(Custom);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            Icon = input.ReadString();
            break;
          }
          case 34: {
            Description = input.ReadString();
            break;
          }
          case 42: {
            RobotDefinitionId = input.ReadString();
            break;
          }
          case 50: {
            SerialNumber = input.ReadString();
            break;
          }
          case 58: {
            StationId = input.ReadString();
            break;
          }
          case 66: {
            MountedToolInstanceId = input.ReadString();
            break;
          }
          case 74: {
            availableToolInstanceIds_.AddEntriesFrom(ref input, _repeated_availableToolInstanceIds_codec);
            break;
          }
          case 80: {
            SupportsToolChange = input.ReadBool();
            break;
          }
          case 88: {
            IsSimulated = input.ReadBool();
            break;
          }
          case 96: {
            Status = (global::Messages.Common.V1.ResourceStatus) input.ReadEnum();
            break;
          }
          case 106: {
            if (basePose_ == null) {
              BasePose = new global::Messages.Common.V1.LocalizedPose();
            }
            input.ReadMessage(BasePose);
            break;
          }
          case 114: {
            if (custom_ == null) {
              Custom = new global::Messages.Common.V1.CustomProperties();
            }
            input.ReadMessage(Custom);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class RobotInstances : pb::IMessage<RobotInstances>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RobotInstances> _parser = new pb::MessageParser<RobotInstances>(() => new RobotInstances());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RobotInstances> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Messages.Resources.V1.RobotInstanceReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RobotInstances() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RobotInstances(RobotInstances other) : this() {
      items_ = other.items_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RobotInstances Clone() {
      return new RobotInstances(this);
    }

    /// <summary>Field number for the "items" field.</summary>
    public const int ItemsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Messages.Resources.V1.RobotInstance> _repeated_items_codec
        = pb::FieldCodec.ForMessage(10, global::Messages.Resources.V1.RobotInstance.Parser);
    private readonly pbc::RepeatedField<global::Messages.Resources.V1.RobotInstance> items_ = new pbc::RepeatedField<global::Messages.Resources.V1.RobotInstance>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Messages.Resources.V1.RobotInstance> Items {
      get { return items_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RobotInstances);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RobotInstances other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!items_.Equals(other.items_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= items_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      items_.WriteTo(output, _repeated_items_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      items_.WriteTo(ref output, _repeated_items_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += items_.CalculateSize(_repeated_items_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RobotInstances other) {
      if (other == null) {
        return;
      }
      items_.Add(other.items_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            items_.AddEntriesFrom(input, _repeated_items_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            items_.AddEntriesFrom(ref input, _repeated_items_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
