// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: resources/v1/worker_definition.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Messages.Resources.V1 {

  /// <summary>Holder for reflection information generated from resources/v1/worker_definition.proto</summary>
  public static partial class WorkerDefinitionReflection {

    #region Descriptor
    /// <summary>File descriptor for resources/v1/worker_definition.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static WorkerDefinitionReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiRyZXNvdXJjZXMvdjEvd29ya2VyX2RlZmluaXRpb24ucHJvdG8SDHJlc291",
            "cmNlcy52MRobYnVmL3ZhbGlkYXRlL3ZhbGlkYXRlLnByb3RvGiFjb21tb24v",
            "djEvY3VzdG9tX3Byb3BlcnRpZXMucHJvdG8aI2NvbW1vbi92MS9leHRlcm5h",
            "bF9yZWZlcmVuY2VzLnByb3RvGit2YWxpZGF0aW9uL3YxL3ByZWRlZmluZWRf",
            "c3RyaW5nX3J1bGVzLnByb3RvIoQDChBXb3JrZXJEZWZpbml0aW9uEg4KAmlk",
            "GAEgASgJUgJpZBIdCgRuYW1lGAIgASgJQgm6SAZyBIDxBAFSBG5hbWUSIAoL",
            "ZGVzY3JpcHRpb24YAyABKAlSC2Rlc2NyaXB0aW9uEhIKBGljb24YBCABKAlS",
            "BGljb24SGgoIZGlzYWJsZWQYBSABKAhSCGRpc2FibGVkEh8KC2VtcGxveWVl",
            "X2lkGAYgASgJUgplbXBsb3llZUlkEkoKEmFyX2VkaXRfcGVybWlzc2lvbhgH",
            "IAEoDjIcLnJlc291cmNlcy52MS5FZGl0UGVybWlzc2lvblIQYXJFZGl0UGVy",
            "bWlzc2lvbhJNChNleHRlcm5hbF9yZWZlcmVuY2VzGAggAygLMhwuY29tbW9u",
            "LnYxLkV4dGVybmFsUmVmZXJlbmNlUhJleHRlcm5hbFJlZmVyZW5jZXMSMwoG",
            "Y3VzdG9tGAkgASgLMhsuY29tbW9uLnYxLkN1c3RvbVByb3BlcnRpZXNSBmN1",
            "c3RvbSJJChFXb3JrZXJEZWZpbml0aW9ucxI0CgVpdGVtcxgBIAMoCzIeLnJl",
            "c291cmNlcy52MS5Xb3JrZXJEZWZpbml0aW9uUgVpdGVtcyqEAQoORWRpdFBl",
            "cm1pc3Npb24SHwobRURJVF9QRVJNSVNTSU9OX1VOU1BFQ0lGSUVEEAASGQoV",
            "RURJVF9QRVJNSVNTSU9OX0JBU0lDEAESHAoYRURJVF9QRVJNSVNTSU9OX0NP",
            "U01FVElDEAISGAoURURJVF9QRVJNSVNTSU9OX0ZVTEwQA0LCAQoQY29tLnJl",
            "c291cmNlcy52MUIVV29ya2VyRGVmaW5pdGlvblByb3RvUAFaPWdpdGh1Yi5j",
            "b20vY29ib3Rhci9wcm90b2NvbC9tZXNzYWdlcy9yZXNvdXJjZXMvdjE7cmVz",
            "b3VyY2VzdjGiAgNSWFiqAhVNZXNzYWdlcy5SZXNvdXJjZXMuVjHKAgxSZXNv",
            "dXJjZXNcVjHiAhhSZXNvdXJjZXNcVjFcR1BCTWV0YWRhdGHqAg1SZXNvdXJj",
            "ZXM6OlYxYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Buf.Validate.ValidateReflection.Descriptor, global::Messages.Common.V1.CustomPropertiesReflection.Descriptor, global::Messages.Common.V1.ExternalReferencesReflection.Descriptor, global::Validation.V1.PredefinedStringRulesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Messages.Resources.V1.EditPermission), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Messages.Resources.V1.WorkerDefinition), global::Messages.Resources.V1.WorkerDefinition.Parser, new[]{ "Id", "Name", "Description", "Icon", "Disabled", "EmployeeId", "ArEditPermission", "ExternalReferences", "Custom" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Messages.Resources.V1.WorkerDefinitions), global::Messages.Resources.V1.WorkerDefinitions.Parser, new[]{ "Items" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum EditPermission {
    /// <summary>
    /// Unspecified: can't edit any properties
    /// </summary>
    [pbr::OriginalName("EDIT_PERMISSION_UNSPECIFIED")] Unspecified = 0,
    /// <summary>
    /// Basic: can edit {basic} properties
    /// </summary>
    [pbr::OriginalName("EDIT_PERMISSION_BASIC")] Basic = 1,
    /// <summary>
    /// Cosmetic: can edit {basic, cosmetic} properties
    /// </summary>
    [pbr::OriginalName("EDIT_PERMISSION_COSMETIC")] Cosmetic = 2,
    /// <summary>
    /// Full: can edit all editable properties
    /// </summary>
    [pbr::OriginalName("EDIT_PERMISSION_FULL")] Full = 3,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class WorkerDefinition : pb::IMessage<WorkerDefinition>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WorkerDefinition> _parser = new pb::MessageParser<WorkerDefinition>(() => new WorkerDefinition());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WorkerDefinition> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Messages.Resources.V1.WorkerDefinitionReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorkerDefinition() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorkerDefinition(WorkerDefinition other) : this() {
      id_ = other.id_;
      name_ = other.name_;
      description_ = other.description_;
      icon_ = other.icon_;
      disabled_ = other.disabled_;
      employeeId_ = other.employeeId_;
      arEditPermission_ = other.arEditPermission_;
      externalReferences_ = other.externalReferences_.Clone();
      custom_ = other.custom_ != null ? other.custom_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorkerDefinition Clone() {
      return new WorkerDefinition(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "description" field.</summary>
    public const int DescriptionFieldNumber = 3;
    private string description_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Description {
      get { return description_; }
      set {
        description_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "icon" field.</summary>
    public const int IconFieldNumber = 4;
    private string icon_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Icon {
      get { return icon_; }
      set {
        icon_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "disabled" field.</summary>
    public const int DisabledFieldNumber = 5;
    private bool disabled_;
    /// <summary>
    /// If disabled, the worker can't be selected
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Disabled {
      get { return disabled_; }
      set {
        disabled_ = value;
      }
    }

    /// <summary>Field number for the "employee_id" field.</summary>
    public const int EmployeeIdFieldNumber = 6;
    private string employeeId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string EmployeeId {
      get { return employeeId_; }
      set {
        employeeId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ar_edit_permission" field.</summary>
    public const int ArEditPermissionFieldNumber = 7;
    private global::Messages.Resources.V1.EditPermission arEditPermission_ = global::Messages.Resources.V1.EditPermission.Unspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Messages.Resources.V1.EditPermission ArEditPermission {
      get { return arEditPermission_; }
      set {
        arEditPermission_ = value;
      }
    }

    /// <summary>Field number for the "external_references" field.</summary>
    public const int ExternalReferencesFieldNumber = 8;
    private static readonly pb::FieldCodec<global::Messages.Common.V1.ExternalReference> _repeated_externalReferences_codec
        = pb::FieldCodec.ForMessage(66, global::Messages.Common.V1.ExternalReference.Parser);
    private readonly pbc::RepeatedField<global::Messages.Common.V1.ExternalReference> externalReferences_ = new pbc::RepeatedField<global::Messages.Common.V1.ExternalReference>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Messages.Common.V1.ExternalReference> ExternalReferences {
      get { return externalReferences_; }
    }

    /// <summary>Field number for the "custom" field.</summary>
    public const int CustomFieldNumber = 9;
    private global::Messages.Common.V1.CustomProperties custom_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Messages.Common.V1.CustomProperties Custom {
      get { return custom_; }
      set {
        custom_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WorkerDefinition);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WorkerDefinition other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Name != other.Name) return false;
      if (Description != other.Description) return false;
      if (Icon != other.Icon) return false;
      if (Disabled != other.Disabled) return false;
      if (EmployeeId != other.EmployeeId) return false;
      if (ArEditPermission != other.ArEditPermission) return false;
      if(!externalReferences_.Equals(other.externalReferences_)) return false;
      if (!object.Equals(Custom, other.Custom)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Description.Length != 0) hash ^= Description.GetHashCode();
      if (Icon.Length != 0) hash ^= Icon.GetHashCode();
      if (Disabled != false) hash ^= Disabled.GetHashCode();
      if (EmployeeId.Length != 0) hash ^= EmployeeId.GetHashCode();
      if (ArEditPermission != global::Messages.Resources.V1.EditPermission.Unspecified) hash ^= ArEditPermission.GetHashCode();
      hash ^= externalReferences_.GetHashCode();
      if (custom_ != null) hash ^= Custom.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (Description.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Description);
      }
      if (Icon.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Icon);
      }
      if (Disabled != false) {
        output.WriteRawTag(40);
        output.WriteBool(Disabled);
      }
      if (EmployeeId.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(EmployeeId);
      }
      if (ArEditPermission != global::Messages.Resources.V1.EditPermission.Unspecified) {
        output.WriteRawTag(56);
        output.WriteEnum((int) ArEditPermission);
      }
      externalReferences_.WriteTo(output, _repeated_externalReferences_codec);
      if (custom_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(Custom);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (Description.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Description);
      }
      if (Icon.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Icon);
      }
      if (Disabled != false) {
        output.WriteRawTag(40);
        output.WriteBool(Disabled);
      }
      if (EmployeeId.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(EmployeeId);
      }
      if (ArEditPermission != global::Messages.Resources.V1.EditPermission.Unspecified) {
        output.WriteRawTag(56);
        output.WriteEnum((int) ArEditPermission);
      }
      externalReferences_.WriteTo(ref output, _repeated_externalReferences_codec);
      if (custom_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(Custom);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Description.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Description);
      }
      if (Icon.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Icon);
      }
      if (Disabled != false) {
        size += 1 + 1;
      }
      if (EmployeeId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EmployeeId);
      }
      if (ArEditPermission != global::Messages.Resources.V1.EditPermission.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ArEditPermission);
      }
      size += externalReferences_.CalculateSize(_repeated_externalReferences_codec);
      if (custom_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Custom);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WorkerDefinition other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Description.Length != 0) {
        Description = other.Description;
      }
      if (other.Icon.Length != 0) {
        Icon = other.Icon;
      }
      if (other.Disabled != false) {
        Disabled = other.Disabled;
      }
      if (other.EmployeeId.Length != 0) {
        EmployeeId = other.EmployeeId;
      }
      if (other.ArEditPermission != global::Messages.Resources.V1.EditPermission.Unspecified) {
        ArEditPermission = other.ArEditPermission;
      }
      externalReferences_.Add(other.externalReferences_);
      if (other.custom_ != null) {
        if (custom_ == null) {
          Custom = new global::Messages.Common.V1.CustomProperties();
        }
        Custom.MergeFrom(other.Custom);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            Description = input.ReadString();
            break;
          }
          case 34: {
            Icon = input.ReadString();
            break;
          }
          case 40: {
            Disabled = input.ReadBool();
            break;
          }
          case 50: {
            EmployeeId = input.ReadString();
            break;
          }
          case 56: {
            ArEditPermission = (global::Messages.Resources.V1.EditPermission) input.ReadEnum();
            break;
          }
          case 66: {
            externalReferences_.AddEntriesFrom(input, _repeated_externalReferences_codec);
            break;
          }
          case 74: {
            if (custom_ == null) {
              Custom = new global::Messages.Common.V1.CustomProperties();
            }
            input.ReadMessage(Custom);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            Description = input.ReadString();
            break;
          }
          case 34: {
            Icon = input.ReadString();
            break;
          }
          case 40: {
            Disabled = input.ReadBool();
            break;
          }
          case 50: {
            EmployeeId = input.ReadString();
            break;
          }
          case 56: {
            ArEditPermission = (global::Messages.Resources.V1.EditPermission) input.ReadEnum();
            break;
          }
          case 66: {
            externalReferences_.AddEntriesFrom(ref input, _repeated_externalReferences_codec);
            break;
          }
          case 74: {
            if (custom_ == null) {
              Custom = new global::Messages.Common.V1.CustomProperties();
            }
            input.ReadMessage(Custom);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class WorkerDefinitions : pb::IMessage<WorkerDefinitions>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WorkerDefinitions> _parser = new pb::MessageParser<WorkerDefinitions>(() => new WorkerDefinitions());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WorkerDefinitions> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Messages.Resources.V1.WorkerDefinitionReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorkerDefinitions() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorkerDefinitions(WorkerDefinitions other) : this() {
      items_ = other.items_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorkerDefinitions Clone() {
      return new WorkerDefinitions(this);
    }

    /// <summary>Field number for the "items" field.</summary>
    public const int ItemsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Messages.Resources.V1.WorkerDefinition> _repeated_items_codec
        = pb::FieldCodec.ForMessage(10, global::Messages.Resources.V1.WorkerDefinition.Parser);
    private readonly pbc::RepeatedField<global::Messages.Resources.V1.WorkerDefinition> items_ = new pbc::RepeatedField<global::Messages.Resources.V1.WorkerDefinition>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Messages.Resources.V1.WorkerDefinition> Items {
      get { return items_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WorkerDefinitions);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WorkerDefinitions other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!items_.Equals(other.items_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= items_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      items_.WriteTo(output, _repeated_items_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      items_.WriteTo(ref output, _repeated_items_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += items_.CalculateSize(_repeated_items_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WorkerDefinitions other) {
      if (other == null) {
        return;
      }
      items_.Add(other.items_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            items_.AddEntriesFrom(input, _repeated_items_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            items_.AddEntriesFrom(ref input, _repeated_items_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
