// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: plm/v1/fixture.proto

package plmv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FixtureType int32

const (
	FixtureType_FIXTURE_TYPE_UNSPECIFIED FixtureType = 0
)

// Enum value maps for FixtureType.
var (
	FixtureType_name = map[int32]string{
		0: "FIXTURE_TYPE_UNSPECIFIED",
	}
	FixtureType_value = map[string]int32{
		"FIXTURE_TYPE_UNSPECIFIED": 0,
	}
)

func (x FixtureType) Enum() *FixtureType {
	p := new(FixtureType)
	*p = x
	return p
}

func (x FixtureType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FixtureType) Descriptor() protoreflect.EnumDescriptor {
	return file_plm_v1_fixture_proto_enumTypes[0].Descriptor()
}

func (FixtureType) Type() protoreflect.EnumType {
	return &file_plm_v1_fixture_proto_enumTypes[0]
}

func (x FixtureType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FixtureType.Descriptor instead.
func (FixtureType) EnumDescriptor() ([]byte, []int) {
	return file_plm_v1_fixture_proto_rawDescGZIP(), []int{0}
}

type FixtureMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon            string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Description     string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Type            FixtureType            `protobuf:"varint,5,opt,name=type,proto3,enum=plm.v1.FixtureType" json:"type,omitempty"`
	AcceptedPartIds []string               `protobuf:"bytes,6,rep,name=accepted_part_ids,json=acceptedPartIds,proto3" json:"accepted_part_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FixtureMessage) Reset() {
	*x = FixtureMessage{}
	mi := &file_plm_v1_fixture_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FixtureMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FixtureMessage) ProtoMessage() {}

func (x *FixtureMessage) ProtoReflect() protoreflect.Message {
	mi := &file_plm_v1_fixture_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FixtureMessage.ProtoReflect.Descriptor instead.
func (*FixtureMessage) Descriptor() ([]byte, []int) {
	return file_plm_v1_fixture_proto_rawDescGZIP(), []int{0}
}

func (x *FixtureMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FixtureMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FixtureMessage) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *FixtureMessage) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FixtureMessage) GetType() FixtureType {
	if x != nil {
		return x.Type
	}
	return FixtureType_FIXTURE_TYPE_UNSPECIFIED
}

func (x *FixtureMessage) GetAcceptedPartIds() []string {
	if x != nil {
		return x.AcceptedPartIds
	}
	return nil
}

type FixtureMessages struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fixtures      []*FixtureMessage      `protobuf:"bytes,1,rep,name=fixtures,proto3" json:"fixtures,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FixtureMessages) Reset() {
	*x = FixtureMessages{}
	mi := &file_plm_v1_fixture_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FixtureMessages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FixtureMessages) ProtoMessage() {}

func (x *FixtureMessages) ProtoReflect() protoreflect.Message {
	mi := &file_plm_v1_fixture_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FixtureMessages.ProtoReflect.Descriptor instead.
func (*FixtureMessages) Descriptor() ([]byte, []int) {
	return file_plm_v1_fixture_proto_rawDescGZIP(), []int{1}
}

func (x *FixtureMessages) GetFixtures() []*FixtureMessage {
	if x != nil {
		return x.Fixtures
	}
	return nil
}

var File_plm_v1_fixture_proto protoreflect.FileDescriptor

const file_plm_v1_fixture_proto_rawDesc = "" +
	"\n" +
	"\x14plm/v1/fixture.proto\x12\x06plm.v1\"\xbf\x01\n" +
	"\x0eFixtureMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12'\n" +
	"\x04type\x18\x05 \x01(\x0e2\x13.plm.v1.FixtureTypeR\x04type\x12*\n" +
	"\x11accepted_part_ids\x18\x06 \x03(\tR\x0facceptedPartIds\"E\n" +
	"\x0fFixtureMessages\x122\n" +
	"\bfixtures\x18\x01 \x03(\v2\x16.plm.v1.FixtureMessageR\bfixtures*+\n" +
	"\vFixtureType\x12\x1c\n" +
	"\x18FIXTURE_TYPE_UNSPECIFIED\x10\x00B\x8f\x01\n" +
	"\n" +
	"com.plm.v1B\fFixtureProtoP\x01Z1github.com/cobotar/protocol/messages/plm/v1;plmv1\xa2\x02\x03PXX\xaa\x02\x0fMessages.Plm.V1\xca\x02\x06Plm\\V1\xe2\x02\x12Plm\\V1\\GPBMetadata\xea\x02\aPlm::V1b\x06proto3"

var (
	file_plm_v1_fixture_proto_rawDescOnce sync.Once
	file_plm_v1_fixture_proto_rawDescData []byte
)

func file_plm_v1_fixture_proto_rawDescGZIP() []byte {
	file_plm_v1_fixture_proto_rawDescOnce.Do(func() {
		file_plm_v1_fixture_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plm_v1_fixture_proto_rawDesc), len(file_plm_v1_fixture_proto_rawDesc)))
	})
	return file_plm_v1_fixture_proto_rawDescData
}

var file_plm_v1_fixture_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_plm_v1_fixture_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_plm_v1_fixture_proto_goTypes = []any{
	(FixtureType)(0),        // 0: plm.v1.FixtureType
	(*FixtureMessage)(nil),  // 1: plm.v1.FixtureMessage
	(*FixtureMessages)(nil), // 2: plm.v1.FixtureMessages
}
var file_plm_v1_fixture_proto_depIdxs = []int32{
	0, // 0: plm.v1.FixtureMessage.type:type_name -> plm.v1.FixtureType
	1, // 1: plm.v1.FixtureMessages.fixtures:type_name -> plm.v1.FixtureMessage
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_plm_v1_fixture_proto_init() }
func file_plm_v1_fixture_proto_init() {
	if File_plm_v1_fixture_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plm_v1_fixture_proto_rawDesc), len(file_plm_v1_fixture_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_plm_v1_fixture_proto_goTypes,
		DependencyIndexes: file_plm_v1_fixture_proto_depIdxs,
		EnumInfos:         file_plm_v1_fixture_proto_enumTypes,
		MessageInfos:      file_plm_v1_fixture_proto_msgTypes,
	}.Build()
	File_plm_v1_fixture_proto = out.File
	file_plm_v1_fixture_proto_goTypes = nil
	file_plm_v1_fixture_proto_depIdxs = nil
}
