from buf.validate import validate_pb2 as _validate_pb2
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor
NAME_COMPONENT_FIELD_NUMBER: _ClassVar[int]
name_component: _descriptor.FieldDescriptor
MODEL_ID_COMPONENT_FIELD_NUMBER: _ClassVar[int]
model_id_component: _descriptor.FieldDescriptor
AR_CONFIG_ID_COMPONENT_FIELD_NUMBER: _ClassVar[int]
ar_config_id_component: _descriptor.FieldDescriptor
PROPERTY_ID_COMPONENT_FIELD_NUMBER: _ClassVar[int]
property_id_component: _descriptor.FieldDescriptor
ROBOT_ID_COMPONENT_FIELD_NUMBER: _ClassVar[int]
robot_id_component: _descriptor.FieldDescriptor
ASSET_ID_COMPONENT_FIELD_NUMBER: _ClassVar[int]
asset_id_component: _descriptor.FieldDescriptor
ENVIRONMENT_ID_COMPONENT_FIELD_NUMBER: _ClassVar[int]
environment_id_component: _descriptor.FieldDescriptor
PART_ID_COMPONENT_FIELD_NUMBER: _ClassVar[int]
part_id_component: _descriptor.FieldDescriptor
TOOL_ID_COMPONENT_FIELD_NUMBER: _ClassVar[int]
tool_id_component: _descriptor.FieldDescriptor
TOOL_INSTANCE_ID_COMPONENT_FIELD_NUMBER: _ClassVar[int]
tool_instance_id_component: _descriptor.FieldDescriptor
MARKER_ID_COMPONENT_FIELD_NUMBER: _ClassVar[int]
marker_id_component: _descriptor.FieldDescriptor
FIXTURE_ID_COMPONENT_FIELD_NUMBER: _ClassVar[int]
fixture_id_component: _descriptor.FieldDescriptor
STATION_ID_COMPONENT_FIELD_NUMBER: _ClassVar[int]
station_id_component: _descriptor.FieldDescriptor
SKILL_ID_COMPONENT_FIELD_NUMBER: _ClassVar[int]
skill_id_component: _descriptor.FieldDescriptor
PROCESS_RUN_ID_COMPONENT_FIELD_NUMBER: _ClassVar[int]
process_run_id_component: _descriptor.FieldDescriptor
SEQUENCE_RUN_ID_COMPONENT_FIELD_NUMBER: _ClassVar[int]
sequence_run_id_component: _descriptor.FieldDescriptor
TASK_RUN_ID_COMPONENT_FIELD_NUMBER: _ClassVar[int]
task_run_id_component: _descriptor.FieldDescriptor
PROCESS_RECIPE_ID_COMPONENT_FIELD_NUMBER: _ClassVar[int]
process_recipe_id_component: _descriptor.FieldDescriptor
SEQUENCE_DEFINITION_ID_COMPONENT_FIELD_NUMBER: _ClassVar[int]
sequence_definition_id_component: _descriptor.FieldDescriptor
TASK_DEFINITION_ID_COMPONENT_FIELD_NUMBER: _ClassVar[int]
task_definition_id_component: _descriptor.FieldDescriptor
CELL_ID_COMPONENT_FIELD_NUMBER: _ClassVar[int]
cell_id_component: _descriptor.FieldDescriptor
