from buf.validate import validate_pb2 as _validate_pb2
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor
NAME_COMPONENT_FIELD_NUMBER: _ClassVar[int]
name_component: _descriptor.FieldDescriptor
MODEL_ID_COMPONENT_FIELD_NUMBER: _ClassVar[int]
model_id_component: _descriptor.FieldDescriptor
AR_CONFIG_ID_COMPONENT_FIELD_NUMBER: _ClassVar[int]
ar_config_id_component: _descriptor.FieldDescriptor
PROPERTY_ID_COMPONENT_FIELD_NUMBER: _ClassVar[int]
property_id_component: _descriptor.FieldDescriptor
ROBOT_ID_COMPONENT_FIELD_NUMBER: _ClassVar[int]
robot_id_component: _descriptor.FieldDescriptor
ASSET_ID_COMPONENT_FIELD_NUMBER: _ClassVar[int]
asset_id_component: _descriptor.FieldDescriptor
ENVIRONMENT_ID_COMPONENT_FIELD_NUMBER: _ClassVar[int]
environment_id_component: _descriptor.FieldDescriptor
PART_ID_COMPONENT_FIELD_NUMBER: _ClassVar[int]
part_id_component: _descriptor.FieldDescriptor
TOOL_ID_COMPONENT_FIELD_NUMBER: _ClassVar[int]
tool_id_component: _descriptor.FieldDescriptor
MARKER_ID_COMPONENT_FIELD_NUMBER: _ClassVar[int]
marker_id_component: _descriptor.FieldDescriptor
