// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: seed/v1/seed.proto

package seedv1

import (
	v15 "github.com/cobotar/protocol/messages/ar/v1"
	v11 "github.com/cobotar/protocol/messages/capability/v1"
	v13 "github.com/cobotar/protocol/messages/process/v1"
	v12 "github.com/cobotar/protocol/messages/product/v1"
	v1 "github.com/cobotar/protocol/messages/resources/v1"
	v14 "github.com/cobotar/protocol/messages/runtime/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Seed struct {
	state                protoimpl.MessageState    `protogen:"open.v1"`
	Lines                []*v1.LineDefinition      `protobuf:"bytes,1,rep,name=lines,proto3" json:"lines,omitempty"`
	Cells                []*v1.CellDefinition      `protobuf:"bytes,2,rep,name=cells,proto3" json:"cells,omitempty"`
	Stations             []*v1.StationDefinition   `protobuf:"bytes,3,rep,name=stations,proto3" json:"stations,omitempty"`
	Workers              []*v1.WorkerDefinition    `protobuf:"bytes,10,rep,name=workers,proto3" json:"workers,omitempty"`
	RobotDefinitions     []*v1.RobotDefinition     `protobuf:"bytes,11,rep,name=robot_definitions,json=robotDefinitions,proto3" json:"robot_definitions,omitempty"`
	RobotInstances       []*v1.RobotInstance       `protobuf:"bytes,12,rep,name=robot_instances,json=robotInstances,proto3" json:"robot_instances,omitempty"`
	Skills               []*v11.SkillDefinition    `protobuf:"bytes,13,rep,name=skills,proto3" json:"skills,omitempty"`
	ActorSkills          []*v11.ActorSkill         `protobuf:"bytes,14,rep,name=actor_skills,json=actorSkills,proto3" json:"actor_skills,omitempty"`
	Devices              []*v1.DeviceMessage       `protobuf:"bytes,15,rep,name=devices,proto3" json:"devices,omitempty"`
	Models               []*v1.ModelArtifact       `protobuf:"bytes,20,rep,name=models,proto3" json:"models,omitempty"`
	AssetDefinitions     []*v1.AssetDefinition     `protobuf:"bytes,30,rep,name=asset_definitions,json=assetDefinitions,proto3" json:"asset_definitions,omitempty"`
	AssetInstances       []*v1.AssetInstance       `protobuf:"bytes,31,rep,name=asset_instances,json=assetInstances,proto3" json:"asset_instances,omitempty"`
	ContainerDefinitions []*v1.ContainerDefinition `protobuf:"bytes,32,rep,name=container_definitions,json=containerDefinitions,proto3" json:"container_definitions,omitempty"`
	ContainerInstances   []*v1.ContainerInstance   `protobuf:"bytes,33,rep,name=container_instances,json=containerInstances,proto3" json:"container_instances,omitempty"`
	ToolDefinitions      []*v1.ToolDefinition      `protobuf:"bytes,34,rep,name=tool_definitions,json=toolDefinitions,proto3" json:"tool_definitions,omitempty"`
	ToolInstances        []*v1.ToolInstance        `protobuf:"bytes,35,rep,name=tool_instances,json=toolInstances,proto3" json:"tool_instances,omitempty"`
	Markers              []*v1.MarkerInstance      `protobuf:"bytes,36,rep,name=markers,proto3" json:"markers,omitempty"`
	PartDefinitions      []*v12.PartDefinition     `protobuf:"bytes,40,rep,name=part_definitions,json=partDefinitions,proto3" json:"part_definitions,omitempty"`
	PartInstances        []*v12.PartInstance       `protobuf:"bytes,41,rep,name=part_instances,json=partInstances,proto3" json:"part_instances,omitempty"`
	Products             []*v12.ProductDefinition  `protobuf:"bytes,42,rep,name=products,proto3" json:"products,omitempty"`
	Recipes              []*v13.ProcessRecipe      `protobuf:"bytes,43,rep,name=recipes,proto3" json:"recipes,omitempty"`
	Sequences            []*v13.SequenceDefinition `protobuf:"bytes,44,rep,name=sequences,proto3" json:"sequences,omitempty"`
	Tasks                []*v13.TaskDefinition     `protobuf:"bytes,45,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Processes            []*v14.ProcessRun         `protobuf:"bytes,50,rep,name=processes,proto3" json:"processes,omitempty"`
	SequenceRuns         []*v14.SequenceRun        `protobuf:"bytes,51,rep,name=sequence_runs,json=sequenceRuns,proto3" json:"sequence_runs,omitempty"`
	TaskRuns             []*v14.TaskRun            `protobuf:"bytes,52,rep,name=task_runs,json=taskRuns,proto3" json:"task_runs,omitempty"`
	Feedback             []*v15.FeedbackMessage    `protobuf:"bytes,60,rep,name=feedback,proto3" json:"feedback,omitempty"`
	Actions              []*v15.ActionMessage      `protobuf:"bytes,61,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Seed) Reset() {
	*x = Seed{}
	mi := &file_seed_v1_seed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Seed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Seed) ProtoMessage() {}

func (x *Seed) ProtoReflect() protoreflect.Message {
	mi := &file_seed_v1_seed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Seed.ProtoReflect.Descriptor instead.
func (*Seed) Descriptor() ([]byte, []int) {
	return file_seed_v1_seed_proto_rawDescGZIP(), []int{0}
}

func (x *Seed) GetLines() []*v1.LineDefinition {
	if x != nil {
		return x.Lines
	}
	return nil
}

func (x *Seed) GetCells() []*v1.CellDefinition {
	if x != nil {
		return x.Cells
	}
	return nil
}

func (x *Seed) GetStations() []*v1.StationDefinition {
	if x != nil {
		return x.Stations
	}
	return nil
}

func (x *Seed) GetWorkers() []*v1.WorkerDefinition {
	if x != nil {
		return x.Workers
	}
	return nil
}

func (x *Seed) GetRobotDefinitions() []*v1.RobotDefinition {
	if x != nil {
		return x.RobotDefinitions
	}
	return nil
}

func (x *Seed) GetRobotInstances() []*v1.RobotInstance {
	if x != nil {
		return x.RobotInstances
	}
	return nil
}

func (x *Seed) GetSkills() []*v11.SkillDefinition {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *Seed) GetActorSkills() []*v11.ActorSkill {
	if x != nil {
		return x.ActorSkills
	}
	return nil
}

func (x *Seed) GetDevices() []*v1.DeviceMessage {
	if x != nil {
		return x.Devices
	}
	return nil
}

func (x *Seed) GetModels() []*v1.ModelArtifact {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *Seed) GetAssetDefinitions() []*v1.AssetDefinition {
	if x != nil {
		return x.AssetDefinitions
	}
	return nil
}

func (x *Seed) GetAssetInstances() []*v1.AssetInstance {
	if x != nil {
		return x.AssetInstances
	}
	return nil
}

func (x *Seed) GetContainerDefinitions() []*v1.ContainerDefinition {
	if x != nil {
		return x.ContainerDefinitions
	}
	return nil
}

func (x *Seed) GetContainerInstances() []*v1.ContainerInstance {
	if x != nil {
		return x.ContainerInstances
	}
	return nil
}

func (x *Seed) GetToolDefinitions() []*v1.ToolDefinition {
	if x != nil {
		return x.ToolDefinitions
	}
	return nil
}

func (x *Seed) GetToolInstances() []*v1.ToolInstance {
	if x != nil {
		return x.ToolInstances
	}
	return nil
}

func (x *Seed) GetMarkers() []*v1.MarkerInstance {
	if x != nil {
		return x.Markers
	}
	return nil
}

func (x *Seed) GetPartDefinitions() []*v12.PartDefinition {
	if x != nil {
		return x.PartDefinitions
	}
	return nil
}

func (x *Seed) GetPartInstances() []*v12.PartInstance {
	if x != nil {
		return x.PartInstances
	}
	return nil
}

func (x *Seed) GetProducts() []*v12.ProductDefinition {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *Seed) GetRecipes() []*v13.ProcessRecipe {
	if x != nil {
		return x.Recipes
	}
	return nil
}

func (x *Seed) GetSequences() []*v13.SequenceDefinition {
	if x != nil {
		return x.Sequences
	}
	return nil
}

func (x *Seed) GetTasks() []*v13.TaskDefinition {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *Seed) GetProcesses() []*v14.ProcessRun {
	if x != nil {
		return x.Processes
	}
	return nil
}

func (x *Seed) GetSequenceRuns() []*v14.SequenceRun {
	if x != nil {
		return x.SequenceRuns
	}
	return nil
}

func (x *Seed) GetTaskRuns() []*v14.TaskRun {
	if x != nil {
		return x.TaskRuns
	}
	return nil
}

func (x *Seed) GetFeedback() []*v15.FeedbackMessage {
	if x != nil {
		return x.Feedback
	}
	return nil
}

func (x *Seed) GetActions() []*v15.ActionMessage {
	if x != nil {
		return x.Actions
	}
	return nil
}

var File_seed_v1_seed_proto protoreflect.FileDescriptor

const file_seed_v1_seed_proto_rawDesc = "" +
	"\n" +
	"\x12seed/v1/seed.proto\x12\aseed.v1\x1a\x12ar/v1/action.proto\x1a\x14ar/v1/feedback.proto\x1a\x1fcapability/v1/actor_skill.proto\x1a$capability/v1/skill_definition.proto\x1a\x1fprocess/v1/process_recipe.proto\x1a$process/v1/sequence_definition.proto\x1a process/v1/task_definition.proto\x1a product/v1/part_definition.proto\x1a\x1eproduct/v1/part_instance.proto\x1a#product/v1/product_definition.proto\x1a#resources/v1/asset_definition.proto\x1a!resources/v1/asset_instance.proto\x1a\"resources/v1/cell_definition.proto\x1a'resources/v1/container_definition.proto\x1a%resources/v1/container_instance.proto\x1a\x19resources/v1/device.proto\x1a\"resources/v1/line_definition.proto\x1a\"resources/v1/marker_instance.proto\x1a\x18resources/v1/model.proto\x1a#resources/v1/robot_definition.proto\x1a!resources/v1/robot_instance.proto\x1a%resources/v1/station_definition.proto\x1a\"resources/v1/tool_definition.proto\x1a resources/v1/tool_instance.proto\x1a$resources/v1/worker_definition.proto\x1a\x1cruntime/v1/process_run.proto\x1a\x1druntime/v1/sequence_run.proto\x1a\x19runtime/v1/task_run.proto\"\xcb\r\n" +
	"\x04Seed\x122\n" +
	"\x05lines\x18\x01 \x03(\v2\x1c.resources.v1.LineDefinitionR\x05lines\x122\n" +
	"\x05cells\x18\x02 \x03(\v2\x1c.resources.v1.CellDefinitionR\x05cells\x12;\n" +
	"\bstations\x18\x03 \x03(\v2\x1f.resources.v1.StationDefinitionR\bstations\x128\n" +
	"\aworkers\x18\n" +
	" \x03(\v2\x1e.resources.v1.WorkerDefinitionR\aworkers\x12J\n" +
	"\x11robot_definitions\x18\v \x03(\v2\x1d.resources.v1.RobotDefinitionR\x10robotDefinitions\x12D\n" +
	"\x0frobot_instances\x18\f \x03(\v2\x1b.resources.v1.RobotInstanceR\x0erobotInstances\x126\n" +
	"\x06skills\x18\r \x03(\v2\x1e.capability.v1.SkillDefinitionR\x06skills\x12<\n" +
	"\factor_skills\x18\x0e \x03(\v2\x19.capability.v1.ActorSkillR\vactorSkills\x125\n" +
	"\adevices\x18\x0f \x03(\v2\x1b.resources.v1.DeviceMessageR\adevices\x123\n" +
	"\x06models\x18\x14 \x03(\v2\x1b.resources.v1.ModelArtifactR\x06models\x12J\n" +
	"\x11asset_definitions\x18\x1e \x03(\v2\x1d.resources.v1.AssetDefinitionR\x10assetDefinitions\x12D\n" +
	"\x0fasset_instances\x18\x1f \x03(\v2\x1b.resources.v1.AssetInstanceR\x0eassetInstances\x12V\n" +
	"\x15container_definitions\x18  \x03(\v2!.resources.v1.ContainerDefinitionR\x14containerDefinitions\x12P\n" +
	"\x13container_instances\x18! \x03(\v2\x1f.resources.v1.ContainerInstanceR\x12containerInstances\x12G\n" +
	"\x10tool_definitions\x18\" \x03(\v2\x1c.resources.v1.ToolDefinitionR\x0ftoolDefinitions\x12A\n" +
	"\x0etool_instances\x18# \x03(\v2\x1a.resources.v1.ToolInstanceR\rtoolInstances\x126\n" +
	"\amarkers\x18$ \x03(\v2\x1c.resources.v1.MarkerInstanceR\amarkers\x12E\n" +
	"\x10part_definitions\x18( \x03(\v2\x1a.product.v1.PartDefinitionR\x0fpartDefinitions\x12?\n" +
	"\x0epart_instances\x18) \x03(\v2\x18.product.v1.PartInstanceR\rpartInstances\x129\n" +
	"\bproducts\x18* \x03(\v2\x1d.product.v1.ProductDefinitionR\bproducts\x123\n" +
	"\arecipes\x18+ \x03(\v2\x19.process.v1.ProcessRecipeR\arecipes\x12<\n" +
	"\tsequences\x18, \x03(\v2\x1e.process.v1.SequenceDefinitionR\tsequences\x120\n" +
	"\x05tasks\x18- \x03(\v2\x1a.process.v1.TaskDefinitionR\x05tasks\x124\n" +
	"\tprocesses\x182 \x03(\v2\x16.runtime.v1.ProcessRunR\tprocesses\x12<\n" +
	"\rsequence_runs\x183 \x03(\v2\x17.runtime.v1.SequenceRunR\fsequenceRuns\x120\n" +
	"\ttask_runs\x184 \x03(\v2\x13.runtime.v1.TaskRunR\btaskRuns\x122\n" +
	"\bfeedback\x18< \x03(\v2\x16.ar.v1.FeedbackMessageR\bfeedback\x12.\n" +
	"\aactions\x18= \x03(\v2\x14.ar.v1.ActionMessageR\aactionsB\x93\x01\n" +
	"\vcom.seed.v1B\tSeedProtoP\x01Z3github.com/cobotar/protocol/messages/seed/v1;seedv1\xa2\x02\x03SXX\xaa\x02\x10Messages.Seed.V1\xca\x02\aSeed\\V1\xe2\x02\x13Seed\\V1\\GPBMetadata\xea\x02\bSeed::V1b\x06proto3"

var (
	file_seed_v1_seed_proto_rawDescOnce sync.Once
	file_seed_v1_seed_proto_rawDescData []byte
)

func file_seed_v1_seed_proto_rawDescGZIP() []byte {
	file_seed_v1_seed_proto_rawDescOnce.Do(func() {
		file_seed_v1_seed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_seed_v1_seed_proto_rawDesc), len(file_seed_v1_seed_proto_rawDesc)))
	})
	return file_seed_v1_seed_proto_rawDescData
}

var file_seed_v1_seed_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_seed_v1_seed_proto_goTypes = []any{
	(*Seed)(nil),                   // 0: seed.v1.Seed
	(*v1.LineDefinition)(nil),      // 1: resources.v1.LineDefinition
	(*v1.CellDefinition)(nil),      // 2: resources.v1.CellDefinition
	(*v1.StationDefinition)(nil),   // 3: resources.v1.StationDefinition
	(*v1.WorkerDefinition)(nil),    // 4: resources.v1.WorkerDefinition
	(*v1.RobotDefinition)(nil),     // 5: resources.v1.RobotDefinition
	(*v1.RobotInstance)(nil),       // 6: resources.v1.RobotInstance
	(*v11.SkillDefinition)(nil),    // 7: capability.v1.SkillDefinition
	(*v11.ActorSkill)(nil),         // 8: capability.v1.ActorSkill
	(*v1.DeviceMessage)(nil),       // 9: resources.v1.DeviceMessage
	(*v1.ModelArtifact)(nil),       // 10: resources.v1.ModelArtifact
	(*v1.AssetDefinition)(nil),     // 11: resources.v1.AssetDefinition
	(*v1.AssetInstance)(nil),       // 12: resources.v1.AssetInstance
	(*v1.ContainerDefinition)(nil), // 13: resources.v1.ContainerDefinition
	(*v1.ContainerInstance)(nil),   // 14: resources.v1.ContainerInstance
	(*v1.ToolDefinition)(nil),      // 15: resources.v1.ToolDefinition
	(*v1.ToolInstance)(nil),        // 16: resources.v1.ToolInstance
	(*v1.MarkerInstance)(nil),      // 17: resources.v1.MarkerInstance
	(*v12.PartDefinition)(nil),     // 18: product.v1.PartDefinition
	(*v12.PartInstance)(nil),       // 19: product.v1.PartInstance
	(*v12.ProductDefinition)(nil),  // 20: product.v1.ProductDefinition
	(*v13.ProcessRecipe)(nil),      // 21: process.v1.ProcessRecipe
	(*v13.SequenceDefinition)(nil), // 22: process.v1.SequenceDefinition
	(*v13.TaskDefinition)(nil),     // 23: process.v1.TaskDefinition
	(*v14.ProcessRun)(nil),         // 24: runtime.v1.ProcessRun
	(*v14.SequenceRun)(nil),        // 25: runtime.v1.SequenceRun
	(*v14.TaskRun)(nil),            // 26: runtime.v1.TaskRun
	(*v15.FeedbackMessage)(nil),    // 27: ar.v1.FeedbackMessage
	(*v15.ActionMessage)(nil),      // 28: ar.v1.ActionMessage
}
var file_seed_v1_seed_proto_depIdxs = []int32{
	1,  // 0: seed.v1.Seed.lines:type_name -> resources.v1.LineDefinition
	2,  // 1: seed.v1.Seed.cells:type_name -> resources.v1.CellDefinition
	3,  // 2: seed.v1.Seed.stations:type_name -> resources.v1.StationDefinition
	4,  // 3: seed.v1.Seed.workers:type_name -> resources.v1.WorkerDefinition
	5,  // 4: seed.v1.Seed.robot_definitions:type_name -> resources.v1.RobotDefinition
	6,  // 5: seed.v1.Seed.robot_instances:type_name -> resources.v1.RobotInstance
	7,  // 6: seed.v1.Seed.skills:type_name -> capability.v1.SkillDefinition
	8,  // 7: seed.v1.Seed.actor_skills:type_name -> capability.v1.ActorSkill
	9,  // 8: seed.v1.Seed.devices:type_name -> resources.v1.DeviceMessage
	10, // 9: seed.v1.Seed.models:type_name -> resources.v1.ModelArtifact
	11, // 10: seed.v1.Seed.asset_definitions:type_name -> resources.v1.AssetDefinition
	12, // 11: seed.v1.Seed.asset_instances:type_name -> resources.v1.AssetInstance
	13, // 12: seed.v1.Seed.container_definitions:type_name -> resources.v1.ContainerDefinition
	14, // 13: seed.v1.Seed.container_instances:type_name -> resources.v1.ContainerInstance
	15, // 14: seed.v1.Seed.tool_definitions:type_name -> resources.v1.ToolDefinition
	16, // 15: seed.v1.Seed.tool_instances:type_name -> resources.v1.ToolInstance
	17, // 16: seed.v1.Seed.markers:type_name -> resources.v1.MarkerInstance
	18, // 17: seed.v1.Seed.part_definitions:type_name -> product.v1.PartDefinition
	19, // 18: seed.v1.Seed.part_instances:type_name -> product.v1.PartInstance
	20, // 19: seed.v1.Seed.products:type_name -> product.v1.ProductDefinition
	21, // 20: seed.v1.Seed.recipes:type_name -> process.v1.ProcessRecipe
	22, // 21: seed.v1.Seed.sequences:type_name -> process.v1.SequenceDefinition
	23, // 22: seed.v1.Seed.tasks:type_name -> process.v1.TaskDefinition
	24, // 23: seed.v1.Seed.processes:type_name -> runtime.v1.ProcessRun
	25, // 24: seed.v1.Seed.sequence_runs:type_name -> runtime.v1.SequenceRun
	26, // 25: seed.v1.Seed.task_runs:type_name -> runtime.v1.TaskRun
	27, // 26: seed.v1.Seed.feedback:type_name -> ar.v1.FeedbackMessage
	28, // 27: seed.v1.Seed.actions:type_name -> ar.v1.ActionMessage
	28, // [28:28] is the sub-list for method output_type
	28, // [28:28] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_seed_v1_seed_proto_init() }
func file_seed_v1_seed_proto_init() {
	if File_seed_v1_seed_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_seed_v1_seed_proto_rawDesc), len(file_seed_v1_seed_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_seed_v1_seed_proto_goTypes,
		DependencyIndexes: file_seed_v1_seed_proto_depIdxs,
		MessageInfos:      file_seed_v1_seed_proto_msgTypes,
	}.Build()
	File_seed_v1_seed_proto = out.File
	file_seed_v1_seed_proto_goTypes = nil
	file_seed_v1_seed_proto_depIdxs = nil
}
