// @generated by protoc-gen-es v2.10.2 with parameter "target=ts,import_extension=ts"
// @generated from file assembly/v1/model.proto (package assembly.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { CustomProperties, ExternalReference } from "./common_pb.ts";
import { file_assembly_v1_common } from "./common_pb.ts";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file assembly/v1/model.proto.
 */
export const file_assembly_v1_model: GenFile = /*@__PURE__*/
  fileDesc("Chdhc3NlbWJseS92MS9tb2RlbC5wcm90bxILYXNzZW1ibHkudjEiiQMKDU1vZGVsQXJ0aWZhY3QSCgoCaWQYASABKAkSDAoEbmFtZRgCIAEoCRITCgtkZXNjcmlwdGlvbhgDIAEoCRIMCgRpY29uGAQgASgJEiYKBWdyb3VwGAUgASgOMhcuYXNzZW1ibHkudjEuTW9kZWxHcm91cBIoCgZvcmlnaW4YBiABKA4yGC5hc3NlbWJseS52MS5Nb2RlbE9yaWdpbhIoCgZmb3JtYXQYByABKA4yGC5hc3NlbWJseS52MS5Nb2RlbEZvcm1hdBIQCghmaWxlbmFtZRgIIAEoCRILCgN1cmkYCSABKAkSFQoNdGh1bWJuYWlsX3VyaRgKIAEoCRIPCgd2ZXJzaW9uGAsgASgJEgwKBHVuaXQYDCABKAkSOwoTZXh0ZXJuYWxfcmVmZXJlbmNlcxgNIAMoCzIeLmFzc2VtYmx5LnYxLkV4dGVybmFsUmVmZXJlbmNlEi0KBmN1c3RvbRgOIAEoCzIdLmFzc2VtYmx5LnYxLkN1c3RvbVByb3BlcnRpZXMiOwoOTW9kZWxBcnRpZmFjdHMSKQoFaXRlbXMYASADKAsyGi5hc3NlbWJseS52MS5Nb2RlbEFydGlmYWN0KrUBCgpNb2RlbEdyb3VwEhsKF01PREVMX0dST1VQX1VOU1BFQ0lGSUVEEAASFAoQTU9ERUxfR1JPVVBfUEFSVBABEhcKE01PREVMX0dST1VQX1BST0RVQ1QQAhIUChBNT0RFTF9HUk9VUF9UT09MEAMSFQoRTU9ERUxfR1JPVVBfUk9CT1QQBBIXChNNT0RFTF9HUk9VUF9GSVhUVVJFEAUSFQoRTU9ERUxfR1JPVVBfQVNTRVQQBip8CgtNb2RlbE9yaWdpbhIcChhNT0RFTF9PUklHSU5fVU5TUEVDSUZJRUQQABIZChVNT0RFTF9PUklHSU5fQlVJTFRfSU4QARIZChVNT0RFTF9PUklHSU5fVVBMT0FERUQQAhIZChVNT0RFTF9PUklHSU5fRVhURVJOQUwQAyqyAQoLTW9kZWxGb3JtYXQSHAoYTU9ERUxfRk9STUFUX1VOU1BFQ0lGSUVEEAASFAoQTU9ERUxfRk9STUFUX0dMQhABEhUKEU1PREVMX0ZPUk1BVF9HTFRGEAISFAoQTU9ERUxfRk9STUFUX09CShADEhUKEU1PREVMX0ZPUk1BVF9TVEVQEAQSFAoQTU9ERUxfRk9STUFUX1NUTBAFEhUKEU1PREVMX0ZPUk1BVF9VU0RaEAZCsAEKD2NvbS5hc3NlbWJseS52MUIKTW9kZWxQcm90b1ABWjtnaXRodWIuY29tL2NvYm90YXIvcHJvdG9jb2wvbWVzc2FnZXMvYXNzZW1ibHkvdjE7YXNzZW1ibHl2MaICA0FYWKoCFE1lc3NhZ2VzLkFzc2VtYmx5LlYxygILQXNzZW1ibHlcVjHiAhdBc3NlbWJseVxWMVxHUEJNZXRhZGF0YeoCDEFzc2VtYmx5OjpWMWIGcHJvdG8z", [file_assembly_v1_common]);

/**
 * @generated from message assembly.v1.ModelArtifact
 */
export type ModelArtifact = Message<"assembly.v1.ModelArtifact"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * @generated from field: string icon = 4;
   */
  icon: string;

  /**
   * @generated from field: assembly.v1.ModelGroup group = 5;
   */
  group: ModelGroup;

  /**
   * @generated from field: assembly.v1.ModelOrigin origin = 6;
   */
  origin: ModelOrigin;

  /**
   * @generated from field: assembly.v1.ModelFormat format = 7;
   */
  format: ModelFormat;

  /**
   * @generated from field: string filename = 8;
   */
  filename: string;

  /**
   * @generated from field: string uri = 9;
   */
  uri: string;

  /**
   * @generated from field: string thumbnail_uri = 10;
   */
  thumbnailUri: string;

  /**
   * @generated from field: string version = 11;
   */
  version: string;

  /**
   * @generated from field: string unit = 12;
   */
  unit: string;

  /**
   * @generated from field: repeated assembly.v1.ExternalReference external_references = 13;
   */
  externalReferences: ExternalReference[];

  /**
   * @generated from field: assembly.v1.CustomProperties custom = 14;
   */
  custom?: CustomProperties;
};

/**
 * Describes the message assembly.v1.ModelArtifact.
 * Use `create(ModelArtifactSchema)` to create a new message.
 */
export const ModelArtifactSchema: GenMessage<ModelArtifact> = /*@__PURE__*/
  messageDesc(file_assembly_v1_model, 0);

/**
 * @generated from message assembly.v1.ModelArtifacts
 */
export type ModelArtifacts = Message<"assembly.v1.ModelArtifacts"> & {
  /**
   * @generated from field: repeated assembly.v1.ModelArtifact items = 1;
   */
  items: ModelArtifact[];
};

/**
 * Describes the message assembly.v1.ModelArtifacts.
 * Use `create(ModelArtifactsSchema)` to create a new message.
 */
export const ModelArtifactsSchema: GenMessage<ModelArtifacts> = /*@__PURE__*/
  messageDesc(file_assembly_v1_model, 1);

/**
 * @generated from enum assembly.v1.ModelGroup
 */
export enum ModelGroup {
  /**
   * @generated from enum value: MODEL_GROUP_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: MODEL_GROUP_PART = 1;
   */
  PART = 1,

  /**
   * @generated from enum value: MODEL_GROUP_PRODUCT = 2;
   */
  PRODUCT = 2,

  /**
   * @generated from enum value: MODEL_GROUP_TOOL = 3;
   */
  TOOL = 3,

  /**
   * @generated from enum value: MODEL_GROUP_ROBOT = 4;
   */
  ROBOT = 4,

  /**
   * @generated from enum value: MODEL_GROUP_FIXTURE = 5;
   */
  FIXTURE = 5,

  /**
   * @generated from enum value: MODEL_GROUP_ASSET = 6;
   */
  ASSET = 6,
}

/**
 * Describes the enum assembly.v1.ModelGroup.
 */
export const ModelGroupSchema: GenEnum<ModelGroup> = /*@__PURE__*/
  enumDesc(file_assembly_v1_model, 0);

/**
 * @generated from enum assembly.v1.ModelOrigin
 */
export enum ModelOrigin {
  /**
   * @generated from enum value: MODEL_ORIGIN_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: MODEL_ORIGIN_BUILT_IN = 1;
   */
  BUILT_IN = 1,

  /**
   * @generated from enum value: MODEL_ORIGIN_UPLOADED = 2;
   */
  UPLOADED = 2,

  /**
   * @generated from enum value: MODEL_ORIGIN_EXTERNAL = 3;
   */
  EXTERNAL = 3,
}

/**
 * Describes the enum assembly.v1.ModelOrigin.
 */
export const ModelOriginSchema: GenEnum<ModelOrigin> = /*@__PURE__*/
  enumDesc(file_assembly_v1_model, 1);

/**
 * @generated from enum assembly.v1.ModelFormat
 */
export enum ModelFormat {
  /**
   * @generated from enum value: MODEL_FORMAT_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: MODEL_FORMAT_GLB = 1;
   */
  GLB = 1,

  /**
   * @generated from enum value: MODEL_FORMAT_GLTF = 2;
   */
  GLTF = 2,

  /**
   * @generated from enum value: MODEL_FORMAT_OBJ = 3;
   */
  OBJ = 3,

  /**
   * @generated from enum value: MODEL_FORMAT_STEP = 4;
   */
  STEP = 4,

  /**
   * @generated from enum value: MODEL_FORMAT_STL = 5;
   */
  STL = 5,

  /**
   * @generated from enum value: MODEL_FORMAT_USDZ = 6;
   */
  USDZ = 6,
}

/**
 * Describes the enum assembly.v1.ModelFormat.
 */
export const ModelFormatSchema: GenEnum<ModelFormat> = /*@__PURE__*/
  enumDesc(file_assembly_v1_model, 2);

