// @generated by protoc-gen-es v2.10.2 with parameter "target=ts,import_extension=ts"
// @generated from file robot/v1/jointstate.proto (package robot.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file robot/v1/jointstate.proto.
 */
export const file_robot_v1_jointstate: GenFile = /*@__PURE__*/
  fileDesc("Chlyb2JvdC92MS9qb2ludHN0YXRlLnByb3RvEghyb2JvdC52MSJXChFKb2ludFN0YXRlTWVzc2FnZRIQCghyb2JvdF9pZBgBIAEoCRIMCgRsaXZlGAIgASgIEhAKCHBvc2l0aW9uGAMgAygBEhAKCHZlbG9jaXR5GAQgAygBQqABCgxjb20ucm9ib3QudjFCD0pvaW50c3RhdGVQcm90b1ABWjVnaXRodWIuY29tL2NvYm90YXIvcHJvdG9jb2wvbWVzc2FnZXMvcm9ib3QvdjE7cm9ib3R2MaICA1JYWKoCEU1lc3NhZ2VzLlJvYm90LlYxygIIUm9ib3RcVjHiAhRSb2JvdFxWMVxHUEJNZXRhZGF0YeoCCVJvYm90OjpWMWIGcHJvdG8z");

/**
 * @generated from message robot.v1.JointStateMessage
 */
export type JointStateMessage = Message<"robot.v1.JointStateMessage"> & {
  /**
   * @generated from field: string robot_id = 1;
   */
  robotId: string;

  /**
   * @generated from field: bool live = 2;
   */
  live: boolean;

  /**
   * @generated from field: repeated double position = 3;
   */
  position: number[];

  /**
   * @generated from field: repeated double velocity = 4;
   */
  velocity: number[];
};

/**
 * Describes the message robot.v1.JointStateMessage.
 * Use `create(JointStateMessageSchema)` to create a new message.
 */
export const JointStateMessageSchema: GenMessage<JointStateMessage> = /*@__PURE__*/
  messageDesc(file_robot_v1_jointstate, 0);

