// @generated by protoc-gen-es v2.10.2 with parameter "target=ts,import_extension=ts"
// @generated from file runtime/v1/runtime_requests.proto (package runtime.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ActorRef } from "../../common/v1/actor_pb.ts";
import { file_common_v1_actor } from "../../common/v1/actor_pb.ts";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file runtime/v1/runtime_requests.proto.
 */
export const file_runtime_v1_runtime_requests: GenFile = /*@__PURE__*/
  fileDesc("CiFydW50aW1lL3YxL3J1bnRpbWVfcmVxdWVzdHMucHJvdG8SCnJ1bnRpbWUudjEiPQoTUHJvY2Vzc0Fib3J0UmVxdWVzdBIWCg5wcm9jZXNzX3J1bl9pZBgBIAEoCRIOCgZyZWFzb24YAiABKAkiWgoWVGFza1N0YXRlQ2hhbmdlUmVxdWVzdBITCgt0YXNrX3J1bl9pZBgBIAEoCRIrCgVzdGF0ZRgCIAEoDjIcLnJ1bnRpbWUudjEuVGFza1N0YXRlUmVxdWVzdCJOChNUYXNrUmVhc3NpZ25SZXF1ZXN0EhMKC3Rhc2tfcnVuX2lkGAEgASgJEiIKBWFjdG9yGAIgASgLMhMuY29tbW9uLnYxLkFjdG9yUmVmIpEBChJUYXNrUHJvZ3Jlc3NVcGRhdGUSEwoLdGFza19ydW5faWQYASABKAkSIgoFYWN0b3IYAiABKAsyEy5jb21tb24udjEuQWN0b3JSZWYSDwoHbWVzc2FnZRgDIAEoCRIUCgxlbGFwc2VkX3RpbWUYBCABKAUSGwoTZXN0aW1hdGVkX3RpbWVfbGVmdBgFIAEoBSrQAQoQVGFza1N0YXRlUmVxdWVzdBIiCh5UQVNLX1NUQVRFX1JFUVVFU1RfVU5TUEVDSUZJRUQQABIiCh5UQVNLX1NUQVRFX1JFUVVFU1RfSU5fUFJPR1JFU1MQARIbChdUQVNLX1NUQVRFX1JFUVVFU1RfRE9ORRACEhsKF1RBU0tfU1RBVEVfUkVRVUVTVF9VTkRPEAMSHAoYVEFTS19TVEFURV9SRVFVRVNUX0VSUk9SEAQSHAoYVEFTS19TVEFURV9SRVFVRVNUX0FCT1JUEAVCswEKDmNvbS5ydW50aW1lLnYxQhRSdW50aW1lUmVxdWVzdHNQcm90b1ABWjlnaXRodWIuY29tL2NvYm90YXIvcHJvdG9jb2wvbWVzc2FnZXMvcnVudGltZS92MTtydW50aW1ldjGiAgNSWFiqAhNNZXNzYWdlcy5SdW50aW1lLlYxygIKUnVudGltZVxWMeICFlJ1bnRpbWVcVjFcR1BCTWV0YWRhdGHqAgtSdW50aW1lOjpWMWIGcHJvdG8z", [file_common_v1_actor]);

/**
 * @generated from message runtime.v1.ProcessAbortRequest
 */
export type ProcessAbortRequest = Message<"runtime.v1.ProcessAbortRequest"> & {
  /**
   * @generated from field: string process_run_id = 1;
   */
  processRunId: string;

  /**
   * @generated from field: string reason = 2;
   */
  reason: string;
};

/**
 * Describes the message runtime.v1.ProcessAbortRequest.
 * Use `create(ProcessAbortRequestSchema)` to create a new message.
 */
export const ProcessAbortRequestSchema: GenMessage<ProcessAbortRequest> = /*@__PURE__*/
  messageDesc(file_runtime_v1_runtime_requests, 0);

/**
 * @generated from message runtime.v1.TaskStateChangeRequest
 */
export type TaskStateChangeRequest = Message<"runtime.v1.TaskStateChangeRequest"> & {
  /**
   * @generated from field: string task_run_id = 1;
   */
  taskRunId: string;

  /**
   * @generated from field: runtime.v1.TaskStateRequest state = 2;
   */
  state: TaskStateRequest;
};

/**
 * Describes the message runtime.v1.TaskStateChangeRequest.
 * Use `create(TaskStateChangeRequestSchema)` to create a new message.
 */
export const TaskStateChangeRequestSchema: GenMessage<TaskStateChangeRequest> = /*@__PURE__*/
  messageDesc(file_runtime_v1_runtime_requests, 1);

/**
 * @generated from message runtime.v1.TaskReassignRequest
 */
export type TaskReassignRequest = Message<"runtime.v1.TaskReassignRequest"> & {
  /**
   * @generated from field: string task_run_id = 1;
   */
  taskRunId: string;

  /**
   * @generated from field: common.v1.ActorRef actor = 2;
   */
  actor?: ActorRef;
};

/**
 * Describes the message runtime.v1.TaskReassignRequest.
 * Use `create(TaskReassignRequestSchema)` to create a new message.
 */
export const TaskReassignRequestSchema: GenMessage<TaskReassignRequest> = /*@__PURE__*/
  messageDesc(file_runtime_v1_runtime_requests, 2);

/**
 * @generated from message runtime.v1.TaskProgressUpdate
 */
export type TaskProgressUpdate = Message<"runtime.v1.TaskProgressUpdate"> & {
  /**
   * @generated from field: string task_run_id = 1;
   */
  taskRunId: string;

  /**
   * @generated from field: common.v1.ActorRef actor = 2;
   */
  actor?: ActorRef;

  /**
   * @generated from field: string message = 3;
   */
  message: string;

  /**
   * elapsed time in seconds
   *
   * @generated from field: int32 elapsed_time = 4;
   */
  elapsedTime: number;

  /**
   * estimated time left in seconds
   *
   * @generated from field: int32 estimated_time_left = 5;
   */
  estimatedTimeLeft: number;
};

/**
 * Describes the message runtime.v1.TaskProgressUpdate.
 * Use `create(TaskProgressUpdateSchema)` to create a new message.
 */
export const TaskProgressUpdateSchema: GenMessage<TaskProgressUpdate> = /*@__PURE__*/
  messageDesc(file_runtime_v1_runtime_requests, 3);

/**
 * @generated from enum runtime.v1.TaskStateRequest
 */
export enum TaskStateRequest {
  /**
   * @generated from enum value: TASK_STATE_REQUEST_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: TASK_STATE_REQUEST_IN_PROGRESS = 1;
   */
  IN_PROGRESS = 1,

  /**
   * @generated from enum value: TASK_STATE_REQUEST_DONE = 2;
   */
  DONE = 2,

  /**
   * @generated from enum value: TASK_STATE_REQUEST_UNDO = 3;
   */
  UNDO = 3,

  /**
   * @generated from enum value: TASK_STATE_REQUEST_ERROR = 4;
   */
  ERROR = 4,

  /**
   * @generated from enum value: TASK_STATE_REQUEST_ABORT = 5;
   */
  ABORT = 5,
}

/**
 * Describes the enum runtime.v1.TaskStateRequest.
 */
export const TaskStateRequestSchema: GenEnum<TaskStateRequest> = /*@__PURE__*/
  enumDesc(file_runtime_v1_runtime_requests, 0);

