// @generated by protoc-gen-es v2.10.2 with parameter "target=ts,import_extension=ts"
// @generated from file runtime/v1/sequence_run.proto (package runtime.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb.ts";
import type { ActorRef } from "../../common/v1/actor_pb.ts";
import { file_common_v1_actor } from "../../common/v1/actor_pb.ts";
import { file_validation_v1_predefined_string_rules } from "../../validation/v1/predefined_string_rules_pb.ts";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file runtime/v1/sequence_run.proto.
 */
export const file_runtime_v1_sequence_run: GenFile = /*@__PURE__*/
  fileDesc("Ch1ydW50aW1lL3YxL3NlcXVlbmNlX3J1bi5wcm90bxIKcnVudGltZS52MSLvAgoLU2VxdWVuY2VSdW4SCgoCaWQYASABKAkSDAoEbmFtZRgCIAEoCRIMCgRpY29uGAMgASgJEiwKFnNlcXVlbmNlX2RlZmluaXRpb25faWQYBCABKAlCDLpICcgBAXIEkPIEARIpChZwYXJlbnRfc2VxdWVuY2VfcnVuX2lkGAUgASgJQgm6SAZyBIDyBAESHgoWY2hpbGRfc2VxdWVuY2VfcnVuX2lkcxgGIAMoCRIaChJjaGlsZF90YXNrX3J1bl9pZHMYByADKAkSOAoFc3RhdGUYCCABKA4yHC5ydW50aW1lLnYxLlNlcXVlbmNlUnVuU3RhdGVCC7pICMgBAYIBAhABEiAKD2NvbXBsZXRlZF90YXNrcxgJIAEoBUIHukgEGgIoABIZChFjYW5fYnVsa19jb21wbGV0ZRgKIAEoCBIsCg9hc3NpZ25lZF9hY3RvcnMYCyADKAsyEy5jb21tb24udjEuQWN0b3JSZWYiNgoMU2VxdWVuY2VSdW5zEiYKBWl0ZW1zGAEgAygLMhcucnVudGltZS52MS5TZXF1ZW5jZVJ1birXAQoQU2VxdWVuY2VSdW5TdGF0ZRIiCh5TRVFVRU5DRV9SVU5fU1RBVEVfVU5TUEVDSUZJRUQQABIgChxTRVFVRU5DRV9SVU5fU1RBVEVfTk9UX1JFQURZEAESHAoYU0VRVUVOQ0VfUlVOX1NUQVRFX1JFQURZEAISIgoeU0VRVUVOQ0VfUlVOX1NUQVRFX0lOX1BST0dSRVNTEAMSGwoXU0VRVUVOQ0VfUlVOX1NUQVRFX0RPTkUQBBIeChpTRVFVRU5DRV9SVU5fU1RBVEVfQUJPUlRFRBAFQq8BCg5jb20ucnVudGltZS52MUIQU2VxdWVuY2VSdW5Qcm90b1ABWjlnaXRodWIuY29tL2NvYm90YXIvcHJvdG9jb2wvbWVzc2FnZXMvcnVudGltZS92MTtydW50aW1ldjGiAgNSWFiqAhNNZXNzYWdlcy5SdW50aW1lLlYxygIKUnVudGltZVxWMeICFlJ1bnRpbWVcVjFcR1BCTWV0YWRhdGHqAgtSdW50aW1lOjpWMWIGcHJvdG8z", [file_buf_validate_validate, file_common_v1_actor, file_validation_v1_predefined_string_rules]);

/**
 * @generated from message runtime.v1.SequenceRun
 */
export type SequenceRun = Message<"runtime.v1.SequenceRun"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string icon = 3;
   */
  icon: string;

  /**
   * @generated from field: string sequence_definition_id = 4;
   */
  sequenceDefinitionId: string;

  /**
   * @generated from field: string parent_sequence_run_id = 5;
   */
  parentSequenceRunId: string;

  /**
   * @generated from field: repeated string child_sequence_run_ids = 6;
   */
  childSequenceRunIds: string[];

  /**
   * @generated from field: repeated string child_task_run_ids = 7;
   */
  childTaskRunIds: string[];

  /**
   * @generated from field: runtime.v1.SequenceRunState state = 8;
   */
  state: SequenceRunState;

  /**
   * @generated from field: int32 completed_tasks = 9;
   */
  completedTasks: number;

  /**
   * @generated from field: bool can_bulk_complete = 10;
   */
  canBulkComplete: boolean;

  /**
   * @generated from field: repeated common.v1.ActorRef assigned_actors = 11;
   */
  assignedActors: ActorRef[];
};

/**
 * Describes the message runtime.v1.SequenceRun.
 * Use `create(SequenceRunSchema)` to create a new message.
 */
export const SequenceRunSchema: GenMessage<SequenceRun> = /*@__PURE__*/
  messageDesc(file_runtime_v1_sequence_run, 0);

/**
 * @generated from message runtime.v1.SequenceRuns
 */
export type SequenceRuns = Message<"runtime.v1.SequenceRuns"> & {
  /**
   * @generated from field: repeated runtime.v1.SequenceRun items = 1;
   */
  items: SequenceRun[];
};

/**
 * Describes the message runtime.v1.SequenceRuns.
 * Use `create(SequenceRunsSchema)` to create a new message.
 */
export const SequenceRunsSchema: GenMessage<SequenceRuns> = /*@__PURE__*/
  messageDesc(file_runtime_v1_sequence_run, 1);

/**
 * @generated from enum runtime.v1.SequenceRunState
 */
export enum SequenceRunState {
  /**
   * @generated from enum value: SEQUENCE_RUN_STATE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: SEQUENCE_RUN_STATE_NOT_READY = 1;
   */
  NOT_READY = 1,

  /**
   * @generated from enum value: SEQUENCE_RUN_STATE_READY = 2;
   */
  READY = 2,

  /**
   * @generated from enum value: SEQUENCE_RUN_STATE_IN_PROGRESS = 3;
   */
  IN_PROGRESS = 3,

  /**
   * @generated from enum value: SEQUENCE_RUN_STATE_DONE = 4;
   */
  DONE = 4,

  /**
   * @generated from enum value: SEQUENCE_RUN_STATE_ABORTED = 5;
   */
  ABORTED = 5,
}

/**
 * Describes the enum runtime.v1.SequenceRunState.
 */
export const SequenceRunStateSchema: GenEnum<SequenceRunState> = /*@__PURE__*/
  enumDesc(file_runtime_v1_sequence_run, 0);

