// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: assembly/v1/common.proto

package assemblyv1

import (
	v11 "github.com/cobotar/protocol/messages/ar/v1"
	v1 "github.com/cobotar/protocol/messages/geometry/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActorKind int32

const (
	ActorKind_ACTOR_KIND_UNSPECIFIED ActorKind = 0
	ActorKind_ACTOR_KIND_HUMAN       ActorKind = 1
	ActorKind_ACTOR_KIND_ROBOT       ActorKind = 2
	ActorKind_ACTOR_KIND_HYBRID      ActorKind = 3
)

// Enum value maps for ActorKind.
var (
	ActorKind_name = map[int32]string{
		0: "ACTOR_KIND_UNSPECIFIED",
		1: "ACTOR_KIND_HUMAN",
		2: "ACTOR_KIND_ROBOT",
		3: "ACTOR_KIND_HYBRID",
	}
	ActorKind_value = map[string]int32{
		"ACTOR_KIND_UNSPECIFIED": 0,
		"ACTOR_KIND_HUMAN":       1,
		"ACTOR_KIND_ROBOT":       2,
		"ACTOR_KIND_HYBRID":      3,
	}
)

func (x ActorKind) Enum() *ActorKind {
	p := new(ActorKind)
	*p = x
	return p
}

func (x ActorKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActorKind) Descriptor() protoreflect.EnumDescriptor {
	return file_assembly_v1_common_proto_enumTypes[0].Descriptor()
}

func (ActorKind) Type() protoreflect.EnumType {
	return &file_assembly_v1_common_proto_enumTypes[0]
}

func (x ActorKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActorKind.Descriptor instead.
func (ActorKind) EnumDescriptor() ([]byte, []int) {
	return file_assembly_v1_common_proto_rawDescGZIP(), []int{0}
}

type ResourceStatus int32

const (
	ResourceStatus_RESOURCE_STATUS_UNSPECIFIED ResourceStatus = 0
	ResourceStatus_RESOURCE_STATUS_AVAILABLE   ResourceStatus = 1
	ResourceStatus_RESOURCE_STATUS_UNAVAILABLE ResourceStatus = 2
	ResourceStatus_RESOURCE_STATUS_DISABLED    ResourceStatus = 3
	ResourceStatus_RESOURCE_STATUS_MAINTENANCE ResourceStatus = 4
)

// Enum value maps for ResourceStatus.
var (
	ResourceStatus_name = map[int32]string{
		0: "RESOURCE_STATUS_UNSPECIFIED",
		1: "RESOURCE_STATUS_AVAILABLE",
		2: "RESOURCE_STATUS_UNAVAILABLE",
		3: "RESOURCE_STATUS_DISABLED",
		4: "RESOURCE_STATUS_MAINTENANCE",
	}
	ResourceStatus_value = map[string]int32{
		"RESOURCE_STATUS_UNSPECIFIED": 0,
		"RESOURCE_STATUS_AVAILABLE":   1,
		"RESOURCE_STATUS_UNAVAILABLE": 2,
		"RESOURCE_STATUS_DISABLED":    3,
		"RESOURCE_STATUS_MAINTENANCE": 4,
	}
)

func (x ResourceStatus) Enum() *ResourceStatus {
	p := new(ResourceStatus)
	*p = x
	return p
}

func (x ResourceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResourceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_assembly_v1_common_proto_enumTypes[1].Descriptor()
}

func (ResourceStatus) Type() protoreflect.EnumType {
	return &file_assembly_v1_common_proto_enumTypes[1]
}

func (x ResourceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResourceStatus.Descriptor instead.
func (ResourceStatus) EnumDescriptor() ([]byte, []int) {
	return file_assembly_v1_common_proto_rawDescGZIP(), []int{1}
}

type SafetyRelevance int32

const (
	SafetyRelevance_SAFETY_RELEVANCE_UNSPECIFIED SafetyRelevance = 0
	SafetyRelevance_SAFETY_RELEVANCE_LOW         SafetyRelevance = 1
	SafetyRelevance_SAFETY_RELEVANCE_MEDIUM      SafetyRelevance = 2
	SafetyRelevance_SAFETY_RELEVANCE_HIGH        SafetyRelevance = 3
	SafetyRelevance_SAFETY_RELEVANCE_CRITICAL    SafetyRelevance = 4
)

// Enum value maps for SafetyRelevance.
var (
	SafetyRelevance_name = map[int32]string{
		0: "SAFETY_RELEVANCE_UNSPECIFIED",
		1: "SAFETY_RELEVANCE_LOW",
		2: "SAFETY_RELEVANCE_MEDIUM",
		3: "SAFETY_RELEVANCE_HIGH",
		4: "SAFETY_RELEVANCE_CRITICAL",
	}
	SafetyRelevance_value = map[string]int32{
		"SAFETY_RELEVANCE_UNSPECIFIED": 0,
		"SAFETY_RELEVANCE_LOW":         1,
		"SAFETY_RELEVANCE_MEDIUM":      2,
		"SAFETY_RELEVANCE_HIGH":        3,
		"SAFETY_RELEVANCE_CRITICAL":    4,
	}
)

func (x SafetyRelevance) Enum() *SafetyRelevance {
	p := new(SafetyRelevance)
	*p = x
	return p
}

func (x SafetyRelevance) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SafetyRelevance) Descriptor() protoreflect.EnumDescriptor {
	return file_assembly_v1_common_proto_enumTypes[2].Descriptor()
}

func (SafetyRelevance) Type() protoreflect.EnumType {
	return &file_assembly_v1_common_proto_enumTypes[2]
}

func (x SafetyRelevance) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SafetyRelevance.Descriptor instead.
func (SafetyRelevance) EnumDescriptor() ([]byte, []int) {
	return file_assembly_v1_common_proto_rawDescGZIP(), []int{2}
}

type CollaborationMode int32

const (
	CollaborationMode_COLLABORATION_MODE_UNSPECIFIED      CollaborationMode = 0
	CollaborationMode_COLLABORATION_MODE_HUMAN_ONLY       CollaborationMode = 1
	CollaborationMode_COLLABORATION_MODE_ROBOT_ONLY       CollaborationMode = 2
	CollaborationMode_COLLABORATION_MODE_SEQUENTIAL_HRC   CollaborationMode = 3
	CollaborationMode_COLLABORATION_MODE_SIMULTANEOUS_HRC CollaborationMode = 4
)

// Enum value maps for CollaborationMode.
var (
	CollaborationMode_name = map[int32]string{
		0: "COLLABORATION_MODE_UNSPECIFIED",
		1: "COLLABORATION_MODE_HUMAN_ONLY",
		2: "COLLABORATION_MODE_ROBOT_ONLY",
		3: "COLLABORATION_MODE_SEQUENTIAL_HRC",
		4: "COLLABORATION_MODE_SIMULTANEOUS_HRC",
	}
	CollaborationMode_value = map[string]int32{
		"COLLABORATION_MODE_UNSPECIFIED":      0,
		"COLLABORATION_MODE_HUMAN_ONLY":       1,
		"COLLABORATION_MODE_ROBOT_ONLY":       2,
		"COLLABORATION_MODE_SEQUENTIAL_HRC":   3,
		"COLLABORATION_MODE_SIMULTANEOUS_HRC": 4,
	}
)

func (x CollaborationMode) Enum() *CollaborationMode {
	p := new(CollaborationMode)
	*p = x
	return p
}

func (x CollaborationMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CollaborationMode) Descriptor() protoreflect.EnumDescriptor {
	return file_assembly_v1_common_proto_enumTypes[3].Descriptor()
}

func (CollaborationMode) Type() protoreflect.EnumType {
	return &file_assembly_v1_common_proto_enumTypes[3]
}

func (x CollaborationMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CollaborationMode.Descriptor instead.
func (CollaborationMode) EnumDescriptor() ([]byte, []int) {
	return file_assembly_v1_common_proto_rawDescGZIP(), []int{3}
}

type ConstraintOperator int32

const (
	ConstraintOperator_CONSTRAINT_OPERATOR_UNSPECIFIED ConstraintOperator = 0
	ConstraintOperator_CONSTRAINT_OPERATOR_EQ          ConstraintOperator = 1
	ConstraintOperator_CONSTRAINT_OPERATOR_NEQ         ConstraintOperator = 2
	ConstraintOperator_CONSTRAINT_OPERATOR_GT          ConstraintOperator = 3
	ConstraintOperator_CONSTRAINT_OPERATOR_GTE         ConstraintOperator = 4
	ConstraintOperator_CONSTRAINT_OPERATOR_LT          ConstraintOperator = 5
	ConstraintOperator_CONSTRAINT_OPERATOR_LTE         ConstraintOperator = 6
	ConstraintOperator_CONSTRAINT_OPERATOR_IN          ConstraintOperator = 7
	ConstraintOperator_CONSTRAINT_OPERATOR_NOT_IN      ConstraintOperator = 8
)

// Enum value maps for ConstraintOperator.
var (
	ConstraintOperator_name = map[int32]string{
		0: "CONSTRAINT_OPERATOR_UNSPECIFIED",
		1: "CONSTRAINT_OPERATOR_EQ",
		2: "CONSTRAINT_OPERATOR_NEQ",
		3: "CONSTRAINT_OPERATOR_GT",
		4: "CONSTRAINT_OPERATOR_GTE",
		5: "CONSTRAINT_OPERATOR_LT",
		6: "CONSTRAINT_OPERATOR_LTE",
		7: "CONSTRAINT_OPERATOR_IN",
		8: "CONSTRAINT_OPERATOR_NOT_IN",
	}
	ConstraintOperator_value = map[string]int32{
		"CONSTRAINT_OPERATOR_UNSPECIFIED": 0,
		"CONSTRAINT_OPERATOR_EQ":          1,
		"CONSTRAINT_OPERATOR_NEQ":         2,
		"CONSTRAINT_OPERATOR_GT":          3,
		"CONSTRAINT_OPERATOR_GTE":         4,
		"CONSTRAINT_OPERATOR_LT":          5,
		"CONSTRAINT_OPERATOR_LTE":         6,
		"CONSTRAINT_OPERATOR_IN":          7,
		"CONSTRAINT_OPERATOR_NOT_IN":      8,
	}
)

func (x ConstraintOperator) Enum() *ConstraintOperator {
	p := new(ConstraintOperator)
	*p = x
	return p
}

func (x ConstraintOperator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConstraintOperator) Descriptor() protoreflect.EnumDescriptor {
	return file_assembly_v1_common_proto_enumTypes[4].Descriptor()
}

func (ConstraintOperator) Type() protoreflect.EnumType {
	return &file_assembly_v1_common_proto_enumTypes[4]
}

func (x ConstraintOperator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConstraintOperator.Descriptor instead.
func (ConstraintOperator) EnumDescriptor() ([]byte, []int) {
	return file_assembly_v1_common_proto_rawDescGZIP(), []int{4}
}

type Ref struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ref) Reset() {
	*x = Ref{}
	mi := &file_assembly_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ref) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ref) ProtoMessage() {}

func (x *Ref) ProtoReflect() protoreflect.Message {
	mi := &file_assembly_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ref.ProtoReflect.Descriptor instead.
func (*Ref) Descriptor() ([]byte, []int) {
	return file_assembly_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *Ref) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type NamedRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamedRef) Reset() {
	*x = NamedRef{}
	mi := &file_assembly_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamedRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamedRef) ProtoMessage() {}

func (x *NamedRef) ProtoReflect() protoreflect.Message {
	mi := &file_assembly_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamedRef.ProtoReflect.Descriptor instead.
func (*NamedRef) Descriptor() ([]byte, []int) {
	return file_assembly_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *NamedRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NamedRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type KeyValueConstraint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Op            ConstraintOperator     `protobuf:"varint,2,opt,name=op,proto3,enum=assembly.v1.ConstraintOperator" json:"op,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Values        []string               `protobuf:"bytes,4,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValueConstraint) Reset() {
	*x = KeyValueConstraint{}
	mi := &file_assembly_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValueConstraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValueConstraint) ProtoMessage() {}

func (x *KeyValueConstraint) ProtoReflect() protoreflect.Message {
	mi := &file_assembly_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValueConstraint.ProtoReflect.Descriptor instead.
func (*KeyValueConstraint) Descriptor() ([]byte, []int) {
	return file_assembly_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *KeyValueConstraint) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValueConstraint) GetOp() ConstraintOperator {
	if x != nil {
		return x.Op
	}
	return ConstraintOperator_CONSTRAINT_OPERATOR_UNSPECIFIED
}

func (x *KeyValueConstraint) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *KeyValueConstraint) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type TimeWindow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeWindow) Reset() {
	*x = TimeWindow{}
	mi := &file_assembly_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeWindow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeWindow) ProtoMessage() {}

func (x *TimeWindow) ProtoReflect() protoreflect.Message {
	mi := &file_assembly_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeWindow.ProtoReflect.Descriptor instead.
func (*TimeWindow) Descriptor() ([]byte, []int) {
	return file_assembly_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *TimeWindow) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *TimeWindow) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

type LocalTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AnchorId      string                 `protobuf:"bytes,1,opt,name=anchor_id,json=anchorId,proto3" json:"anchor_id,omitempty"`
	Offset        *v1.Pose               `protobuf:"bytes,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalTarget) Reset() {
	*x = LocalTarget{}
	mi := &file_assembly_v1_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalTarget) ProtoMessage() {}

func (x *LocalTarget) ProtoReflect() protoreflect.Message {
	mi := &file_assembly_v1_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalTarget.ProtoReflect.Descriptor instead.
func (*LocalTarget) Descriptor() ([]byte, []int) {
	return file_assembly_v1_common_proto_rawDescGZIP(), []int{4}
}

func (x *LocalTarget) GetAnchorId() string {
	if x != nil {
		return x.AnchorId
	}
	return ""
}

func (x *LocalTarget) GetOffset() *v1.Pose {
	if x != nil {
		return x.Offset
	}
	return nil
}

type EstimatedDuration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nominal       *durationpb.Duration   `protobuf:"bytes,1,opt,name=nominal,proto3" json:"nominal,omitempty"`
	Min           *durationpb.Duration   `protobuf:"bytes,2,opt,name=min,proto3" json:"min,omitempty"`
	Max           *durationpb.Duration   `protobuf:"bytes,3,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EstimatedDuration) Reset() {
	*x = EstimatedDuration{}
	mi := &file_assembly_v1_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstimatedDuration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstimatedDuration) ProtoMessage() {}

func (x *EstimatedDuration) ProtoReflect() protoreflect.Message {
	mi := &file_assembly_v1_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstimatedDuration.ProtoReflect.Descriptor instead.
func (*EstimatedDuration) Descriptor() ([]byte, []int) {
	return file_assembly_v1_common_proto_rawDescGZIP(), []int{5}
}

func (x *EstimatedDuration) GetNominal() *durationpb.Duration {
	if x != nil {
		return x.Nominal
	}
	return nil
}

func (x *EstimatedDuration) GetMin() *durationpb.Duration {
	if x != nil {
		return x.Min
	}
	return nil
}

func (x *EstimatedDuration) GetMax() *durationpb.Duration {
	if x != nil {
		return x.Max
	}
	return nil
}

type DisplayText struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Title               string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description         string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	OperatorInstruction string                 `protobuf:"bytes,3,opt,name=operator_instruction,json=operatorInstruction,proto3" json:"operator_instruction,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DisplayText) Reset() {
	*x = DisplayText{}
	mi := &file_assembly_v1_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisplayText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisplayText) ProtoMessage() {}

func (x *DisplayText) ProtoReflect() protoreflect.Message {
	mi := &file_assembly_v1_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisplayText.ProtoReflect.Descriptor instead.
func (*DisplayText) Descriptor() ([]byte, []int) {
	return file_assembly_v1_common_proto_rawDescGZIP(), []int{6}
}

func (x *DisplayText) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DisplayText) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DisplayText) GetOperatorInstruction() string {
	if x != nil {
		return x.OperatorInstruction
	}
	return ""
}

type ExternalReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	System        string                 `protobuf:"bytes,1,opt,name=system,proto3" json:"system,omitempty"`
	ExternalId    string                 `protobuf:"bytes,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalReference) Reset() {
	*x = ExternalReference{}
	mi := &file_assembly_v1_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalReference) ProtoMessage() {}

func (x *ExternalReference) ProtoReflect() protoreflect.Message {
	mi := &file_assembly_v1_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalReference.ProtoReflect.Descriptor instead.
func (*ExternalReference) Descriptor() ([]byte, []int) {
	return file_assembly_v1_common_proto_rawDescGZIP(), []int{7}
}

func (x *ExternalReference) GetSystem() string {
	if x != nil {
		return x.System
	}
	return ""
}

func (x *ExternalReference) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *ExternalReference) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type CustomProperties struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Properties    []*v11.Property        `protobuf:"bytes,1,rep,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomProperties) Reset() {
	*x = CustomProperties{}
	mi := &file_assembly_v1_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomProperties) ProtoMessage() {}

func (x *CustomProperties) ProtoReflect() protoreflect.Message {
	mi := &file_assembly_v1_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomProperties.ProtoReflect.Descriptor instead.
func (*CustomProperties) Descriptor() ([]byte, []int) {
	return file_assembly_v1_common_proto_rawDescGZIP(), []int{8}
}

func (x *CustomProperties) GetProperties() []*v11.Property {
	if x != nil {
		return x.Properties
	}
	return nil
}

var File_assembly_v1_common_proto protoreflect.FileDescriptor

const file_assembly_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x18assembly/v1/common.proto\x12\vassembly.v1\x1a\x14ar/v1/property.proto\x1a\x16geometry/v1/pose.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x15\n" +
	"\x03Ref\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\".\n" +
	"\bNamedRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x85\x01\n" +
	"\x12KeyValueConstraint\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x02op\x18\x02 \x01(\x0e2\x1f.assembly.v1.ConstraintOperatorR\x02op\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x16\n" +
	"\x06values\x18\x04 \x03(\tR\x06values\"l\n" +
	"\n" +
	"TimeWindow\x120\n" +
	"\x05start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\"U\n" +
	"\vLocalTarget\x12\x1b\n" +
	"\tanchor_id\x18\x01 \x01(\tR\banchorId\x12)\n" +
	"\x06offset\x18\x02 \x01(\v2\x11.geometry.v1.PoseR\x06offset\"\xa2\x01\n" +
	"\x11EstimatedDuration\x123\n" +
	"\anominal\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\anominal\x12+\n" +
	"\x03min\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x03min\x12+\n" +
	"\x03max\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x03max\"x\n" +
	"\vDisplayText\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x121\n" +
	"\x14operator_instruction\x18\x03 \x01(\tR\x13operatorInstruction\"^\n" +
	"\x11ExternalReference\x12\x16\n" +
	"\x06system\x18\x01 \x01(\tR\x06system\x12\x1f\n" +
	"\vexternal_id\x18\x02 \x01(\tR\n" +
	"externalId\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\"C\n" +
	"\x10CustomProperties\x12/\n" +
	"\n" +
	"properties\x18\x01 \x03(\v2\x0f.ar.v1.PropertyR\n" +
	"properties*j\n" +
	"\tActorKind\x12\x1a\n" +
	"\x16ACTOR_KIND_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ACTOR_KIND_HUMAN\x10\x01\x12\x14\n" +
	"\x10ACTOR_KIND_ROBOT\x10\x02\x12\x15\n" +
	"\x11ACTOR_KIND_HYBRID\x10\x03*\xb0\x01\n" +
	"\x0eResourceStatus\x12\x1f\n" +
	"\x1bRESOURCE_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19RESOURCE_STATUS_AVAILABLE\x10\x01\x12\x1f\n" +
	"\x1bRESOURCE_STATUS_UNAVAILABLE\x10\x02\x12\x1c\n" +
	"\x18RESOURCE_STATUS_DISABLED\x10\x03\x12\x1f\n" +
	"\x1bRESOURCE_STATUS_MAINTENANCE\x10\x04*\xa4\x01\n" +
	"\x0fSafetyRelevance\x12 \n" +
	"\x1cSAFETY_RELEVANCE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14SAFETY_RELEVANCE_LOW\x10\x01\x12\x1b\n" +
	"\x17SAFETY_RELEVANCE_MEDIUM\x10\x02\x12\x19\n" +
	"\x15SAFETY_RELEVANCE_HIGH\x10\x03\x12\x1d\n" +
	"\x19SAFETY_RELEVANCE_CRITICAL\x10\x04*\xcd\x01\n" +
	"\x11CollaborationMode\x12\"\n" +
	"\x1eCOLLABORATION_MODE_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dCOLLABORATION_MODE_HUMAN_ONLY\x10\x01\x12!\n" +
	"\x1dCOLLABORATION_MODE_ROBOT_ONLY\x10\x02\x12%\n" +
	"!COLLABORATION_MODE_SEQUENTIAL_HRC\x10\x03\x12'\n" +
	"#COLLABORATION_MODE_SIMULTANEOUS_HRC\x10\x04*\xa0\x02\n" +
	"\x12ConstraintOperator\x12#\n" +
	"\x1fCONSTRAINT_OPERATOR_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16CONSTRAINT_OPERATOR_EQ\x10\x01\x12\x1b\n" +
	"\x17CONSTRAINT_OPERATOR_NEQ\x10\x02\x12\x1a\n" +
	"\x16CONSTRAINT_OPERATOR_GT\x10\x03\x12\x1b\n" +
	"\x17CONSTRAINT_OPERATOR_GTE\x10\x04\x12\x1a\n" +
	"\x16CONSTRAINT_OPERATOR_LT\x10\x05\x12\x1b\n" +
	"\x17CONSTRAINT_OPERATOR_LTE\x10\x06\x12\x1a\n" +
	"\x16CONSTRAINT_OPERATOR_IN\x10\a\x12\x1e\n" +
	"\x1aCONSTRAINT_OPERATOR_NOT_IN\x10\bB\xb1\x01\n" +
	"\x0fcom.assembly.v1B\vCommonProtoP\x01Z;github.com/cobotar/protocol/messages/assembly/v1;assemblyv1\xa2\x02\x03AXX\xaa\x02\x14Messages.Assembly.V1\xca\x02\vAssembly\\V1\xe2\x02\x17Assembly\\V1\\GPBMetadata\xea\x02\fAssembly::V1b\x06proto3"

var (
	file_assembly_v1_common_proto_rawDescOnce sync.Once
	file_assembly_v1_common_proto_rawDescData []byte
)

func file_assembly_v1_common_proto_rawDescGZIP() []byte {
	file_assembly_v1_common_proto_rawDescOnce.Do(func() {
		file_assembly_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_assembly_v1_common_proto_rawDesc), len(file_assembly_v1_common_proto_rawDesc)))
	})
	return file_assembly_v1_common_proto_rawDescData
}

var file_assembly_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_assembly_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_assembly_v1_common_proto_goTypes = []any{
	(ActorKind)(0),                // 0: assembly.v1.ActorKind
	(ResourceStatus)(0),           // 1: assembly.v1.ResourceStatus
	(SafetyRelevance)(0),          // 2: assembly.v1.SafetyRelevance
	(CollaborationMode)(0),        // 3: assembly.v1.CollaborationMode
	(ConstraintOperator)(0),       // 4: assembly.v1.ConstraintOperator
	(*Ref)(nil),                   // 5: assembly.v1.Ref
	(*NamedRef)(nil),              // 6: assembly.v1.NamedRef
	(*KeyValueConstraint)(nil),    // 7: assembly.v1.KeyValueConstraint
	(*TimeWindow)(nil),            // 8: assembly.v1.TimeWindow
	(*LocalTarget)(nil),           // 9: assembly.v1.LocalTarget
	(*EstimatedDuration)(nil),     // 10: assembly.v1.EstimatedDuration
	(*DisplayText)(nil),           // 11: assembly.v1.DisplayText
	(*ExternalReference)(nil),     // 12: assembly.v1.ExternalReference
	(*CustomProperties)(nil),      // 13: assembly.v1.CustomProperties
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
	(*v1.Pose)(nil),               // 15: geometry.v1.Pose
	(*durationpb.Duration)(nil),   // 16: google.protobuf.Duration
	(*v11.Property)(nil),          // 17: ar.v1.Property
}
var file_assembly_v1_common_proto_depIdxs = []int32{
	4,  // 0: assembly.v1.KeyValueConstraint.op:type_name -> assembly.v1.ConstraintOperator
	14, // 1: assembly.v1.TimeWindow.start:type_name -> google.protobuf.Timestamp
	14, // 2: assembly.v1.TimeWindow.end:type_name -> google.protobuf.Timestamp
	15, // 3: assembly.v1.LocalTarget.offset:type_name -> geometry.v1.Pose
	16, // 4: assembly.v1.EstimatedDuration.nominal:type_name -> google.protobuf.Duration
	16, // 5: assembly.v1.EstimatedDuration.min:type_name -> google.protobuf.Duration
	16, // 6: assembly.v1.EstimatedDuration.max:type_name -> google.protobuf.Duration
	17, // 7: assembly.v1.CustomProperties.properties:type_name -> ar.v1.Property
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_assembly_v1_common_proto_init() }
func file_assembly_v1_common_proto_init() {
	if File_assembly_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_assembly_v1_common_proto_rawDesc), len(file_assembly_v1_common_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_assembly_v1_common_proto_goTypes,
		DependencyIndexes: file_assembly_v1_common_proto_depIdxs,
		EnumInfos:         file_assembly_v1_common_proto_enumTypes,
		MessageInfos:      file_assembly_v1_common_proto_msgTypes,
	}.Build()
	File_assembly_v1_common_proto = out.File
	file_assembly_v1_common_proto_goTypes = nil
	file_assembly_v1_common_proto_depIdxs = nil
}
