// @generated by protoc-gen-es v2.10.2 with parameter "target=ts,import_extension=ts"
// @generated from file ar/v1/ar_config.proto (package ar.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ActionMessage } from "./action_pb.ts";
import { file_ar_v1_action } from "./action_pb.ts";
import type { FeedbackMessage } from "./feedback_pb.ts";
import { file_ar_v1_feedback } from "./feedback_pb.ts";
import type { HelperMessage } from "./helper_pb.ts";
import { file_ar_v1_helper } from "./helper_pb.ts";
import type { Property } from "./property_pb.ts";
import { file_ar_v1_property } from "./property_pb.ts";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb.ts";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ar/v1/ar_config.proto.
 */
export const file_ar_v1_ar_config: GenFile = /*@__PURE__*/
  fileDesc("ChVhci92MS9hcl9jb25maWcucHJvdG8SBWFyLnYxIl0KE0FSQ29uZmlnSW5mb01lc3NhZ2USCgoCaWQYASABKAkSFwoEbmFtZRgCIAEoCUIJukgGcgQQARhAEgwKBGljb24YAyABKAkSEwoLZGVzY3JpcHRpb24YBCABKAkiQQoUQVJDb25maWdJbmZvTWVzc2FnZXMSKQoFaW5mb3MYASADKAsyGi5hci52MS5BUkNvbmZpZ0luZm9NZXNzYWdlIqECCg9BUkNvbmZpZ01lc3NhZ2USCgoCaWQYASABKAkSFwoEbmFtZRgCIAEoCUIJukgGcgQQARhAEgwKBGljb24YAyABKAkSEwoLZGVzY3JpcHRpb24YBCABKAkSKAoIZmVlZGJhY2sYBSADKAsyFi5hci52MS5GZWVkYmFja01lc3NhZ2USJQoHYWN0aW9ucxgGIAMoCzIULmFyLnYxLkFjdGlvbk1lc3NhZ2USJQoHaGVscGVycxgHIAMoCzIULmFyLnYxLkhlbHBlck1lc3NhZ2USIwoKcHJvcGVydGllcxgIIAMoCzIPLmFyLnYxLlByb3BlcnR5EikKFWFyX2Rpc2FwcGVhcl9kaXN0YW5jZRgJIAEoA0IKukgHIgVI3gIoACI7ChBBUkNvbmZpZ01lc3NhZ2VzEicKB2NvbmZpZ3MYASADKAsyFi5hci52MS5BUkNvbmZpZ01lc3NhZ2VCiQEKCWNvbS5hci52MUINQXJDb25maWdQcm90b1ABWi9naXRodWIuY29tL2NvYm90YXIvcHJvdG9jb2wvbWVzc2FnZXMvYXIvdjE7YXJ2MaICA0FYWKoCDk1lc3NhZ2VzLkFSLlYxygIFQXJcVjHiAhFBclxWMVxHUEJNZXRhZGF0YeoCBkFyOjpWMWIGcHJvdG8z", [file_ar_v1_action, file_ar_v1_feedback, file_ar_v1_helper, file_ar_v1_property, file_buf_validate_validate]);

/**
 * Just delete this?
 *
 * @generated from message ar.v1.ARConfigInfoMessage
 */
export type ARConfigInfoMessage = Message<"ar.v1.ARConfigInfoMessage"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string icon = 3;
   */
  icon: string;

  /**
   * @generated from field: string description = 4;
   */
  description: string;
};

/**
 * Describes the message ar.v1.ARConfigInfoMessage.
 * Use `create(ARConfigInfoMessageSchema)` to create a new message.
 */
export const ARConfigInfoMessageSchema: GenMessage<ARConfigInfoMessage> = /*@__PURE__*/
  messageDesc(file_ar_v1_ar_config, 0);

/**
 * @generated from message ar.v1.ARConfigInfoMessages
 */
export type ARConfigInfoMessages = Message<"ar.v1.ARConfigInfoMessages"> & {
  /**
   * @generated from field: repeated ar.v1.ARConfigInfoMessage infos = 1;
   */
  infos: ARConfigInfoMessage[];
};

/**
 * Describes the message ar.v1.ARConfigInfoMessages.
 * Use `create(ARConfigInfoMessagesSchema)` to create a new message.
 */
export const ARConfigInfoMessagesSchema: GenMessage<ARConfigInfoMessages> = /*@__PURE__*/
  messageDesc(file_ar_v1_ar_config, 1);

/**
 * @generated from message ar.v1.ARConfigMessage
 */
export type ARConfigMessage = Message<"ar.v1.ARConfigMessage"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string icon = 3;
   */
  icon: string;

  /**
   * @generated from field: string description = 4;
   */
  description: string;

  /**
   * TODO: just a list of Id's?
   *
   * @generated from field: repeated ar.v1.FeedbackMessage feedback = 5;
   */
  feedback: FeedbackMessage[];

  /**
   * @generated from field: repeated ar.v1.ActionMessage actions = 6;
   */
  actions: ActionMessage[];

  /**
   * @generated from field: repeated ar.v1.HelperMessage helpers = 7;
   */
  helpers: HelperMessage[];

  /**
   * @generated from field: repeated ar.v1.Property properties = 8;
   */
  properties: Property[];

  /**
   * Threshold distance in cm all AR elements should disappear. 0 = ignored
   *
   * @generated from field: int64 ar_disappear_distance = 9;
   */
  arDisappearDistance: bigint;
};

/**
 * Describes the message ar.v1.ARConfigMessage.
 * Use `create(ARConfigMessageSchema)` to create a new message.
 */
export const ARConfigMessageSchema: GenMessage<ARConfigMessage> = /*@__PURE__*/
  messageDesc(file_ar_v1_ar_config, 2);

/**
 * @generated from message ar.v1.ARConfigMessages
 */
export type ARConfigMessages = Message<"ar.v1.ARConfigMessages"> & {
  /**
   * @generated from field: repeated ar.v1.ARConfigMessage configs = 1;
   */
  configs: ARConfigMessage[];
};

/**
 * Describes the message ar.v1.ARConfigMessages.
 * Use `create(ARConfigMessagesSchema)` to create a new message.
 */
export const ARConfigMessagesSchema: GenMessage<ARConfigMessages> = /*@__PURE__*/
  messageDesc(file_ar_v1_ar_config, 3);

