// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ar/v1/action.proto

package arv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/cobotar/protocol/messages/validation/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActionType int32

const (
	ActionType_ACTION_TYPE_UNSPECIFIED       ActionType = 0
	ActionType_ACTION_TYPE_TASK_COMPLETE     ActionType = 10
	ActionType_ACTION_TYPE_TASK_UNDO         ActionType = 11
	ActionType_ACTION_TYPE_TASK_ASSIGN       ActionType = 12
	ActionType_ACTION_TYPE_TASK_HIGHLIGHT    ActionType = 13
	ActionType_ACTION_TYPE_TASK_HELP         ActionType = 14
	ActionType_ACTION_TYPE_ROBOT_PLAY_PAUSE  ActionType = 50
	ActionType_ACTION_TYPE_ROBOT_ACKNOWLEDGE ActionType = 51
	ActionType_ACTION_TYPE_ROBOT_FREE_DRIVE  ActionType = 52
)

// Enum value maps for ActionType.
var (
	ActionType_name = map[int32]string{
		0:  "ACTION_TYPE_UNSPECIFIED",
		10: "ACTION_TYPE_TASK_COMPLETE",
		11: "ACTION_TYPE_TASK_UNDO",
		12: "ACTION_TYPE_TASK_ASSIGN",
		13: "ACTION_TYPE_TASK_HIGHLIGHT",
		14: "ACTION_TYPE_TASK_HELP",
		50: "ACTION_TYPE_ROBOT_PLAY_PAUSE",
		51: "ACTION_TYPE_ROBOT_ACKNOWLEDGE",
		52: "ACTION_TYPE_ROBOT_FREE_DRIVE",
	}
	ActionType_value = map[string]int32{
		"ACTION_TYPE_UNSPECIFIED":       0,
		"ACTION_TYPE_TASK_COMPLETE":     10,
		"ACTION_TYPE_TASK_UNDO":         11,
		"ACTION_TYPE_TASK_ASSIGN":       12,
		"ACTION_TYPE_TASK_HIGHLIGHT":    13,
		"ACTION_TYPE_TASK_HELP":         14,
		"ACTION_TYPE_ROBOT_PLAY_PAUSE":  50,
		"ACTION_TYPE_ROBOT_ACKNOWLEDGE": 51,
		"ACTION_TYPE_ROBOT_FREE_DRIVE":  52,
	}
)

func (x ActionType) Enum() *ActionType {
	p := new(ActionType)
	*p = x
	return p
}

func (x ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_ar_v1_action_proto_enumTypes[0].Descriptor()
}

func (ActionType) Type() protoreflect.EnumType {
	return &file_ar_v1_action_proto_enumTypes[0]
}

func (x ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionType.Descriptor instead.
func (ActionType) EnumDescriptor() ([]byte, []int) {
	return file_ar_v1_action_proto_rawDescGZIP(), []int{0}
}

type ActionMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon          string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Type          ActionType             `protobuf:"varint,5,opt,name=type,proto3,enum=ar.v1.ActionType" json:"type,omitempty"`
	Properties    []*Property            `protobuf:"bytes,6,rep,name=properties,proto3" json:"properties,omitempty"`
	ConfigId      string                 `protobuf:"bytes,7,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionMessage) Reset() {
	*x = ActionMessage{}
	mi := &file_ar_v1_action_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionMessage) ProtoMessage() {}

func (x *ActionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ar_v1_action_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionMessage.ProtoReflect.Descriptor instead.
func (*ActionMessage) Descriptor() ([]byte, []int) {
	return file_ar_v1_action_proto_rawDescGZIP(), []int{0}
}

func (x *ActionMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ActionMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ActionMessage) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *ActionMessage) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ActionMessage) GetType() ActionType {
	if x != nil {
		return x.Type
	}
	return ActionType_ACTION_TYPE_UNSPECIFIED
}

func (x *ActionMessage) GetProperties() []*Property {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *ActionMessage) GetConfigId() string {
	if x != nil {
		return x.ConfigId
	}
	return ""
}

type ActionMessages struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actions       []*ActionMessage       `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionMessages) Reset() {
	*x = ActionMessages{}
	mi := &file_ar_v1_action_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionMessages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionMessages) ProtoMessage() {}

func (x *ActionMessages) ProtoReflect() protoreflect.Message {
	mi := &file_ar_v1_action_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionMessages.ProtoReflect.Descriptor instead.
func (*ActionMessages) Descriptor() ([]byte, []int) {
	return file_ar_v1_action_proto_rawDescGZIP(), []int{1}
}

func (x *ActionMessages) GetActions() []*ActionMessage {
	if x != nil {
		return x.Actions
	}
	return nil
}

type ActionAddMessage struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ConfigId             string                 `protobuf:"bytes,1,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon                 string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Description          string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Type                 ActionType             `protobuf:"varint,5,opt,name=type,proto3,enum=ar.v1.ActionType" json:"type,omitempty"`
	AgentId              string                 `protobuf:"bytes,6,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ActivatingPropertyId string                 `protobuf:"bytes,7,opt,name=activating_property_id,json=activatingPropertyId,proto3" json:"activating_property_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ActionAddMessage) Reset() {
	*x = ActionAddMessage{}
	mi := &file_ar_v1_action_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionAddMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionAddMessage) ProtoMessage() {}

func (x *ActionAddMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ar_v1_action_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionAddMessage.ProtoReflect.Descriptor instead.
func (*ActionAddMessage) Descriptor() ([]byte, []int) {
	return file_ar_v1_action_proto_rawDescGZIP(), []int{2}
}

func (x *ActionAddMessage) GetConfigId() string {
	if x != nil {
		return x.ConfigId
	}
	return ""
}

func (x *ActionAddMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ActionAddMessage) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *ActionAddMessage) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ActionAddMessage) GetType() ActionType {
	if x != nil {
		return x.Type
	}
	return ActionType_ACTION_TYPE_UNSPECIFIED
}

func (x *ActionAddMessage) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ActionAddMessage) GetActivatingPropertyId() string {
	if x != nil {
		return x.ActivatingPropertyId
	}
	return ""
}

type ActionUpdateMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon          string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionUpdateMessage) Reset() {
	*x = ActionUpdateMessage{}
	mi := &file_ar_v1_action_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionUpdateMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionUpdateMessage) ProtoMessage() {}

func (x *ActionUpdateMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ar_v1_action_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionUpdateMessage.ProtoReflect.Descriptor instead.
func (*ActionUpdateMessage) Descriptor() ([]byte, []int) {
	return file_ar_v1_action_proto_rawDescGZIP(), []int{3}
}

func (x *ActionUpdateMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ActionUpdateMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ActionUpdateMessage) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *ActionUpdateMessage) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ActionCloneMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalId    string                 `protobuf:"bytes,1,opt,name=original_id,json=originalId,proto3" json:"original_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon          string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionCloneMessage) Reset() {
	*x = ActionCloneMessage{}
	mi := &file_ar_v1_action_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionCloneMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionCloneMessage) ProtoMessage() {}

func (x *ActionCloneMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ar_v1_action_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionCloneMessage.ProtoReflect.Descriptor instead.
func (*ActionCloneMessage) Descriptor() ([]byte, []int) {
	return file_ar_v1_action_proto_rawDescGZIP(), []int{4}
}

func (x *ActionCloneMessage) GetOriginalId() string {
	if x != nil {
		return x.OriginalId
	}
	return ""
}

func (x *ActionCloneMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ActionCloneMessage) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *ActionCloneMessage) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_ar_v1_action_proto protoreflect.FileDescriptor

const file_ar_v1_action_proto_rawDesc = "" +
	"\n" +
	"\x12ar/v1/action.proto\x12\x05ar.v1\x1a\x14ar/v1/property.proto\x1a\x1bbuf/validate/validate.proto\x1a+validation/v1/predefined_string_rules.proto\"\x81\x02\n" +
	"\rActionMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\x04name\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x80\xf1\x04\x01R\x04name\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x122\n" +
	"\x04type\x18\x05 \x01(\x0e2\x11.ar.v1.ActionTypeB\v\xbaH\b\xc8\x01\x01\x82\x01\x02\x10\x01R\x04type\x12/\n" +
	"\n" +
	"properties\x18\x06 \x03(\v2\x0f.ar.v1.PropertyR\n" +
	"properties\x12&\n" +
	"\tconfig_id\x18\a \x01(\tB\t\xbaH\x06r\x04\x90\xf1\x04\x01R\bconfigId\"@\n" +
	"\x0eActionMessages\x12.\n" +
	"\aactions\x18\x01 \x03(\v2\x14.ar.v1.ActionMessageR\aactions\"\x89\x02\n" +
	"\x10ActionAddMessage\x12&\n" +
	"\tconfig_id\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x90\xf1\x04\x01R\bconfigId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x122\n" +
	"\x04type\x18\x05 \x01(\x0e2\x11.ar.v1.ActionTypeB\v\xbaH\b\xc8\x01\x01\x82\x01\x02\x10\x01R\x04type\x12\x19\n" +
	"\bagent_id\x18\x06 \x01(\tR\aagentId\x124\n" +
	"\x16activating_property_id\x18\a \x01(\tR\x14activatingPropertyId\"z\n" +
	"\x13ActionUpdateMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\x04name\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x80\xf1\x04\x01R\x04name\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\x7f\n" +
	"\x12ActionCloneMessage\x12\x1f\n" +
	"\voriginal_id\x18\x01 \x01(\tR\n" +
	"originalId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription*\xa2\x02\n" +
	"\n" +
	"ActionType\x12\x1b\n" +
	"\x17ACTION_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19ACTION_TYPE_TASK_COMPLETE\x10\n" +
	"\x12\x19\n" +
	"\x15ACTION_TYPE_TASK_UNDO\x10\v\x12\x1b\n" +
	"\x17ACTION_TYPE_TASK_ASSIGN\x10\f\x12\x1e\n" +
	"\x1aACTION_TYPE_TASK_HIGHLIGHT\x10\r\x12\x19\n" +
	"\x15ACTION_TYPE_TASK_HELP\x10\x0e\x12 \n" +
	"\x1cACTION_TYPE_ROBOT_PLAY_PAUSE\x102\x12!\n" +
	"\x1dACTION_TYPE_ROBOT_ACKNOWLEDGE\x103\x12 \n" +
	"\x1cACTION_TYPE_ROBOT_FREE_DRIVE\x104B\x87\x01\n" +
	"\tcom.ar.v1B\vActionProtoP\x01Z/github.com/cobotar/protocol/messages/ar/v1;arv1\xa2\x02\x03AXX\xaa\x02\x0eMessages.AR.V1\xca\x02\x05Ar\\V1\xe2\x02\x11Ar\\V1\\GPBMetadata\xea\x02\x06Ar::V1b\x06proto3"

var (
	file_ar_v1_action_proto_rawDescOnce sync.Once
	file_ar_v1_action_proto_rawDescData []byte
)

func file_ar_v1_action_proto_rawDescGZIP() []byte {
	file_ar_v1_action_proto_rawDescOnce.Do(func() {
		file_ar_v1_action_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ar_v1_action_proto_rawDesc), len(file_ar_v1_action_proto_rawDesc)))
	})
	return file_ar_v1_action_proto_rawDescData
}

var file_ar_v1_action_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ar_v1_action_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_ar_v1_action_proto_goTypes = []any{
	(ActionType)(0),             // 0: ar.v1.ActionType
	(*ActionMessage)(nil),       // 1: ar.v1.ActionMessage
	(*ActionMessages)(nil),      // 2: ar.v1.ActionMessages
	(*ActionAddMessage)(nil),    // 3: ar.v1.ActionAddMessage
	(*ActionUpdateMessage)(nil), // 4: ar.v1.ActionUpdateMessage
	(*ActionCloneMessage)(nil),  // 5: ar.v1.ActionCloneMessage
	(*Property)(nil),            // 6: ar.v1.Property
}
var file_ar_v1_action_proto_depIdxs = []int32{
	0, // 0: ar.v1.ActionMessage.type:type_name -> ar.v1.ActionType
	6, // 1: ar.v1.ActionMessage.properties:type_name -> ar.v1.Property
	1, // 2: ar.v1.ActionMessages.actions:type_name -> ar.v1.ActionMessage
	0, // 3: ar.v1.ActionAddMessage.type:type_name -> ar.v1.ActionType
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_ar_v1_action_proto_init() }
func file_ar_v1_action_proto_init() {
	if File_ar_v1_action_proto != nil {
		return
	}
	file_ar_v1_property_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ar_v1_action_proto_rawDesc), len(file_ar_v1_action_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ar_v1_action_proto_goTypes,
		DependencyIndexes: file_ar_v1_action_proto_depIdxs,
		EnumInfos:         file_ar_v1_action_proto_enumTypes,
		MessageInfos:      file_ar_v1_action_proto_msgTypes,
	}.Build()
	File_ar_v1_action_proto = out.File
	file_ar_v1_action_proto_goTypes = nil
	file_ar_v1_action_proto_depIdxs = nil
}
