// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ar/v1/ar_config_binding.proto

package arv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/cobotar/protocol/messages/common/v1"
	_ "github.com/cobotar/protocol/messages/validation/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RobotMapping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RobotId       string                 `protobuf:"bytes,1,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`          // Legacy robot definition identifier.
	PropertyId    string                 `protobuf:"bytes,2,opt,name=property_id,json=propertyId,proto3" json:"property_id,omitempty"` // Legacy target property for the mapped robot.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RobotMapping) Reset() {
	*x = RobotMapping{}
	mi := &file_ar_v1_ar_config_binding_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RobotMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotMapping) ProtoMessage() {}

func (x *RobotMapping) ProtoReflect() protoreflect.Message {
	mi := &file_ar_v1_ar_config_binding_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotMapping.ProtoReflect.Descriptor instead.
func (*RobotMapping) Descriptor() ([]byte, []int) {
	return file_ar_v1_ar_config_binding_proto_rawDescGZIP(), []int{0}
}

func (x *RobotMapping) GetRobotId() string {
	if x != nil {
		return x.RobotId
	}
	return ""
}

func (x *RobotMapping) GetPropertyId() string {
	if x != nil {
		return x.PropertyId
	}
	return ""
}

type AssetMapping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetId       string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`          // Legacy asset definition identifier.
	PropertyId    string                 `protobuf:"bytes,2,opt,name=property_id,json=propertyId,proto3" json:"property_id,omitempty"` // Legacy target property for the mapped asset.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetMapping) Reset() {
	*x = AssetMapping{}
	mi := &file_ar_v1_ar_config_binding_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetMapping) ProtoMessage() {}

func (x *AssetMapping) ProtoReflect() protoreflect.Message {
	mi := &file_ar_v1_ar_config_binding_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetMapping.ProtoReflect.Descriptor instead.
func (*AssetMapping) Descriptor() ([]byte, []int) {
	return file_ar_v1_ar_config_binding_proto_rawDescGZIP(), []int{1}
}

func (x *AssetMapping) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *AssetMapping) GetPropertyId() string {
	if x != nil {
		return x.PropertyId
	}
	return ""
}

// ARResourceBinding binds a config-declared slot to a concrete resource
// instance owned by the target station or cell.
type ARResourceBinding struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SlotId          string                 `protobuf:"bytes,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`                              // Config-declared slot to satisfy.
	RobotInstanceId string                 `protobuf:"bytes,2,opt,name=robot_instance_id,json=robotInstanceId,proto3" json:"robot_instance_id,omitempty"` // Concrete robot instance selected for the slot.
	AssetInstanceId string                 `protobuf:"bytes,3,opt,name=asset_instance_id,json=assetInstanceId,proto3" json:"asset_instance_id,omitempty"` // Concrete asset instance selected for the slot.
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ARResourceBinding) Reset() {
	*x = ARResourceBinding{}
	mi := &file_ar_v1_ar_config_binding_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ARResourceBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ARResourceBinding) ProtoMessage() {}

func (x *ARResourceBinding) ProtoReflect() protoreflect.Message {
	mi := &file_ar_v1_ar_config_binding_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ARResourceBinding.ProtoReflect.Descriptor instead.
func (*ARResourceBinding) Descriptor() ([]byte, []int) {
	return file_ar_v1_ar_config_binding_proto_rawDescGZIP(), []int{2}
}

func (x *ARResourceBinding) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

func (x *ARResourceBinding) GetRobotInstanceId() string {
	if x != nil {
		return x.RobotInstanceId
	}
	return ""
}

func (x *ARResourceBinding) GetAssetInstanceId() string {
	if x != nil {
		return x.AssetInstanceId
	}
	return ""
}

// ARConfigBindingMessage binds a reusable ARConfig to a concrete runtime
// workspace.
//
// Runtime resolution should typically work like this:
// - load bindings targeted directly at the active station
// - load bindings targeted at the parent cell
// - sort by standalone/priority
// - apply property_overrides after the config template is loaded
// - populate resource slot properties and runtime context values afterwards
//
// This keeps ARConfig authoring reusable while making station/cell-specific
// resource wiring explicit and safe.
type ARConfigBindingMessage struct {
	state             protoimpl.MessageState    `protogen:"open.v1"`
	Id                string                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Stable binding identifier.
	Name              string                    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon              string                    `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Description       string                    `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	StationId         string                    `protobuf:"bytes,5,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`                          // Station this binding targets directly.
	CellId            string                    `protobuf:"bytes,6,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`                                   // Cell this binding targets directly.
	ArConfigId        string                    `protobuf:"bytes,7,opt,name=ar_config_id,json=arConfigId,proto3" json:"ar_config_id,omitempty"`                     // Reusable AR config template to bind.
	Disabled          bool                      `protobuf:"varint,8,opt,name=disabled,proto3" json:"disabled,omitempty"`                                            // If true, the binding should be ignored by resolution.
	Standalone        bool                      `protobuf:"varint,9,opt,name=standalone,proto3" json:"standalone,omitempty"`                                        // If true, only standalone bindings with the highest priority should be shown.
	Priority          int32                     `protobuf:"varint,10,opt,name=priority,proto3" json:"priority,omitempty"`                                           // Higher values should be resolved before lower values.
	ResourceBindings  []*ARResourceBinding      `protobuf:"bytes,11,rep,name=resource_bindings,json=resourceBindings,proto3" json:"resource_bindings,omitempty"`    // Concrete resource assignments for config-declared slots.
	PropertyOverrides []*v1.PropertyValueUpdate `protobuf:"bytes,12,rep,name=property_overrides,json=propertyOverrides,proto3" json:"property_overrides,omitempty"` // Station/cell-local values applied to config properties before runtime values.
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ARConfigBindingMessage) Reset() {
	*x = ARConfigBindingMessage{}
	mi := &file_ar_v1_ar_config_binding_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ARConfigBindingMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ARConfigBindingMessage) ProtoMessage() {}

func (x *ARConfigBindingMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ar_v1_ar_config_binding_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ARConfigBindingMessage.ProtoReflect.Descriptor instead.
func (*ARConfigBindingMessage) Descriptor() ([]byte, []int) {
	return file_ar_v1_ar_config_binding_proto_rawDescGZIP(), []int{3}
}

func (x *ARConfigBindingMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ARConfigBindingMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ARConfigBindingMessage) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *ARConfigBindingMessage) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ARConfigBindingMessage) GetStationId() string {
	if x != nil {
		return x.StationId
	}
	return ""
}

func (x *ARConfigBindingMessage) GetCellId() string {
	if x != nil {
		return x.CellId
	}
	return ""
}

func (x *ARConfigBindingMessage) GetArConfigId() string {
	if x != nil {
		return x.ArConfigId
	}
	return ""
}

func (x *ARConfigBindingMessage) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *ARConfigBindingMessage) GetStandalone() bool {
	if x != nil {
		return x.Standalone
	}
	return false
}

func (x *ARConfigBindingMessage) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *ARConfigBindingMessage) GetResourceBindings() []*ARResourceBinding {
	if x != nil {
		return x.ResourceBindings
	}
	return nil
}

func (x *ARConfigBindingMessage) GetPropertyOverrides() []*v1.PropertyValueUpdate {
	if x != nil {
		return x.PropertyOverrides
	}
	return nil
}

type ARConfigBindingMessages struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Bindings      []*ARConfigBindingMessage `protobuf:"bytes,1,rep,name=bindings,proto3" json:"bindings,omitempty"` // Station/cell bindings for reusable AR configs.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ARConfigBindingMessages) Reset() {
	*x = ARConfigBindingMessages{}
	mi := &file_ar_v1_ar_config_binding_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ARConfigBindingMessages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ARConfigBindingMessages) ProtoMessage() {}

func (x *ARConfigBindingMessages) ProtoReflect() protoreflect.Message {
	mi := &file_ar_v1_ar_config_binding_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ARConfigBindingMessages.ProtoReflect.Descriptor instead.
func (*ARConfigBindingMessages) Descriptor() ([]byte, []int) {
	return file_ar_v1_ar_config_binding_proto_rawDescGZIP(), []int{4}
}

func (x *ARConfigBindingMessages) GetBindings() []*ARConfigBindingMessage {
	if x != nil {
		return x.Bindings
	}
	return nil
}

var File_ar_v1_ar_config_binding_proto protoreflect.FileDescriptor

const file_ar_v1_ar_config_binding_proto_rawDesc = "" +
	"\n" +
	"\x1dar/v1/ar_config_binding.proto\x12\x05ar.v1\x1a\x1bbuf/validate/validate.proto\x1a\x18common/v1/property.proto\x1a+validation/v1/predefined_string_rules.proto\"`\n" +
	"\fRobotMapping\x12$\n" +
	"\brobot_id\x18\x01 \x01(\tB\t\xbaH\x06r\x04\xa0\xf1\x04\x01R\arobotId\x12*\n" +
	"\vproperty_id\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x98\xf1\x04\x01R\n" +
	"propertyId\"`\n" +
	"\fAssetMapping\x12$\n" +
	"\basset_id\x18\x01 \x01(\tB\t\xbaH\x06r\x04\xb0\xf1\x04\x01R\aassetId\x12*\n" +
	"\vproperty_id\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x98\xf1\x04\x01R\n" +
	"propertyId\"\xd4\x01\n" +
	"\x11ARResourceBinding\x12\"\n" +
	"\aslot_id\x18\x01 \x01(\tB\t\xbaH\x06r\x04\xf8\xeb0\x01R\x06slotId\x125\n" +
	"\x11robot_instance_id\x18\x02 \x01(\tB\t\xbaH\x06r\x04\xa8\xf1\x04\x01R\x0frobotInstanceId\x125\n" +
	"\x11asset_instance_id\x18\x03 \x01(\tB\t\xbaH\x06r\x04\xb8\xf1\x04\x01R\x0fassetInstanceId:-\xbaH*\"(\n" +
	"\x11robot_instance_id\n" +
	"\x11asset_instance_id\x10\x01\"\x92\x04\n" +
	"\x16ARConfigBindingMessage\x12\x19\n" +
	"\x02id\x18\x01 \x01(\tB\t\xbaH\x06r\x04\xe8\xeb0\x01R\x02id\x12\x1d\n" +
	"\x04name\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x80\xf1\x04\x01R\x04name\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12(\n" +
	"\n" +
	"station_id\x18\x05 \x01(\tB\t\xbaH\x06r\x04\xf8\xf1\x04\x01R\tstationId\x12\"\n" +
	"\acell_id\x18\x06 \x01(\tB\t\xbaH\x06r\x04\xb8\xf2\x04\x01R\x06cellId\x12.\n" +
	"\far_config_id\x18\a \x01(\tB\f\xbaH\t\xc8\x01\x01r\x04\x90\xf1\x04\x01R\n" +
	"arConfigId\x12\x1a\n" +
	"\bdisabled\x18\b \x01(\bR\bdisabled\x12\x1e\n" +
	"\n" +
	"standalone\x18\t \x01(\bR\n" +
	"standalone\x12\x1a\n" +
	"\bpriority\x18\n" +
	" \x01(\x05R\bpriority\x12E\n" +
	"\x11resource_bindings\x18\v \x03(\v2\x18.ar.v1.ARResourceBindingR\x10resourceBindings\x12M\n" +
	"\x12property_overrides\x18\f \x03(\v2\x1e.common.v1.PropertyValueUpdateR\x11propertyOverrides:\x1c\xbaH\x19\"\x17\n" +
	"\n" +
	"station_id\n" +
	"\acell_id\x10\x01\"T\n" +
	"\x17ARConfigBindingMessages\x129\n" +
	"\bbindings\x18\x01 \x03(\v2\x1d.ar.v1.ARConfigBindingMessageR\bbindingsB\x90\x01\n" +
	"\tcom.ar.v1B\x14ArConfigBindingProtoP\x01Z/github.com/cobotar/protocol/messages/ar/v1;arv1\xa2\x02\x03AXX\xaa\x02\x0eMessages.AR.V1\xca\x02\x05Ar\\V1\xe2\x02\x11Ar\\V1\\GPBMetadata\xea\x02\x06Ar::V1b\x06proto3"

var (
	file_ar_v1_ar_config_binding_proto_rawDescOnce sync.Once
	file_ar_v1_ar_config_binding_proto_rawDescData []byte
)

func file_ar_v1_ar_config_binding_proto_rawDescGZIP() []byte {
	file_ar_v1_ar_config_binding_proto_rawDescOnce.Do(func() {
		file_ar_v1_ar_config_binding_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ar_v1_ar_config_binding_proto_rawDesc), len(file_ar_v1_ar_config_binding_proto_rawDesc)))
	})
	return file_ar_v1_ar_config_binding_proto_rawDescData
}

var file_ar_v1_ar_config_binding_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_ar_v1_ar_config_binding_proto_goTypes = []any{
	(*RobotMapping)(nil),            // 0: ar.v1.RobotMapping
	(*AssetMapping)(nil),            // 1: ar.v1.AssetMapping
	(*ARResourceBinding)(nil),       // 2: ar.v1.ARResourceBinding
	(*ARConfigBindingMessage)(nil),  // 3: ar.v1.ARConfigBindingMessage
	(*ARConfigBindingMessages)(nil), // 4: ar.v1.ARConfigBindingMessages
	(*v1.PropertyValueUpdate)(nil),  // 5: common.v1.PropertyValueUpdate
}
var file_ar_v1_ar_config_binding_proto_depIdxs = []int32{
	2, // 0: ar.v1.ARConfigBindingMessage.resource_bindings:type_name -> ar.v1.ARResourceBinding
	5, // 1: ar.v1.ARConfigBindingMessage.property_overrides:type_name -> common.v1.PropertyValueUpdate
	3, // 2: ar.v1.ARConfigBindingMessages.bindings:type_name -> ar.v1.ARConfigBindingMessage
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_ar_v1_ar_config_binding_proto_init() }
func file_ar_v1_ar_config_binding_proto_init() {
	if File_ar_v1_ar_config_binding_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ar_v1_ar_config_binding_proto_rawDesc), len(file_ar_v1_ar_config_binding_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ar_v1_ar_config_binding_proto_goTypes,
		DependencyIndexes: file_ar_v1_ar_config_binding_proto_depIdxs,
		MessageInfos:      file_ar_v1_ar_config_binding_proto_msgTypes,
	}.Build()
	File_ar_v1_ar_config_binding_proto = out.File
	file_ar_v1_ar_config_binding_proto_goTypes = nil
	file_ar_v1_ar_config_binding_proto_depIdxs = nil
}
