// @generated by protoc-gen-es v2.10.2 with parameter "target=ts,import_extension=ts"
// @generated from file resources/v1/cell_definition.proto (package resources.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { CustomProperties } from "../../common/v1/custom_properties_pb.ts";
import { file_common_v1_custom_properties } from "../../common/v1/custom_properties_pb.ts";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file resources/v1/cell_definition.proto.
 */
export const file_resources_v1_cell_definition: GenFile = /*@__PURE__*/
  fileDesc("CiJyZXNvdXJjZXMvdjEvY2VsbF9kZWZpbml0aW9uLnByb3RvEgxyZXNvdXJjZXMudjEijwEKDkNlbGxEZWZpbml0aW9uEgoKAmlkGAEgASgJEgwKBG5hbWUYAiABKAkSEwoLZGVzY3JpcHRpb24YAyABKAkSDAoEaWNvbhgEIAEoCRITCgtzdGF0aW9uX2lkcxgFIAMoCRIrCgZjdXN0b20YBiABKAsyGy5jb21tb24udjEuQ3VzdG9tUHJvcGVydGllc0LAAQoQY29tLnJlc291cmNlcy52MUITQ2VsbERlZmluaXRpb25Qcm90b1ABWj1naXRodWIuY29tL2NvYm90YXIvcHJvdG9jb2wvbWVzc2FnZXMvcmVzb3VyY2VzL3YxO3Jlc291cmNlc3YxogIDUlhYqgIVTWVzc2FnZXMuUmVzb3VyY2VzLlYxygIMUmVzb3VyY2VzXFYx4gIYUmVzb3VyY2VzXFYxXEdQQk1ldGFkYXRh6gINUmVzb3VyY2VzOjpWMWIGcHJvdG8z", [file_common_v1_custom_properties]);

/**
 * @generated from message resources.v1.CellDefinition
 */
export type CellDefinition = Message<"resources.v1.CellDefinition"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * @generated from field: string icon = 4;
   */
  icon: string;

  /**
   * @generated from field: repeated string station_ids = 5;
   */
  stationIds: string[];

  /**
   * @generated from field: common.v1.CustomProperties custom = 6;
   */
  custom?: CustomProperties;
};

/**
 * Describes the message resources.v1.CellDefinition.
 * Use `create(CellDefinitionSchema)` to create a new message.
 */
export const CellDefinitionSchema: GenMessage<CellDefinition> = /*@__PURE__*/
  messageDesc(file_resources_v1_cell_definition, 0);

