// @generated by protoc-gen-es v2.10.2 with parameter "target=ts,import_extension=ts"
// @generated from file resources/v1/worker_definition.proto (package resources.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb.ts";
import type { CustomProperties } from "../../common/v1/custom_properties_pb.ts";
import { file_common_v1_custom_properties } from "../../common/v1/custom_properties_pb.ts";
import type { ExternalReference } from "../../common/v1/external_references_pb.ts";
import { file_common_v1_external_references } from "../../common/v1/external_references_pb.ts";
import { file_validation_v1_predefined_string_rules } from "../../validation/v1/predefined_string_rules_pb.ts";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file resources/v1/worker_definition.proto.
 */
export const file_resources_v1_worker_definition: GenFile = /*@__PURE__*/
  fileDesc("CiRyZXNvdXJjZXMvdjEvd29ya2VyX2RlZmluaXRpb24ucHJvdG8SDHJlc291cmNlcy52MSKjAgoQV29ya2VyRGVmaW5pdGlvbhIKCgJpZBgBIAEoCRIXCgRuYW1lGAIgASgJQgm6SAZyBIDxBAESEwoLZGVzY3JpcHRpb24YAyABKAkSDAoEaWNvbhgEIAEoCRIQCghkaXNhYmxlZBgFIAEoCBITCgtlbXBsb3llZV9pZBgGIAEoCRI4ChJhcl9lZGl0X3Blcm1pc3Npb24YByABKA4yHC5yZXNvdXJjZXMudjEuRWRpdFBlcm1pc3Npb24SOQoTZXh0ZXJuYWxfcmVmZXJlbmNlcxgIIAMoCzIcLmNvbW1vbi52MS5FeHRlcm5hbFJlZmVyZW5jZRIrCgZjdXN0b20YCSABKAsyGy5jb21tb24udjEuQ3VzdG9tUHJvcGVydGllcyJCChFXb3JrZXJEZWZpbml0aW9ucxItCgVpdGVtcxgBIAMoCzIeLnJlc291cmNlcy52MS5Xb3JrZXJEZWZpbml0aW9uKoQBCg5FZGl0UGVybWlzc2lvbhIfChtFRElUX1BFUk1JU1NJT05fVU5TUEVDSUZJRUQQABIZChVFRElUX1BFUk1JU1NJT05fQkFTSUMQARIcChhFRElUX1BFUk1JU1NJT05fQ09TTUVUSUMQAhIYChRFRElUX1BFUk1JU1NJT05fRlVMTBADQsIBChBjb20ucmVzb3VyY2VzLnYxQhVXb3JrZXJEZWZpbml0aW9uUHJvdG9QAVo9Z2l0aHViLmNvbS9jb2JvdGFyL3Byb3RvY29sL21lc3NhZ2VzL3Jlc291cmNlcy92MTtyZXNvdXJjZXN2MaICA1JYWKoCFU1lc3NhZ2VzLlJlc291cmNlcy5WMcoCDFJlc291cmNlc1xWMeICGFJlc291cmNlc1xWMVxHUEJNZXRhZGF0YeoCDVJlc291cmNlczo6VjFiBnByb3RvMw", [file_buf_validate_validate, file_common_v1_custom_properties, file_common_v1_external_references, file_validation_v1_predefined_string_rules]);

/**
 * @generated from message resources.v1.WorkerDefinition
 */
export type WorkerDefinition = Message<"resources.v1.WorkerDefinition"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * @generated from field: string icon = 4;
   */
  icon: string;

  /**
   * If disabled, the worker can't be selected
   *
   * @generated from field: bool disabled = 5;
   */
  disabled: boolean;

  /**
   * @generated from field: string employee_id = 6;
   */
  employeeId: string;

  /**
   * @generated from field: resources.v1.EditPermission ar_edit_permission = 7;
   */
  arEditPermission: EditPermission;

  /**
   * @generated from field: repeated common.v1.ExternalReference external_references = 8;
   */
  externalReferences: ExternalReference[];

  /**
   * @generated from field: common.v1.CustomProperties custom = 9;
   */
  custom?: CustomProperties;
};

/**
 * Describes the message resources.v1.WorkerDefinition.
 * Use `create(WorkerDefinitionSchema)` to create a new message.
 */
export const WorkerDefinitionSchema: GenMessage<WorkerDefinition> = /*@__PURE__*/
  messageDesc(file_resources_v1_worker_definition, 0);

/**
 * @generated from message resources.v1.WorkerDefinitions
 */
export type WorkerDefinitions = Message<"resources.v1.WorkerDefinitions"> & {
  /**
   * @generated from field: repeated resources.v1.WorkerDefinition items = 1;
   */
  items: WorkerDefinition[];
};

/**
 * Describes the message resources.v1.WorkerDefinitions.
 * Use `create(WorkerDefinitionsSchema)` to create a new message.
 */
export const WorkerDefinitionsSchema: GenMessage<WorkerDefinitions> = /*@__PURE__*/
  messageDesc(file_resources_v1_worker_definition, 1);

/**
 * @generated from enum resources.v1.EditPermission
 */
export enum EditPermission {
  /**
   * Unspecified: can't edit any properties
   *
   * @generated from enum value: EDIT_PERMISSION_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Basic: can edit {basic} properties
   *
   * @generated from enum value: EDIT_PERMISSION_BASIC = 1;
   */
  BASIC = 1,

  /**
   * Cosmetic: can edit {basic, cosmetic} properties
   *
   * @generated from enum value: EDIT_PERMISSION_COSMETIC = 2;
   */
  COSMETIC = 2,

  /**
   * Full: can edit all editable properties
   *
   * @generated from enum value: EDIT_PERMISSION_FULL = 3;
   */
  FULL = 3,
}

/**
 * Describes the enum resources.v1.EditPermission.
 */
export const EditPermissionSchema: GenEnum<EditPermission> = /*@__PURE__*/
  enumDesc(file_resources_v1_worker_definition, 0);

