// @generated by protoc-gen-es v2.10.2 with parameter "target=ts,import_extension=ts"
// @generated from file capability/v1/validity_policy.proto (package capability.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb.ts";
import { file_validation_v1_predefined_string_rules } from "../../validation/v1/predefined_string_rules_pb.ts";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file capability/v1/validity_policy.proto.
 */
export const file_capability_v1_validity_policy: GenFile = /*@__PURE__*/
  fileDesc("CiNjYXBhYmlsaXR5L3YxL3ZhbGlkaXR5X3BvbGljeS5wcm90bxINY2FwYWJpbGl0eS52MSJpCg5WYWxpZGl0eVBvbGljeRIKCgJpZBgBIAEoCRIXCgRuYW1lGAIgASgJQgm6SAZyBIDxBAESDAoEaWNvbhgDIAEoCRITCgtkZXNjcmlwdGlvbhgEIAEoCRIPCgd2ZXJzaW9uGAUgASgJIkAKEFZhbGlkaXR5UG9saWNpZXMSLAoFaXRlbXMYASADKAsyHS5jYXBhYmlsaXR5LnYxLlZhbGlkaXR5UG9saWN5QscBChFjb20uY2FwYWJpbGl0eS52MUITVmFsaWRpdHlQb2xpY3lQcm90b1ABWj9naXRodWIuY29tL2NvYm90YXIvcHJvdG9jb2wvbWVzc2FnZXMvY2FwYWJpbGl0eS92MTtjYXBhYmlsaXR5djGiAgNDWFiqAhZNZXNzYWdlcy5DYXBhYmlsaXR5LlYxygINQ2FwYWJpbGl0eVxWMeICGUNhcGFiaWxpdHlcVjFcR1BCTWV0YWRhdGHqAg5DYXBhYmlsaXR5OjpWMWIGcHJvdG8z", [file_buf_validate_validate, file_validation_v1_predefined_string_rules]);

/**
 * @generated from message capability.v1.ValidityPolicy
 */
export type ValidityPolicy = Message<"capability.v1.ValidityPolicy"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string icon = 3;
   */
  icon: string;

  /**
   * @generated from field: string description = 4;
   */
  description: string;

  /**
   * @generated from field: string version = 5;
   */
  version: string;
};

/**
 * Describes the message capability.v1.ValidityPolicy.
 * Use `create(ValidityPolicySchema)` to create a new message.
 */
export const ValidityPolicySchema: GenMessage<ValidityPolicy> = /*@__PURE__*/
  messageDesc(file_capability_v1_validity_policy, 0);

/**
 * @generated from message capability.v1.ValidityPolicies
 */
export type ValidityPolicies = Message<"capability.v1.ValidityPolicies"> & {
  /**
   * @generated from field: repeated capability.v1.ValidityPolicy items = 1;
   */
  items: ValidityPolicy[];
};

/**
 * Describes the message capability.v1.ValidityPolicies.
 * Use `create(ValidityPoliciesSchema)` to create a new message.
 */
export const ValidityPoliciesSchema: GenMessage<ValidityPolicies> = /*@__PURE__*/
  messageDesc(file_capability_v1_validity_policy, 1);

