syntax = "proto3";
package ar.v1;

import "buf/validate/validate.proto";

option csharp_namespace = "Messages.AR.V1";
option go_package = "github.com/cobotar/protocol/messages/ar/v1";

enum AssistanceSemantic {
  ASSISTANCE_SEMANTIC_UNSPECIFIED = 0;

  ASSISTANCE_SEMANTIC_LOCATE_ENTITY = 1;
  ASSISTANCE_SEMANTIC_DIRECT_ATTENTION = 2;

  ASSISTANCE_SEMANTIC_SHOW_TARGET_POSITION = 10;
  ASSISTANCE_SEMANTIC_SHOW_TARGET_ORIENTATION = 11;
  ASSISTANCE_SEMANTIC_SUPPORT_ALIGNMENT = 12;

  ASSISTANCE_SEMANTIC_COMMUNICATE_ACTION = 20;
  ASSISTANCE_SEMANTIC_COMMUNICATE_CONSTRAINT = 21;
  ASSISTANCE_SEMANTIC_COMMUNICATE_EXCEPTION = 22;
  ASSISTANCE_SEMANTIC_COMMUNICATE_VARIANT = 23;

  ASSISTANCE_SEMANTIC_REQUEST_ACKNOWLEDGEMENT = 30;
  ASSISTANCE_SEMANTIC_VERIFY_STATE = 31;
  ASSISTANCE_SEMANTIC_ESTABLISH_COMPLETION = 32;

  ASSISTANCE_SEMANTIC_PRESENT_ACTION = 40;
  ASSISTANCE_SEMANTIC_COMMUNICATE_ACTION_CONSEQUENCE = 41;
  ASSISTANCE_SEMANTIC_PROTECT_ACTION = 42;
}

enum SemanticSourceType {
  SEMANTIC_SOURCE_TYPE_UNSPECIFIED = 0;

  SEMANTIC_SOURCE_TYPE_ACTION = 1;
  SEMANTIC_SOURCE_TYPE_SUBJECT = 2;
  SEMANTIC_SOURCE_TYPE_SUBJECT_LABEL = 3;
  SEMANTIC_SOURCE_TYPE_SUBJECT_GEOMETRY = 4;

  SEMANTIC_SOURCE_TYPE_CURRENT_POSE = 10;
  SEMANTIC_SOURCE_TYPE_TARGET_POSE = 11;

  SEMANTIC_SOURCE_TYPE_CONSTRAINT = 20;
  SEMANTIC_SOURCE_TYPE_COMPLETION_CRITERION = 21;
  SEMANTIC_SOURCE_TYPE_VARIANT_CONTEXT = 22;

  SEMANTIC_SOURCE_TYPE_PROCESS_TRANSITION = 30;

  // Later:
  // PLANNED_TRAJECTORY
  // SPATIAL_REGION
  // ROBOT_STATE
  // ...
}

enum SemanticValueType {
  SEMANTIC_VALUE_TYPE_UNSPECIFIED = 0;

  SEMANTIC_VALUE_TYPE_ENTITY = 1;
  SEMANTIC_VALUE_TYPE_FACT = 2;
  SEMANTIC_VALUE_TYPE_ACTION = 3;

  SEMANTIC_VALUE_TYPE_SPATIAL_ANCHOR = 10;
  SEMANTIC_VALUE_TYPE_POSE = 11;
  SEMANTIC_VALUE_TYPE_GEOMETRY = 12;
  SEMANTIC_VALUE_TYPE_PATH = 13;
  SEMANTIC_VALUE_TYPE_REGION = 14;

  SEMANTIC_VALUE_TYPE_PROCESS_TRANSITION = 20;
}

message SemanticSourceRequirement {
  SemanticSourceType source = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).enum.defined_only = true
  ];
  SemanticValueType value_type = 2 [
    (buf.validate.field).required = true,
    (buf.validate.field).enum.defined_only = true
  ];

  bool optional = 3;
}
