name: Buf CI
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
  delete:
permissions:
  contents: write
  pull-requests: write
jobs:
  buf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: bufbuild/buf-action@v1
        with:
          setup_only: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run linter
        run: buf lint

      - name: Checking breaking changes
        run: buf breaking --against "https://github.com/cobotar/protocol.git#branch=main"

      - name: Generate proto messages
        run: buf generate

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: autobot
          author_email: lunding@me.com
          message: 'Generate new proto messages'
          add: '*.go'
